### ISSUE TITLE
v3.0.2 bug report

### ISSUE THREAD

**Issue by m11751** [laurent22/joplin#10219]
### Operating system

Windows

### Joplin version

v3.0.2

### Desktop version info

Joplin 3.0.2 (prod, win32)

客户端 ID: 2ace8df3d2c54e8d999af39261a8287e
同步版本：3
配置文件版本：46
支持的密钥链：否

修订：a59ad20

### Current behaviour

1.When I enter a string in an entry and press Enter, the entry disappears and the cursor jumps to another random entry. At this time, I need to edit the text in other text tools such as notepad, then search for the specified entry and copy it to joplin. I hope to solve this bug. This problem has not appeared in previous releases. Thank you.

### Expected behaviour

The above bugs appear with probability and are not inevitable problems. Please be informed.

**Comment by B0BIC** [comment]
I'm getting this when I make _any_ change to a note from within "All Notes." Modifying a note in any way causes it to disappear. The note isn't erased, it's just no longer displayed in the list. Clicking "info" on a note will do the same thing.

 Also, notes in "All Notes" are no longer displaying their notebook.

**Comment by graphit0** [comment]
probably a duplicate of #10194

**Comment by Dricc123** [comment]
duplicate of #10236

**Comment by m11751** [comment]
The least v3.0.3 still have not solve this bug

**Comment by m11751** [comment]
This bug already fixed in version 3.0.6 but Mardown can't be used

**Comment by nonobio** [comment]
https://github.com/laurent22/joplin/issues/10388#issuecomment-2114741089

**Comment by Julrob199** [comment]
Hope this gets fixed soon! This bug still exists in 3.0.7, it makes the app barely usable since weeks. Hope this i prioritized in the next update. I have the problem on the work windows computer and also here on my private linux. Thank you!!

There are duplicates of many different types, which somehow all refer to the same problem: 
#10388 
#10236 
#10194

**Comment by Julrob199** [comment]
From my point of view, this topic could be closed. Error was fixed by #10568 in [v3.0.9](https://github.com/laurent22/joplin/releases/tag/v3.0.9).
