### ISSUE TITLE
Text search doesn't show results including all partial words as expected

### ISSUE THREAD

**Issue by mcmxcdev** [laurent22/joplin#10425]
### Operating system

Linux

### Joplin version

3.0.6

### Desktop version info

Joplin 3.0.6 (prod, linux)

Client ID: f964f06935f348e1b58784c8abc9e8de
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Backup: 1.4.1

### Current behaviour

1. Have notes including the word "colorado" or "colorado in motion"
2. Search for "colorado in motion"
3. Only results with "in" will show up, not the full search string

I have 10+ notes including the word "colorado" but none of them show up in the search results, not even "colorado in motion".
 
(This is my specific use case, I assume it can be reproduced for other search terms as well)

![Screenshot from 2024-05-10 09-25-17](https://github.com/laurent22/joplin/assets/16797721/419cb790-7ada-4381-9024-01cb8059dc99)

### Expected behaviour

Full search strings separated by whitespace should be found as part of notes search results

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

We recently had a report of nonbreaking spaces causing issues with search. A partial [fix has been merged](https://github.com/laurent22/joplin/pull/10417) but is still unreleased. See [the pull request](https://github.com/laurent22/joplin/pull/10417) for details.

**Comment by personalizedrefrigerator** [comment]
The fix has been released in [version 3.0.8](https://github.com/laurent22/joplin/releases/tag/v3.0.8). If this is indeed the same issue, then,
1. making a change to one of the notes that should appear in the search results, and
2. searching for `colorado`

should cause the just-edited note to appear in search results.

**Comment by mcmxcdev** [comment]
I had a look at the newest version and searching for "colorado" finds it (just like before I think), but the issue remains that searching for "colorado in motion" (which is a company name) still doesn't result in a matched file including that wording.

**Comment by mcmxcdev** [comment]
Bump

**Comment by personalizedrefrigerator** [comment]
> I had a look at the newest version and searching for "colorado" finds it (just like before I think), but the issue remains that searching for "colorado in motion" (which is a company name) still doesn't result in a matched file including that wording.

One possibility is that the note needs to be re-indexed (if this was caused by the issue https://github.com/laurent22/joplin/pull/10417 fixed). Making a small change to the note should cause this to happen.

If that doesn't help, does starting the search with a `/` help? (For example, `/colorado in motion`, rather than `colorado in motion`). For context, `/` causes Joplin to use a different (slower) search mode.
