### ISSUE TITLE
Restore notebook from trash does not work if notebook not selected first

### ISSUE THREAD

**Issue by bgoodmansf** [laurent22/joplin#11833]
### Operating system

Windows

### Joplin version

3.2.12

### Desktop version info

Joplin 3.2.12 (prod, win32)

Client ID: d16c32bc36464e35ae2476ff20a2110a
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d6f1ca4

Freehand Drawing: 2.14.0

### Current behaviour

1. Open Joplin profile with multiple notebooks.
2. Delete a notebook (move to trash).
3. Right-click deleted notebook in trash. A context menu with "Restore notebook" appears.
4. Click "Restore notebook". Nothing happens.

### Expected behaviour

Expect deleted notebook to be restored.

If the notebook in the trash is selected first by clicking on it, then the "Restore notebook" item in the context menu works properly. The problem occurs when a notebook outside the trash is selected and you right-click the notebook in the trash without selecting it first.

![Image](https://github.com/user-attachments/assets/9d7e12cd-dff1-421b-818f-370102cfefd8)

**Comment by rabbabansh** [comment]
Can't reproduce the issue, seems to have been fixed.

**Comment by laurent22** [comment]
Also can't replicate. It seems to have been fixed

**Comment by bgoodmansf** [comment]
Still broken for me. Clicking on "Restore Notebook" does nothing. Does not dismiss the menu.

<img width="434" height="349" alt="Image" src="https://github.com/user-attachments/assets/13c50aaf-5994-4a76-b750-3379a4b3f50c" />

Joplin 3.4.12
Windows 11 25H2

Note: Be sure NOT to select the notebook in the trash first.
