### ISSUE TITLE
Android: Memory leak? 

### ISSUE THREAD

**Issue by TobiasDev** [laurent22/joplin#1493]
### Operating system
- Android

### Application
- Mobile

### Bug
Whenever I write for a longer time in Joplin on my OnePlus 3 it starts to lag a lot after a while. 

I've tried several other writing apps to make sure it isn't my keyboard or such that has the memory leak, but I only see the issues happening when writing in Joplin. 

This usually doesn't take to long after I begin to write, usually within the first 5 minutes. 

If I can help with any kind of debugging let me know here and I'll do what I can.

**Comment by hagbartus** [comment]
I am facing the same issue, OnePlus 3T here. It's really annoying and not fun the use the app after some (quite short) time.
If you want me to do some logging / tests, please let me know.

**Comment by laurent22** [comment]
Is that the issue you're having? https://github.com/facebook/react-native/issues/20119

**Comment by TobiasDev** [comment]
Yeah, that is the one!

**Comment by m-p-3** [comment]
I suffer from this issue on my Mi A1 (Android 9), and so far the only workaround I've found is a reboot. Anything else I can do to avoid rebooting?

**Comment by TobiasDev** [comment]
@m-p-3 I believe the only thing you can do is poke in the linked issue from Laurent22. It is a bug in the library and not in Joplin

**Comment by foxmask** [comment]
I'm in a situation where, now, I fear to edit / add note on android, because this problem happens each time I enter a complet sentance. (eg a todo list)
As soon as I meet this issue, I have to restart the mobile, because the keyboard (handled by gboard app) is become unusable too. :/

**Comment by laurent22** [comment]
The RN issue that tracks this problem is apparently high priority but looks like it hasn't been fixed yet. I'll upgrade relatively soon RN anyway and we'll see if it's any better.

**Comment by virtadpt** [comment]
Would downgrading to v0.49 be an option?  Reading those bug tickets, that seems to be the last rev that didn't have the slowdown bug.

**Comment by foxmask** [comment]
I would test it in case, as now I can just do one thing , reading content, not adding otherwise I have to reboot the smartphone

**Comment by laurent22** [comment]
Perhaps some hope? https://github.com/facebook/react-native/issues/20119#issuecomment-576917362

**Comment by foxmask** [comment]
Because of that, I do not use Joplin for months. I had to move on markor/syncthing :(

**Comment by laurent22** [comment]
> Because of that, I do not use Joplin for months. I had to move on markor/syncthing :(

yes it seems to affect some people more than other, maybe depending on the device or note.

**Comment by laurent22** [comment]
Apparently the text input component [was completely rewritten](https://github.com/facebook/react-native/issues/20119?email_source=notifications&email_token=AAJZ3UC6TOREJ6WEKCNYZDTQ7AAJHA5CNFSM4FJBJNFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJSVPEA#issuecomment-577066896) using React hooks so that might be good news for us. Hopefully someone can confirm this.

**Comment by laurent22** [comment]
Seems it's been confirmed - https://github.com/facebook/react-native/issues/20119#issuecomment-578650379 Now it's "only" a matter of upgrading to the latest version of React Native.

**Comment by foxmask** [comment]
that's smell good

**Comment by haeringer** [comment]
Happy to see there's a fix in sight, because I'm hardly able to use the app on my Mi A2/Android 10 device right now. Would close issue #1209 too.

**Comment by AlexandreBrown** [comment]
Same issue also occurs on desktop.
When typing relatively small notes in 1 go, (~1700 characters with maths markdown expressions), the app becomes very slow and there is a big delay when typing (I have to wait a 200ms-1000ms before each char)

I suspect this is related to this memory leak issue because when I kill the app and restart it it fixes the issue.

OS: Ubuntu 20.04 
CPU: i7 6700k
RAM: 32GB
Storage: NVMe SSD

**Comment by virtadpt** [comment]
It's still a problem for the Android version (Joplin v1.0.324v database v28) running on a Samsung SM-G965U (Android v10).  Is there any hope in sight?

**Comment by erichiller** [comment]
Same here - Samsung S8

**Comment by jbcurtin** [comment]
I've experienced a slowdown in the application on my phone too when ever the note reaches 3+ paragraphs. Any status on improving the performance of the typing on Android?

( btw, @laurent22 , we can't see if anything is being discussed in the thread @roman-r-m mentioned )

**Comment by GreatestFool** [comment]
This should seriously be looked into faster, what is the point of being able to edit if the application is to slow for it?

On my S5e I'm experiencing enough lag that it starts skipping inputs if I don't write at a literal snails pace. It takes about one to two second for each input to even be added, which when combined with then input skipping does not make for a pretty view.

As of now, the mobile application is atrocious for anything more than previewing notes.

**Comment by virtadpt** [comment]
Ticket closed, 21 April... this is why I stopped using Joplin.  It's completely unusuable.  I thought I unsubbed from this ticket thread.

**Comment by Zie0** [comment]
OnePlus 3T user here. This has impacted me for months, ever since I started depending on Joplin for note taking. When I have a longer note there is no use in using the android app and I must switch to desktop.

Most recently this happened yesterday.

**Comment by seth100** [comment]
Any update on this?
I'm not able to edit my notes in a normal way, too slow, totally annoying

**Comment by chromer030** [comment]
On android app is too slow and using 300 mb of ram !!!

**Comment by cosminribo** [comment]
Maybe this issue should be renamed, to something like:
ReactNative text editing extremely slow for text input.
The 0.63 version, used in the latest Joplin app did not solve the problem. For the moment, I'm using a different editor, and copy text to Joplin.

**Comment by laurent22** [comment]
I've just noticed an interesting technique mentioned in the upstream bug: https://github.com/facebook/react-native/issues/20119#issuecomment-714545951 Could be worth a try.

**Comment by exic** [comment]
Would it be feasible to allow external editors in the app? That could be nice anyways and would also be a good workaround.

**Comment by roman-r-m** [comment]
It may be possible, but has to be done from scratch since Android is very different from desktop.

**Comment by roman-r-m** [comment]
So I've been looking into this for a while now and while I still can't reproduce it I've noticed a potential issue.

On the native side if I log text updates coming from RN, whenever I type even a single character I see 2 updates:
* 1-character change corresponding to what I have typed
* followed by another update that replaces the whole text with itself -- I suspect this is where the slowness might be coming from.

The reason for this second update seems to be that the Note component is being redrawn way too often even when a change in props/state has no effect on the UI.

**Comment by ShivamKumar2002** [comment]
I can confirm this issue, and it's extremely problematic. Now am afraid of even making notes on android because on average before i write 1-2 notes, my phone becomes extremely laggy and lag goes on increasing. After some time I am not even able to type.

**Comment by laurent22** [comment]
I believe this issue is fixed now with the beta editor. If it happens with the beta editor too, please open a new issue.

**Comment by tsherrington** [comment]
This problem still exists with current Joplin (2.8.1) on Samsung S22 Ultra.  After having the editor open for about 60 seconds (not much typing) it slows to the point where when I type a word, it takes .5 to 1 second to appear.  Exiting the note and re-entering fixes it, but problem returns within 60 seconds.  Makes it almost unusable.  Problem doesn't exist in any other app.
I am using Samsung Keyboard.

**Comment by jdelisle5** [comment]
This issue exist still! I love Joplin but I have to use Samsung notes and copy and paste into Joplin. Is there nothing we can do to fix inside joplin?

**Comment by chromer030** [comment]
This issue persists on latest version of Joplin Android, please do something for it...
