### ISSUE TITLE
OK button Overlapped with Calendar

### ISSUE THREAD

**Issue by ishriom53tyagi** [laurent22/joplin#2768]
## Environment

Joplin version: 1.0.194
Platform: Linux

## Steps to reproduce

1. Go to any notebook
2. click on the alarm icon
3. click on the input field
![Screenshot from 2020-03-16 11-08-52](https://user-images.githubusercontent.com/36675100/76707322-22dae880-6714-11ea-98eb-fb8465211ea7.png)

## Describe what you expected to happen
Ok button should be clearly visible

![Screenshot from 2020-03-16 11-22-08 (copy)](https://user-images.githubusercontent.com/36675100/76707356-88c77000-6714-11ea-80b6-b584f71c1429.png)

**Comment by ALWISH007** [comment]
I guess the issue here is resolved.

**Comment by rossorp** [comment]
I just checked and it is still an issue with v1.0.201 on Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/1185919/80821820-652b8c80-8bd1-11ea-8758-b8c92e544dd7.png)
