### ISSUE TITLE
Application crashes when trying to print

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#3161]
See here: https://github.com/laurent22/joplin/blob/51732a5adb72f9c3a2b95f4f9aa9f6e949aa3e42/ElectronClient/InteropServiceHelper.js#L72

Maybe a Chromium bug? https://github.com/electron/electron/issues/19946

**Comment by aashimawadhwa** [comment]
i would ike to work on this issue can u please elaborate a little more?

**Comment by mcmxcdev** [comment]
I cannot reproduce this and the linked Chromium bug has been fixed in the meantime. This issue can probably be closed.

**Comment by jebofponderworthy** [comment]
File/Print does print as requested for me now, but Joplin crashes immediately after.  Ubuntu 20.04, up to date, and Joplin 2.8.8 (see below). How may I help?

Joplin 2.8.8 (prod, linux)

Client ID: 20f0a19000124501950148661e6a0833
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: c2a6a13eb

**Comment by Katzinski** [comment]
Since the issue persists, you might work around it by

1. File > Export ... > PDF file
2. Save as PDF
3. In case your PDF links to other files, these links will not work -> open PDF in document viewer and re-save, this time without the links
