### ISSUE TITLE
High cpu usage / hanging system when opening Joplin under Wayland

### ISSUE THREAD

**Issue by diogogomes** [laurent22/joplin#3384]
## Environment

Joplin version: 2.1.9 (this issue already existed in some previous versions)
Platform: Linux
OS specifics:
  - Arch with Plasma
  - Centos 8
  - Debian 10 with Gnome Desktop with Wayland
  - Fedora 32

## Steps to reproduce

1. Log in in a Gnome session with Wayland / Mutter
1.Click to open the Joplin app
2. Wait until system hangs and/or crash

## Describe what you expected to happen

It's expected the application opens normally without hanging the machine when using the Wayland protocol.

## Notes

This only happens under the Mutter window manager and Wayland. Joplin opens immediately with normal cpu usage under other window managers.

## Urls

[Mutter](https://gitlab.gnome.org/GNOME/mutter)

## Logfile

**Log from the terminal:**
``(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397 ``

**Log from developer tools:**
```
DevTools failed to parse SourceMap: file:///tmp/.mount_joplinywn0Xg/resources/app.asar/gui/ResourceScreen.js.map
/tmp/.mount_joplinyw…r/lib/logger.js:126 23:12:28 Starting Clipper server on port 41184
/tmp/.mount_joplinyw…evelopment.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(NoteTextViewerComponent), Connect(NoteToolbar), Connect(TagItemComponent), Connect(TagListComponent), Connect(ToolbarComponent), ReactAce
/tmp/.mount_joplinyw…evelopment.js:11494 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(NoteTextViewerComponent), Connect(NoteToolbar), Connect(TagItemComponent), Connect(TagListComponent), Connect(ToolbarComponent)
3
/tmp/.mount_joplinyw…essageHandler.js:30 Got ipc-message: noteRenderComplete undefined
```

**Comment by BsNoSi** [comment]
## Environment
- Version 1.0.223(prerelease)
- Windows 10x64 pro

## Effect
- opens four threads (Taskmanager)
- no window opens → no access → "useless"

## Workaround

- returned to version 1.0.220

**Comment by diogogomes** [comment]
I updated the issue with logs from terminal.

@laurent22, you removed the bug tag for some reason related to the lack of logs or because you do not consider a bug? Thank you.

this issue already existed in some previous versions

**Comment by laurent22** [comment]
The GitHub tracker is only for actionable issues, and unfortunately while this bug might happen in your computer it's not possible to replicate it on our side. The log is just the usual warnings.

**Comment by laurent22** [comment]
Does it happen with all the notes or just some of them?

And isn't it the same as this bug https://github.com/laurent22/joplin/issues/3114

**Comment by diogogomes** [comment]
Understand (about the tracker).

It's happening when I try to open the app. I'm aware of the issue with the kernel 5.5 but I missed the references to the high cpu usage and I decided to open this issue.

Can be related. I'll try later with a lower version of the kernel on another machine to be sure if is related or not.

I'll leave a message then. Thank you

**Comment by diogogomes** [comment]
I tested on another machine with **kernel 4.19** and the result was the same: **high processor usage when the application is opened**.

**Comment by BsNoSi** [comment]
(For me) Solved with →
Joplin 1.0.224 (prod, win32)
Revision: 1899d866 (master)

**Comment by diogogomes** [comment]
For me, the problem persists in the version 1.0.224.

**Comment by diogogomes** [comment]
The issue persists in the version 1.0.227 and kernel 5.4, 5.5, 5.6 and 5.7.

Note: Related with Gnome Sheel and not with kernel?

**Comment by diogogomes** [comment]
@laurent22, I just made some progess to debug this issue.

**This only happens under Wayland protocol. Joplin opens immediately with normal cpu usage under Xorg.**

[Wayland webpage](https://wayland.freedesktop.org/)

Please tell me if I can help providing more information.

**Comment by isaiahfrantz** [comment]
Ive been stuck on 1.0.179 on fedora 32 for this very reason (ie I get the same electron message and then nothing).
I havent tried reverting the kernel because:
- I dont really want to run an old kernel just for a note app 
- I heard that the kernel issue had been resolved?

I keep trying every release (and some pre-releases) to no avail :(
(FYI I am using appimage home & config directories to keep attempts with other releases separated from my 1.0.179 data so they should be running clean)

**Comment by diogogomes** [comment]
I updated the issue with the Fedora 32.

@isaiahfrantz, can you test with Xorg and tell me if the issue persists?

> I heard that the kernel issue had been resolved?

I tested with the old 4.19 kernel and I suspect this issue is not related with the kernel.

**Comment by diogogomes** [comment]
The issue persists in the version 1.0.233.

**Comment by hateusingusername** [comment]
Remove the config directory   ~/.config/Joplin/ and run the Joplin app again.
This works fine for me.😁

**Comment by diogogomes** [comment]
The issue persists in the version 1.0.242.

**Comment by JCTechSol** [comment]
I have been following these types of threads since 1.0.207 (the last version that worked for me)
I've just discovered a fix for my situation, maybe it will help others. While trying to find some smoking gun I came across the fact that I could not update nodejs.
`Error: 
 Problem: cannot install both nodejs-2:14.11.0-1nodesource.x86_64 and nodejs-1:10.19.0-2.module_el8.1.0+296+bef51246.x86_64
  - package npm-1:6.13.4-1.10.19.0.2.module_el8.1.0+296+bef51246.x86_64 requires nodejs = 1:10.19.0-2.module_el8.1.0+296+bef51246, but none of the providers can be installed
  - cannot install the best update candidate for package nodejs-1:10.19.0-2.module_el8.1.0+296+bef51246.x86_64
  - problem with installed package npm-1:6.13.4-1.10.19.0.2.module_el8.1.0+296+bef51246.x86_64
`
After removing npm Joplin works as expected.
NAME="CentOS Linux"
VERSION="8 (Core)"
KERNEL="4.18.0-193.14.2.el8_2.x86_64"

**Comment by JCTechSol** [comment]
Well that was short lived. It hangs again now on launch...I really don't know why.
I even installed 1.1.4 and still hangs on launch...

**Comment by JCTechSol** [comment]
Since the upgrade to 1.1.4 I can launch the AppImage from terminal and it will open without hanging. At least there is a work around...

**Comment by diogogomes** [comment]
@JCTechSol, I have been using the terminal method but sometimes I have to cancel the process and start again to work.

I did some testing with Debian Unstable with a newer version of xwayland and it seems to have worked well.

Still, I can't confirm that it's due to xwayland because I ran out of time to continue my tests.

**Comment by JCTechSol** [comment]
Today I wasn't able to open Joplin from terminal. It froze just like with the app shortcut. After repeated attempts and combinations I was able to get it to launch after I tried lunching an old version. It presents an error message about the database being newer then expected. After I press OK and dismiss that, I can then open the appimage of 1.1.4 successfully. I'm not sure why that combination works.

**Comment by JCTechSol** [comment]
There is some more oddities with this workaround as well. I've discovered that if I try lunching the 1.0.241.AppImage it doesn't work, in fact it will crash the computer. But if I try lunching the 1.0.207.AppImage the database error successfully pops up saying that the database is newer then expected etc. Then I can successfully lunch the 1.1.4.Applmage. It seems like such a random piece of information but I can faithfully reproduce this behavior every time so I think its significant.

**Comment by smalltimer** [comment]
Hi, I am on Debian 10 and use the .deb from github releases. Same issue: Joplin freezes the system on Wayland. This is very counter-productive :( I lost some unsaved work and computations.

**Comment by diogogomes** [comment]
Note: The issue persists in the version 1.2.6.

**Comment by JCTechSol** [comment]
I can also confirm the same behavior is present in 1.2.6. Also the same workaround works. Launching the 1.0.207 appImage, click ok on the error message, then launching the 1.2.6 appimage

**Comment by JCTechSol** [comment]
I haven't be able to do a lot of testing but it appears 1.3 won't run at all. Thankfully I am still able to run 1.2.6 with the workaround as it looks like no modification\upgrade has happen on the database. (Launching the 1.0.207 appImage, click ok on the error message, then launching the 1.2.6 appimage)

**Comment by JCTechSol** [comment]
So I've just installed 1.4.18 using the recommended method (
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash) and it opened up flawlessly....I'm excited but cautious. I will do some more testing and update here again...

**Comment by JCTechSol** [comment]
After a reboot now Jopin won't open at all. Not even the work around works any more. Tried updating to 1.4.19, no change. Installed the latest CentOS 8 update, no change. I can't access my Joplin notes at all now...

**Comment by JCTechSol** [comment]
Removing the following folders and reinstalling using the recommended wget method fixed the issue. Joplin will now open again...
~/.joplin-bin
~/.joplin
~/.config/@joplin
~/.config/Joplin
~/.config/joplin-desktop

**Comment by JCTechSol** [comment]
Reboot seems to break things. I had to remove the folders again and reinstall. I tried just removing the ~/.joplin folder and reinstalling but it still crashed. I had to remove all 4 and reinstall to get it to work again.

~/.joplin
~/.config/@joplin
~/.config/Joplin
~/.config/joplin-desktop

The only thing that I change or configure after install is:

1. Configure darkmore in appearance
2. Setup dropbox sync
3. Set encryption to decrypt the notes.

I wonder if one of these is responsible for the crashing behavior...

**Comment by JCTechSol** [comment]
It seems that deleting ~/.config/@joplin and ~/.config/joplin-desktop are enough to get it working again.
I will test to see if darkmode has anything to do with it...

**Comment by JCTechSol** [comment]
man this problem keeps getting stranger and stranger...
Test darkmode, not the issue here, with our without darkmode the same crash is experienced on opening. That leaves encryption\dropbox and related to the issue.

I tested this morning with 1.5.11.... same issues.
I wanted to test my old workaround of opening an old version, getting an error prompt and then opening the new version, BUT instead of giving me an error prompt, joplin.1.2.6.AppImage actually opened! I was not expecting this and thought this might be bad news for my notebook. But I noticed something I've never seen before, a conflict notebook in red. It had a copy of one of my notes in it. I examined it closely and did not notice any issues or differences from the actual note. Just to be sure I wanted to export it but I wasn't able to. Joplin would go through the motion and create the _resource folder but nothing else and no data was in the _resource folder. I could export other notes, just not this conflict one. So I decided to delete the conflict note, sync and close. I was then able to open 1.5.11 with no issues....

Was the problem this whole time!?!? 
A corrupted conflict note?!?!?! 
That would explain why it would only open if no notebook was existing and would break after I synced it. 

If this is indeed the root issue. Is there anyway this can be identified or cleaned up instead of just hanging?

**Comment by diogogomes** [comment]
Update: The issue persists in the version 1.6.7.

---

@JCTechSol,

> A corrupted conflict note?!?!?!

I don't think so. I don't have any corrupted note. I can't confirm but I'm 90% sure that is a compatibility issue between Joplin (and maybe electronjs) and the implementation of Wayland (xwayland)

**Comment by ddtuan99** [comment]
Confirm in Debian 10.8. Everytime I open Joplin, I have to open process monitor beside to end Joplin processes, if not, my system will freeze/hang because Joplin demands extemely high CPU usage (if this happens, there is no UI showed up yet). Try to open and kill the processes agian and again until Joplin opens normally.

@laurent22 Could you have a look on this issue?

**Comment by wisp3rwind** [comment]
> I don't think so. I don't have any corrupted note. I can't confirm but I'm 90% sure that is a compatibility issue between Joplin (and maybe electronjs) and the implementation of Wayland (xwayland)

FWIW: I'm also seeing high CPU usage during sync (not hanging the desktop, but causing substantial lag), and in particular, the processes that consume all the CPU are the `--type=gpu-process` and `--type=renderer` issue. That would indeed point at a problem related to the interaction between electron and xwayland.

This is Joplin 1.7.11, xwayland 21.0.99.902, Mutter 3.38.4. I'll check sway on next reboot.

**Comment by diogogomes** [comment]
> **EDIT:** On sway, CPU usage is significantly lower (~half), and much more importantly, it goes to essentially 0% as soon as the Joplin window is completely obscured. IIRC, this wasn't the case on Mutter.

@wisp3rwind, thanks for the test.

Today I updated Xwayland in Debian and the problem remained. After the update and after reading your suggestion I'm not sure if it's Xwayland any more.

Maybe it's the composer Mutter like you said. I just can't figure out why Joplin is the only Electron application that has the problem with Mutter since it doesn't have elaborate graphics.

Everything works fine on Xorg. If it's Mutter's problem, shouldn't it persist in Xorg? (I really don't know)

**Comment by diogogomes** [comment]
> unfortunately while this bug might happen in your computer it's not possible to replicate it on our side

@laurent22, does this mean that it works in your side with Gnome and Wayland or that you have not tried with the reported operating systems / Linux distributions?

**Comment by wisp3rwind** [comment]
> Today I updated Xwayland in Debian and the problem remained. After the update and after reading your suggestion I'm not sure if it's Xwayland any more.
> 
> Maybe it's the composer Mutter like you said. I just can't figure out why Joplin is the only Electron application that has the problem with Mutter since it doesn't have elaborate graphics.
> 
> Everything works fine on Xorg. If it's Mutter's problem, shouldn't it persist in Xorg? (I really don't know)

I don't think so, running through Xwayland will use completely different code on the compositor side. How elaborate the graphics are also shouldn't matter, the Xorg/Wayland protocols are really only about sending the graphics to the compositor after the client has rendered them.

I guess this one will be really hard to pin down, there's simply too many hard-to-debug components which could be the problem. I'm not going to invest any further time into debugging here. FWIW, what I'm seeing also seems to be similar to https://github.com/laurent22/joplin/issues/1284 (but without crashes, only increased FF CPU usage). As is noted in that issue, it's really unexpected that both processes could influence each other; the only sensible explanation I have right now is that they are fighting over some resource.

**Comment by diogogomes** [comment]
> On sway, CPU usage is significantly lower (~half), and much more importantly, it goes to essentially 0% as soon as the Joplin window is completely obscured. IIRC, this wasn't the case on Mutter.

@wisp3rwind, I confirmed the same behaviour with KDE Plasma. Thanks again for the help.

I have updated the issue description with this new information.

**Comment by wisp3rwind** [comment]
> > On sway, CPU usage is significantly lower (~half), and much more importantly, it goes to essentially 0% as soon as the Joplin window is completely obscured. IIRC, this wasn't the case on Mutter.
> 
> @wisp3rwind, I confirmed the same behaviour with KDE Plasma. Thanks again for the help.

You're welcome :) I've since switched to a different note-taking application, so I certainly won't be investing any more time in debugging this. Unfortunately, Wayland still seems to be too niche for anybody to really care. There might be a chance that this will be resolved when native Wayland support is enabled for electron (https://github.com/electron/electron/issues/9056, https://github.com/electron/electron/issues/10915)

**Comment by dmirubtsov** [comment]
The same for Xorg/Plasma on Arch

**Comment by diogogomes** [comment]
@dmirubtsov, can you check if you have Mutter installed? Thank you.

**Comment by Peter4487** [comment]
FWIW I'm seeing this problem running Gnome / Wayland too. Crashes the whole thing, very frustrating. If you look at the time stamps in the log below, you'll see a multi-minute pause after ""DecryptionWorker: completed decryption."

> 2021-08-17 11:43:09: App: "Profile directory: /home/XXX/.config/joplin-desktop"
> 2021-08-17 11:43:09: "Database was open successfully"
> 2021-08-17 11:43:09: "Checking for database schema update..."
> 2021-08-17 11:43:09: "Current database version", "{"version":39,"table_fields_version":39}"
> 2021-08-17 11:43:09: "Upgrading database from version 39"
> 2021-08-17 11:43:09: "New version: 39. Previously recorded version: 39"
> 2021-08-17 11:43:09: "KeychainService: checking if keychain supported"
> 2021-08-17 11:43:09: "KeychainService: check was already done - skipping. Supported:", "0"
> 2021-08-17 11:43:09: handleSyncStartupOperation: "Processing operation:", "0"
> 2021-08-17 11:43:09: App: "Client ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "ResourceFetcher: Auto-add resources: Mode: always"
> 2021-08-17 11:43:09: "ResourceFetcher: Auto-added resources: 0"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: "app.start: doing regular boot"
> 2021-08-17 11:43:09: App: "Refreshing notes:", "null", "null"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: "Trying to load 1 master keys..."
> 2021-08-17 11:43:09: "Loaded master keys: 1"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "10000"
> 2021-08-17 11:43:09: App: "Refreshing notes:", "2", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> 2021-08-17 11:43:09: "Scheduling sync operation...", "1000"
> 2021-08-17 11:43:09: RevisionService: "RevisionService::runInBackground: Starting background service with revision collection interval 600000"
> 2021-08-17 11:43:09: SpellCheckerServiceDriverNative: "Set effective language from "en-US" to "en-US""
> 2021-08-17 11:43:11: "Loading existing note", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> 2021-08-17 11:43:11: "Preparing scheduled sync"
> 2021-08-17 11:43:11: "DecryptionWorker: starting decryption..."
> 2021-08-17 11:43:11: "Starting scheduled sync"
> 2021-08-17 11:43:12: "Loaded note:", "{"id":"XXXXXXXXXXXXXXXXXXXXXXXXXX","parent_id":"XXXXXXXXXXXXXXXXXXXXXXXXXX","title":STUFF","created_time":1628369195581,"updated_time":1628295474986,"is_conflict":0,"latitude":"42.31200000","longitude":"-71.10810000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplin-desktop","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"user_created_time":1628444195781,"user_updated_time":162345474586,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"share_id":"","conflict_original_id":"","type_":1}"
> 2021-08-17 11:43:13: "Saving settings..."
> 2021-08-17 11:43:13: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1629336293374]"
> 2021-08-17 11:43:13: "Indexing resources..."
> 2021-08-17 11:43:13: "ResourceService::indexNoteResources: Start"
> 2021-08-17 11:43:13: RevisionService: "RevisionService::maintenance: Starting..."
> 2021-08-17 11:43:13: RevisionService: "RevisionService::maintenance: Service is enabled"
> 2021-08-17 11:43:14: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
> 2021-08-17 11:43:14: "ResourceService::indexNoteResources: Completed"
> 2021-08-17 11:43:14: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
> 2021-08-17 11:43:14: "DecryptionWorker: completed decryption."
> 2021-08-17 11:43:14: models/Folder: "updateNoteShareIds: notes to update:", "0"
> 2021-08-17 11:43:14: models/Folder: "updateResourceShareIds: resources to update:", "0"
> 2021-08-17 11:43:14: FileApi: "get info.json"
> 2021-08-17 11:43:14: RevisionService: "RevisionService::maintenance: Done in 558ms"
> 2021-08-17 11:43:14: "Settings have been saved."
> 2021-08-17 11:43:16: "Sync target info:", "{"version":2}"
> 2021-08-17 11:43:16: FileApi: "list "
> 2021-08-17 11:43:16: FileApi: "list "
> 2021-08-17 11:43:19: "SearchEngine: Updating FTS table..."
> 2021-08-17 11:43:19: "SearchEngine: Updated FTS table in 1ms. Inserted: 0. Deleted: 0"
> 2021-08-17 11:43:20: FileApi: "put temp/timeCheck844728.txt", "null"
> 2021-08-17 11:43:26: FileApi: "stat temp/timeCheck844728.txt"
> 2021-08-17 11:43:31: FileApi: "delete temp/timeCheck844728.txt"
> 2021-08-17 11:43:31: FileApi: "put locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXXXX.json", "null"
> 2021-08-17 11:43:39: "ResourceService::indexNoteResources: Start"
> 2021-08-17 11:43:39: "ResourceService::indexNoteResources: Completed"
> 2021-08-17 11:43:39: "ResourceService::deleteOrphanResources:", "[]"
> 2021-08-17 11:43:40: FileApi: "list "
> 2021-08-17 11:43:40: FileApi: "list "
> 2021-08-17 11:43:44: FileApi: "delta "
> 2021-08-17 11:43:46: "BasicDelta: Report: {"timestamp":1623556711000,"older":139,"newer":0,"equal":1}"
> 2021-08-17 11:43:46: "Sync: fetchingTotal: Fetching delta items from sync target"
> 2021-08-17 11:43:47: FileApi: "delete locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXX.json"
> 2021-08-17 11:43:47: "Saving settings..."
> 2021-08-17 11:43:47: "Settings have been saved."
> 2021-08-17 11:43:51: "Sync: finished: Synchronisation finished [1629292421374]"
> 2021-08-17 11:43:51: "Operations completed: "
> 2021-08-17 11:43:51: "fetchingTotal: -"
> 2021-08-17 11:43:51: "Total folders: 19"
> 2021-08-17 11:43:51: "Total notes: 38"
> 2021-08-17 11:43:51: "Total resources: 8"
> 2021-08-17 11:43:51: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:43:51: "Updating all notifications..."
> 2021-08-17 11:43:51: "Garbage collecting alarms..."
> 2021-08-17 11:43:51: "Sync has finished and note has never been changed - reloading it"
> 2021-08-17 11:43:52: "Saving settings..."
> 2021-08-17 11:43:52: "Settings have been saved."
> 2021-08-17 11:43:52: "DecryptionWorker: starting decryption..."
> 2021-08-17 11:43:52: "DecryptionWorker: completed decryption."
> 2021-08-17 11:48:51: "Running background sync on timer..."
> 2021-08-17 11:48:51: "Scheduling sync operation...", "0"
> 2021-08-17 11:48:51: "Preparing scheduled sync"
> 2021-08-17 11:48:51: "Starting scheduled sync"
> 2021-08-17 11:48:51: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1628456331871]"
> 2021-08-17 11:48:51: "Indexing resources..."
> 2021-08-17 11:48:51: "ResourceService::indexNoteResources: Start"
> 2021-08-17 11:48:52: "ResourceService::indexNoteResources: Completed"
> 2021-08-17 11:48:52: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
> 2021-08-17 11:48:52: models/Folder: "updateNoteShareIds: notes to update:", "0"
> 2021-08-17 11:48:52: models/Folder: "updateResourceShareIds: resources to update:", "0"
> 2021-08-17 11:48:52: FileApi: "get info.json"
> 2021-08-17 11:48:55: "Sync target info:", "{"version":2}"
> 2021-08-17 11:48:55: FileApi: "list "
> 2021-08-17 11:48:55: FileApi: "list "
> 2021-08-17 11:48:57: FileApi: "put locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXX.json", "null"
> 2021-08-17 11:49:00: FileApi: "list "
> 2021-08-17 11:49:00: FileApi: "list "
> 2021-08-17 11:49:03: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
> 2021-08-17 11:49:03: "TaskQueue.stop: syncDownload: Done, waited for 0"
> 2021-08-17 11:49:03: FileApi: "delta "
> 2021-08-17 11:49:05: "BasicDelta: Report: {"timestamp":1628352231000,"older":139,"newer":0,"equal":1}"
> 2021-08-17 11:49:05: "Sync: fetchingTotal: Fetching delta items from sync target"
> 2021-08-17 11:49:05: FileApi: "delete locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json"
> 2021-08-17 11:49:05: "Saving settings..."
> 2021-08-17 11:49:05: "Settings have been saved."
> 2021-08-17 11:49:08: "Sync: finished: Synchronisation finished [1629456471]"
> 2021-08-17 11:49:09: "Operations completed: "
> 2021-08-17 11:49:09: "fetchingTotal: -"
> 2021-08-17 11:49:09: "Total folders: 19"
> 2021-08-17 11:49:09: "Total notes: 38"
> 2021-08-17 11:49:09: "Total resources: 8"
> 2021-08-17 11:49:09: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:49:09: "Sync has finished and note has never been changed - reloading it"
> 2021-08-17 11:49:09: "Saving settings..."
> 2021-08-17 11:49:09: "Settings have been saved."
> 2021-08-17 11:49:10: "DecryptionWorker: starting decryption..."
> 2021-08-17 11:49:10: "DecryptionWorker: completed decryption."
> 2021-08-17 11:53:09: RevisionService: "RevisionService::maintenance: Starting..."
> 2021-08-17 11:53:09: RevisionService: "RevisionService::maintenance: Service is enabled"
> 2021-08-17 11:53:09: RevisionService: "RevisionService::collectRevisions: Created revisions for 0 notes"
> 2021-08-17 11:53:09: RevisionService: "RevisionService::maintenance: Done in 105ms"
> 2021-08-17 11:54:09: "Running background sync on timer..."
> 2021-08-17 11:54:09: "Scheduling sync operation...", "0"
> 2021-08-17 11:54:09: "Preparing scheduled sync"
> 2021-08-17 11:54:09: "Starting scheduled sync"
> 2021-08-17 11:54:09: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [16295234459221]"
> 2021-08-17 11:54:09: "Indexing resources..."
> 2021-08-17 11:54:09: "ResourceService::indexNoteResources: Start"
> 2021-08-17 11:54:09: "ResourceService::indexNoteResources: Completed"
> 2021-08-17 11:54:09: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
> 2021-08-17 11:54:09: models/Folder: "updateNoteShareIds: notes to update:", "0"
> 2021-08-17 11:54:09: models/Folder: "updateResourceShareIds: resources to update:", "0"
> 2021-08-17 11:54:09: FileApi: "get info.json"
> 2021-08-17 11:54:11: "Sync target info:", "{"version":2}"
> 2021-08-17 11:54:11: FileApi: "list "
> 2021-08-17 11:54:11: FileApi: "list "
> 2021-08-17 11:54:12: FileApi: "put temp/timeCheck163485.txt", "null"
> 2021-08-17 11:54:17: FileApi: "stat temp/timeCheck163485.txt"
> 2021-08-17 11:54:19: FileApi: "delete temp/timeCheck163485.txt"
> 2021-08-17 11:54:19: FileApi: "put locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json", "null"
> 2021-08-17 11:54:22: FileApi: "list "
> 2021-08-17 11:54:22: FileApi: "list "
> 2021-08-17 11:54:24: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
> 2021-08-17 11:54:24: "TaskQueue.stop: syncDownload: Done, waited for 0"
> 2021-08-17 11:54:24: FileApi: "delta "
> 2021-08-17 11:54:25: "BasicDelta: Report: {"timestamp":1628424661000,"older":139,"newer":0,"equal":1}"
> 2021-08-17 11:54:25: "Sync: fetchingTotal: Fetching delta items from sync target"
> 2021-08-17 11:54:25: FileApi: "delete locks/sync_desktop_XXXXXXXXXXXXXXXX.json"
> 2021-08-17 11:54:26: "Saving settings..."
> 2021-08-17 11:54:26: "Settings have been saved."
> 2021-08-17 11:54:28: "Sync: finished: Synchronisation finished [1629255549221]"
> 2021-08-17 11:54:28: "Operations completed: "
> 2021-08-17 11:54:28: "fetchingTotal: -"
> 2021-08-17 11:54:28: "Total folders: 19"
> 2021-08-17 11:54:28: "Total notes: 38"
> 2021-08-17 11:54:28: "Total resources: 8"
> 2021-08-17 11:54:28: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:54:28: "Sync has finished and note has never been changed - reloading it"
> 2021-08-17 11:54:28: "Saving settings..."
> 2021-08-17 11:54:28: "Settings have been saved."
> 2021-08-17 11:54:29: "DecryptionWorker: starting decryption..."
> 2021-08-17 11:54:29: "DecryptionWorker: completed decryption."
> 2021-08-17 11:59:28: "Running background sync on timer..."
> 2021-08-17 11:59:28: "Scheduling sync operation...", "0"
> 2021-08-17 11:59:28: "Preparing scheduled sync"
> 2021-08-17 11:59:28: "Starting scheduled sync"
> 2021-08-17 11:59:28: "Sync: starting: Starting synchronisation to target 5... supportsAccurateTimestamp = false; supportsMultiPut = false [1629345968281]"
> 2021-08-17 11:59:28: "Indexing resources..."
> 2021-08-17 11:59:28: "ResourceService::indexNoteResources: Start"
> 2021-08-17 11:59:28: "ResourceService::indexNoteResources: Completed"
> 2021-08-17 11:59:28: models/Folder: "updateFolderShareIds:", "{"shareUpdateCount":0,"unshareUpdateCount":0}"
> 2021-08-17 11:59:28: models/Folder: "updateNoteShareIds: notes to update:", "0"
> 2021-08-17 11:59:28: models/Folder: "updateResourceShareIds: resources to update:", "0"
> 2021-08-17 11:59:28: FileApi: "get info.json"
> 2021-08-17 11:59:30: "Sync target info:", "{"version":2}"
> 2021-08-17 11:59:30: FileApi: "list "
> 2021-08-17 11:59:30: FileApi: "list "
> 2021-08-17 11:59:33: FileApi: "put locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json", "null"
> 2021-08-17 11:59:34: FileApi: "list "
> 2021-08-17 11:59:34: FileApi: "list "
> 2021-08-17 11:59:38: "TaskQueue.stop: syncDownload: waiting for tasks to complete: 0"
> 2021-08-17 11:59:38: "TaskQueue.stop: syncDownload: Done, waited for 0"
> 2021-08-17 11:59:38: FileApi: "delta "
> 2021-08-17 11:59:40: "BasicDelta: Report: {"timestamp":1628254611000,"older":139,"newer":0,"equal":1}"
> 2021-08-17 11:59:40: "Sync: fetchingTotal: Fetching delta items from sync target"
> 2021-08-17 11:59:40: FileApi: "delete locks/sync_desktop_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json"
> 2021-08-17 11:59:41: "Saving settings..."
> 2021-08-17 11:59:41: "Settings have been saved."
> 2021-08-17 11:59:45: "Sync: finished: Synchronisation finished [1629215968281]"
> 2021-08-17 11:59:45: "Operations completed: "
> 2021-08-17 11:59:45: "fetchingTotal: -"
> 2021-08-17 11:59:45: "Total folders: 19"
> 2021-08-17 11:59:45: "Total notes: 38"
> 2021-08-17 11:59:45: "Total resources: 8"
> 2021-08-17 11:59:45: "Setting up recurrent sync with interval 300"
> 2021-08-17 11:59:45: "Sync has finished and note has never been changed - reloading it"
> 2021-08-17 11:59:45: "Saving settings..."
> 2021-08-17 11:59:45: "Settings have been saved."
> 2021-08-17 11:59:46: "DecryptionWorker: starting decryption..."
> 2021-08-17 11:59:46: "DecryptionWorker: completed decryption."
>

**Comment by Peter4487** [comment]
This is still an issue

**Comment by diogogomes** [comment]
After updating Joplin to version 2.6.1 the problem came back but in a different way: this time Joplin is slow, uses 100% of a core and the synchronization icon keeps spinning.

@laurent22, can you open this issue again or shall I create a new one since it might be a different problem?

Thank you

**Comment by diogogomes** [comment]
I resolved my issue by disabling the Untagged extension.

Check if you have the same extension activated.

**Comment by scaleoutsean** [comment]
> I resolved my issue by disabling the Untagged extension.
> Check if you have the same extension activated.

I don't have any extensions enabled, but that was a good general direction - what helps in my case is running Joplin in Safe Mode which seems to disable something that uses a lot of CPU. In normal mode, Joplin uses 200% CPU and CPU overheats within 1 minute; in Safe Mode it uses 10-30% and there's no problem.

I run it on Ubuntu 20.04 (Mate) and the high CPU utilization problem doesn't appear just on Joplin startup or when syncing - in my case it's all the time.

**Comment by NicolasLeboeuf** [comment]
Hey there.

I've just migrated to a new laptop with Ubuntu 22.04 (Gnome3, Wayland) and I have this issue. I was on Windows before and liked Joplin, but I can no longer keep it open all the time as it takes 7-8% of my CPU (16 cores, ouch) and my laptop fan is getting crazy.

I'm using a pure vanilla Joplin, last version available 2.8.8

![Capture d’écran du 2022-09-07 14-48-59](https://user-images.githubusercontent.com/62602652/188882396-80ac2698-3397-40f0-9e35-f554fee09c9b.png)
Here you can see my CPU. First half: Joplin running, second half: Joplin stopped.

**Comment by srajan0149** [comment]
This issue seems to be resolved, can anybody else confirm?

**Comment by diogogomes** [comment]
Hello @srajan0149,

Yes from my side.
