### ISSUE TITLE
"New Sub-notebook" missing from menus?

### ISSUE THREAD

**Issue by rroblak** [laurent22/joplin#3496]
I don't know if I missed an update on this or if this is a bug, but I'm no longer seeing the "New Sub-notebook" item in the toolbar menu or Notebook context menu:

![image](https://user-images.githubusercontent.com/103835/87452308-ecc04f00-c5b5-11ea-9b9f-1046e50360b2.png)

![image](https://user-images.githubusercontent.com/103835/87452330-f5188a00-c5b5-11ea-94d7-74f6699cf35a.png)

Was this intentional? It means that whenever I want to create a new sub-notebook I now have to create it and then drag it to its parent rather than it being created in the proper location to begin with.

## Environment

Joplin version: 1.0.227 (prod, darwin)
Platform: Desktop
OS specifics: macOS Mojave Version 10.14.6

## Steps to reproduce

1. Go to the _File_ toolbar or context-click (usually right-lick) on an existing notebook in the sidebar.

## Describe what you expected to happen

For there to be a _New Sub-notebook_ item in the menu that allows me to create a sub-notebook of the currently-selected notebook.

## Logfile

N/A

**Comment by laurent22** [comment]
Should be fixed in latest release: https://github.com/laurent22/joplin/releases/tag/v1.0.229

**Comment by rroblak** [comment]
@laurent22 Thanks for the fast response!

Unfortunately, I'm still seeing the issue on v1.0.229:

![image](https://user-images.githubusercontent.com/103835/87610011-fbdbf580-c6b8-11ea-9df7-58c6527443cf.png)

**Comment by laurent22** [comment]
It will be in the release after that actually, commit b770ffda4d4c007f65fb3dc6b2e86cde7ce57093

**Comment by bibucket** [comment]
> It will be in the release after that actually, commit [b770ffd](https://github.com/laurent22/joplin/commit/b770ffda4d4c007f65fb3dc6b2e86cde7ce57093)

There is syntax error in line 290:
new MenuItem(CommandService.instance().commandToMenuItem('newNotebook', null, { parentId: itemId })),

should removed the comma:
new MenuItem(CommandService.instance().commandToMenuItem('newNotebook', null, { parentId: itemId }))
