### ISSUE TITLE
Joplin Desktop: No longer able to create subnotebook

### ISSUE THREAD

**Issue by ncatanchin** [laurent22/joplin#3527]
## Environment

Joplin version: Joplin for Desktop v1.0.229 (prod, win32)
Platform: Windows
OS specifics: Windows 10 - Latest updates

## Steps to reproduce

1. Right click on a notebook in left panel
2. Do not see "Create as subnotebook" (can't remember exact wording)

## Describe what you expected to happen
Expected to see option to create subnotebook

**Comment by laurent22** [comment]
Fixed in next version

**Comment by ncatanchin** [comment]
Have updated a couple of times @laurent22 - still can't see this functionality
