### ISSUE TITLE
Error: Cannot acquire sync lock after upgrading to 1.0.242 - Linux Desktop App

### ISSUE THREAD

**Issue by mistermoutan** [laurent22/joplin#3729]
After updating desktop linux app to 1.0.241 (then updated to 1.0.242 but the problem remains)  syncing is not working. Sync Target is Dropbox. The error I'm getting is  "Error: Cannot acquire sync lock: either the lock could be written but not read back. Or it was expired before it was read again." I have tried uninstalling Jopling both removing  ~joplin/, ~/.config/Joplin and ~.config/joplin-deesktop and re linking Joplin to Dropbox  but the problem remains. The Android App was also updated to 1.0.339 shortly before the desktop one and is working well.

The logs show a "failed to parse SourceMap" issue which I assume is relevant since sync related files (amongst others) are showing up there.

## Environment

Joplin version: 1.0.242
Platform: Linux 
OS specifics:  Fedora 32

## Steps to reproduce

1. Update to Joplin 1.0.242
2. Attempt to Sync to Dropbox Target

(Update Android App to 1.0.339 before this steps and sync?)

## Logfile

The output from the develepor tools console is below:

![2020-09-08_13-09-1599572929](https://user-images.githubusercontent.com/45517674/92473960-d35d0d00-f1ca-11ea-9131-8260aee645d3.jpg)
![2020-09-08_13-09-1599572900](https://user-images.githubusercontent.com/45517674/92473973-d5bf6700-f1ca-11ea-8736-601cd99a1db2.jpg)

**Comment by sylvain-75** [comment]
Hello 
I think its not the platform:
I have the same problem on windows 10  2004 
bests regards

**Comment by laurent22** [comment]
A few users had this error but I can't replicate it nor narrow it down to what might be causing it. Just in case could you check the content of these two files and let me know what it is?

https://www.dropbox.com/home/Apps/JoplinDev?preview=info.json (it should say `{"version":2}`)

https://www.dropbox.com/home/Apps/JoplinDev/.sync?preview=version.txt (It should say just `2`)

**Comment by mistermoutan** [comment]
Thanks for the quick reply.

Both files have the expected content. Please provide updates if you are able to figure this out, I'll do the same on my end.

**Comment by laurent22** [comment]
This issue might be due to incorrect system time so if it happens to you, please check your clock and make sure it's set accurately. Either use system NTP or get the time from a reliable source: http://time.org/

**Comment by sylvain-75** [comment]
Hello 
My problem with windows10 2004 was resolved with you advice 
the time of my pc advance by 3 minutes

Thank you very much

**Comment by mistermoutan** [comment]
I can confirm that using system NTP solved the issue for me. All I had to do was enable chrony's daemon (`systemctl enable --now chronyd` )

Thanks a lot, great work

**Comment by laurent22** [comment]
For those still having this issue, please give a try to the latest release: https://github.com/laurent22/joplin/releases/tag/v1.0.245

**Comment by andrewdolman** [comment]
Upgrading to v1.0.245 fixed this on Mac and Windows, but the Android app still has the issue at the moment.

**Comment by tim-hub** [comment]
> Upgrading to v1.0.245 fixed this on Mac and Windows, but the Android app still has the issue at the moment.

I updated to the latest one, but still got problem on android
