### ISSUE TITLE
Systray no longer accessible in Gnome 

### ISSUE THREAD

**Issue by fhaefemeier** [laurent22/joplin#3756]
After update to version 1.0.245 using the update script `Joplin_install_and_update.sh` the system tray is no longer shown. Using TopIcons Plus Gnome extension to top panel. It was working in version 1.0.195 before.

## Environment

Joplin 1.0.245 (prod, linux)
Sync-Version: 2
Profil-Version: 33
Revision: 2aa7eaa (master)

Platform: Linux
OS specifics: Fedora Workstation 32 / Gnome 3.36.5 / TopIcons Plus (Gnome Extension)

## Steps to reproduce

1. Start Joplin 

Expectation: systray icon appear in the list of tray icons in the top panel.

## Logfile

No errors / warnings in log.txt during start of application.

**Comment by fhaefemeier** [comment]
Issue is still open.

Joplin 1.1.4 (prod, linux)
Sync-Version: 2
Profil-Version: 34
Revision: 9610b7e (master)

**Comment by trap000d** [comment]
https://github.com/laurent22/joplin/pull/3716
It's fixed in upstream, I've asked Joplin developers to upgrade Electron ^8.3.2 a month ago...

**Comment by gombosg** [comment]
Apparently still present.
Joplin 1.2.6
Fedora 32
GNOME 3.36.6
Both "Topicons plus" and "Tray icons" shell extensions - neither show the Joplin icon.

**Comment by Wenzel** [comment]
I don't know if this is related to this issue, but for me, the systray icon is showing up, but end up disappearing when I put my laptop to sleep and wake it up again.
When I login to Gnome Shell, the systray icon is gone, and I have to quit Joplin, and start it again to get the icon back.

**Comment by Wenzel** [comment]
Also note that when I start Joplin, the ubuntu appindicators extension is complaining in journalctl:

~~~
 gnome-shell[2846]: JS ERROR: Exception in callback for signal: property-changed: GdkPixbuf.PixbufError: Format d’image non reconnu
                                          _updateImage@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:618:49
                                          _onPropertyChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:554:42
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                          property_set@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:125:14
                                          _endRequestProperties/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:271:33
                                          _endRequestProperties@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusMenu.js:266:19
                                          asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
~~~

But it doesn't prevent the systray icon from showing up.

**Comment by zero77** [comment]
> #3716
> It's fixed in upstream, I've asked Joplin developers to upgrade Electron ^8.3.2 a month ago...

Also, https://github.com/electron/electron/pull/23674

**Comment by fhaefemeier** [comment]
I update to 1.4.19 and seems to work again. The tray was shown after starting. Thanks
