### ISSUE TITLE
UI sometimes broken on IOS 14

### ISSUE THREAD

**Issue by Jenny54321** [laurent22/joplin#3830]
## Environment

Joplin version: 10.1.0
Platform: IOS
OS specifics: 14.0

## Steps to reproduce

0. Update device to IOS 14.
1. Edit any note.
2. Press back to save.
3. See the broken UI.
![1A453FB9-772E-4A7D-BDED-5B9664899093](https://user-images.githubusercontent.com/71888897/94278938-039ffc00-ff7e-11ea-8837-a671c0bdf08f.png)

## Describe what you expected to happen
Work normally like in IOS 13.

**Comment by duxswhatdux** [comment]
Good to see it’s not an isolated issue.
I have this on iPadOS 14 where iPhone seems to be ok for me. 
Happens when you hide the keyboard. Made a short screen recording, attached in the zip file.
[2020-10-09 18.24.28.zip](https://github.com/laurent22/joplin/files/5358152/2020-10-09.18.24.28.zip)

Thx!

**Comment by coughingmouse** [comment]
@Jenny54321 Judging from the screenshot it seems you're also using an iPad running iPadOS 14.0.0 or 14.0.1. Better change title soon.

It seems it's also happening in the Configuration menu. I, personally, found this concerning issue when I was trying to paste Nextcloud WebDAV URL & other credentials. 

To me, it seems it's only happening when I'm using split keyboard. Joplin hides the text portion where the keyboard should be if it were not split. As the keyboard is hidden, the huge chunk of black space covers up the screen.

**Comment by duxswhatdux** [comment]
> @Jenny54321 Judging from the screenshot it seems you're using an iPad running iPadOS 14.0.0 or 14.0.1, not iOS. Someone better change title soon.
> 
> It seems it's also happening in the Configuration menu. I, personally, found this concerning issue when I was trying to paste Nextcloud WebDAV URL & other credentials.
> 
> To me (on iPadOS 14.0.1), it seems it's only happening when I'm using **split keyboard**. Joplin hides the text portion where the keyboard should be if it were not split. As the keyboard is hidden, the huge chunk of black space covers up the screen.
> 
> Joplin is, at current state, utterly unusable for iPad users with split keyboard and I'm surprised not many care.

Here is more info. Fresh 14.0.1 is a problem, where upgrade from 13.x to 14.0.0 then to 14.0.1 was fine also. After a wipe
E and new download of 14.0.1 from apple causes it to blow
https://github.com/laurent22/joplin/issues/3830#issuecomment-706455786

**Comment by duxswhatdux** [comment]
> @Jenny54321 Judging from the screenshot it seems you're using an iPad running iPadOS 14.0.0 or 14.0.1, not iOS. Someone better change title soon.
> 
> It seems it's also happening in the Configuration menu. I, personally, found this concerning issue when I was trying to paste Nextcloud WebDAV URL & other credentials.
> 
> To me (on iPadOS 14.0.1), it seems it's only happening when I'm using **split keyboard**. Joplin hides the text portion where the keyboard should be if it were not split. As the keyboard is hidden, the huge chunk of black space covers up the screen.
> 
> Joplin is, at current state, utterly unusable for iPad users with split keyboard and I'm surprised not many care.

Happens with full keyboard for myself.

**Comment by coughingmouse** [comment]
I'm wildly guessing that the part of code causing this has something to do with how when writing on my iPhone XR, Joplin hides about a line width of space behind my keyboard.

**Comment by duxswhatdux** [comment]
This is still happening, although I just installed Joplin 10.3.1 this morning. Was hoping the next update would be the fix 🙁
![E248DDDD-0A83-4B89-8D14-82AF005FF251](https://user-images.githubusercontent.com/45373146/98385843-b434fd00-200c-11eb-81a7-8e59fe427e5c.jpeg)
![FEF6ED15-FE1F-4978-968F-D6F9D861D975](https://user-images.githubusercontent.com/45373146/98385869-bac37480-200c-11eb-8299-adef6053318b.jpeg)

**Comment by duxswhatdux** [comment]
That’s interesting. 
On my Mac, using the latest version of Joplin (as of Nov 7, 2020), I made an edit with a note that is shared between the Mac and the iPad. 
- Sync the Mac to my cloud share
- Sync my iPad to receive the updated note

First, thought it was just the note updated on the Mac that didn’t Bork out on the iPad, but I created new note on the iPad after the Mac/sync to iPad note edit…
Now the screen issue (video above) no longer happens at all. 🤔

**Comment by coughingmouse** [comment]
'Tis still here and still pretty broken.

**Comment by duxswhatdux** [comment]
Hi there. I recalled making a note on there it seems to be fixed after Apple released the update 14.1. It was all Apples fault by the looks of things. 

Thanks

**Comment by coughingmouse** [comment]
I now am using iPadOS 14.3, Joplin updated to the latest version, and the problem persists.

**Comment by duxswhatdux** [comment]
> I now am using iPadOS 14.3, Joplin updated to the latest version, and the problem persists.

What I done was backed up my data, erased the iPad, reinstalled Joplin. The problem persisted until 14.1 update. Maybe was full wipe is needed?

**Comment by duxswhatdux** [comment]
Fixed by Apples Update 14.1

**Comment by nwabeen** [comment]
This UI bug persists on iPhone devices (14.5). Please fix this issue as soon as possible. it's blocking the core function : users can't even add or edit theirs notes. Actually, the app is  completely unusable on iPhone.

Thank you in advance for your fix.

**Comment by deferredreward** [comment]
I have been experiencing this quite a bit. It has been a real frustration. 

In iPad OS 14.4.2 it is mostly working - the only way I could replicate was if I had Joplin in split screen with a floating keyboard. (Other times it was a near constant problem unless using the full bottom keyboard). I'll update if it breaks when this updates to 14.5. Joplin version 10.7.2

iOS 12 works just fine. :grin:

**Comment by coughingmouse** [comment]
Tried reinstalling on my iPad, but to my avail, the problem persists. Anyone mind changing the title of this very misleading thread already?

**Comment by coughingmouse** [comment]
Sadly, the problem still persists.

**Comment by duxswhatdux** [comment]
Hi. Yes, this returned with IOS 14.6 on the iPad. 

Thanks,
Warren

**Comment by didaktiik** [comment]
Hi,

The bug is present on iPhone 7 (iOS 14.6) and iPad Pro 11" (iPad OS 14.6).
Joplin for iOS is the latest one,  version 12.1.2.

The iPhone was reset to factory setting prior setting it up, before installing apps and, Joplin.

The bug manifests itself during these actions:

- creating a new note/to-do
- editing existing notes/to-dos (adding new stuff, not just "blank" edit)
- 1st Joplin configuration was quite difficult, adding Nextcloud credentials especially was a nightmare, I had to terminate the app numreous times when switching back and forth between Joplin and Bitwarden (adding credentials, sync url)

diik

**Comment by Cor73** [comment]
Hello,

I would also like to add that I'm experiencing this issue. I have iPad OS 14.7 running on iPad Pro 10.5" and the issue is as described by previous posters. 
iPad was factory reset before installing Joplin, so Joplin 12.1.2 is a fresh install, not an upgrade from previous version.

For me, the bug happens when I do the following sequence of actions:

1. Create new note or to dos
2. Add a Title and add some notes
2. Click the back button **==> at this point: the bug manifests**

This appears to be very similar to how it is triggered when other people have posted.

Warm regards,

**Comment by selwyndd21** [comment]
This issue persist on iOS 15.1.1 on Iphone 13.  Anyone knows who can fix this issue?

![IMG_9755](https://user-images.githubusercontent.com/5052144/143880203-64b7f6aa-293a-4a47-a8fc-e4947d38a1a6.PNG)

**Comment by ehijzen** [comment]
In 16.3 ui show just an empty screen after doing a search.

**Comment by coughingmouse** [comment]
This issue doesn’t appear on my setup anymore.
