### ISSUE TITLE
Insert Date using shorcut or menu doesn’t work in WYSIWYG

### ISSUE THREAD

**Issue by paramecie** [laurent22/joplin#4099]
It works in Markdown editor, but when in **Rich Text editor** :
	* the Edit / Insert Date menu item is disabled,
	* whatever the shortcut is, striking the shortcut won't insert the Date.

But note that while it seems to do nothing, in fact it does change the edition date of the note.

BTW, also in Rich Text editor, all edition items in the Edit menu are disabled - I don't know if it's related.

![image](https://user-images.githubusercontent.com/32078594/99421607-db3dd980-28fe-11eb-9e4e-ad29a128e1e4.png)

## Environment

Joplin version: 1.3.18
Platform: Windows
OS specifics: 7, 64bits

## Steps to reproduce

1. create a new note,
2. shift (if not already) to WYSIWYG (Rich Text editor),
3. strike the shortcut to insert a date : it won't insert a date, but will change the edition date.

It's 100% reproducible, sorry not to add log, too few time :-(
Hoping it'll be OK.

Posted in forum also:
https://discourse.joplinapp.org/t/insert-date-using-shorcut-or-menu-doesnt-work/12373

Thank you!

**Comment by laurent22** [comment]
First bug should be fixed in next release, and second one for now we don't support.

**Comment by romanovsky** [comment]
I can still reproduce the problem in the latest release of `Joplin 2.8.8 (prod, darwin)`.
I.e. Markdown editor has functional "insert date shortcut" with `Cmd-D`, Rich Text editor has this menu item grayed out and `Cmd-D` does nothing.
