### ISSUE TITLE
Exported notes with long titles have truncated filenames

### ISSUE THREAD

**Issue by panicsteve** [laurent22/joplin#4519]
When exporting a note with a long title, the filename seems to be truncated to 60 (?) characters.

For example "This is a note with a very long title that will get truncated" becomes "This is a note with a very long title that will ge.md".

On filesystems that support long filenames, it would be nice if the whole title could be used for the filename.

## Environment

Joplin version: 1.7.10 (prod, darwin)
Platform: macOS
OS specifics: 10.15.7 (19H512)

## Steps to reproduce

1. Create a note with a long title, such as "This is a note with a very long title that will get truncated"
2. Export the note to a markdown file
3. Observe the truncated filename

## Describe what you expected to happen

I hoped the exported file would be named "This is a note with a very long title that will get truncated.md"

## Logfile

Will provide if needed.

**Comment by panicsteve** [comment]
I took a look at the changelog just now but don't see it mentioned as being fixed.

**Comment by Pavan-Bellam** [comment]
hi, I would like to work on this issue. Thanks!

**Comment by Pavan-Bellam** [comment]
@laurent22, as per the code maximum length of a file is 50 characters. This is the root of the problem, do you suggest me to increase the maximum length of the filename? 
![2021-04-02](https://user-images.githubusercontent.com/60264606/113470112-990dd280-9470-11eb-86fc-3ec44d9e2b2e.png)

**Comment by JackGruber** [comment]
**Please note:**
In editions of Windows before Windows 10 version 1607, the maximum length for a path is MAX_PATH, which is defined as 260 characters, this includes the filename and all folders! 

https://docs.microsoft.com/de-de/windows/win32/fileio/maximum-file-path-limitation

**Comment by Pavan-Bellam** [comment]
But it is working fine when I am exporting in other formats.
1. I identified that Breakpoint 1 - line number 97 in /home/bellam/Documents/joplin-dev/packages/lib/services/interop/InteropService_Exporter_Md.js 
is causing the problem
Juggling out here, While debugging the code from this break point again its going in to some other sql queries.
2. I tried statically changing the file name in the code at Breakpoint 1, but still while debugging its taking the title given for the Note.
3. I also tried changing the maxlength in /home/bellam/Documents/joplin-dev/packages/lib/path-utils.js, But maxLength is not changing while running the code.
![2021-04-07 (2)](https://user-images.githubusercontent.com/60264606/113838611-8f57d800-97ac-11eb-81cf-bc3701d8155b.png)
.
Any help is appreciated.

**Comment by Pavan-Bellam** [comment]
I have fixed the bug, the problem was in path-utils.js. I will make a PR  with updated code.

**Comment by pmottishaw** [comment]
I have just attempted to export notes as Markdown (with and without Front Matter) and this bug is still there.  The markdown filenames are truncated at 50 characters. Note that when you include Front Matter the full title of the note appears in the Front Matter). I am using  Joplin 2.6.10 (prod, win32) on Windows 10 Home, Version	21H1,
OS build	19043.1466. 

Any idea when it might be fixed?
