### ISSUE TITLE
[Feature Request] Settings to display reminders for next 'x' days

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#477]
### Operating system

- Linux

### Application

- Desktop

### Description

I would like to not see notification of all the reminders I've setup for a year (Yes I did, for example to manage my hosting billing :) 

So It could be helpful to have a settings allowing to set the numbers of days before displaying the notifications.

For example : "Would you like to display reminders for the next 'x' days: "

**Comment by foxmask** [comment]
bug still here on Linux

**Comment by laurent22** [comment]
@foxmask, I don't understand this issue - do you mean that you're getting notifications too early? I think that's fixed now, but maybe you mean something else.

**Comment by foxmask** [comment]
It was almost that, but forget the initial request. 

For what you said, tt's not fixed:

* I've set a note as todo with a reminder for the 8th of november 10h45 that raises a popup right now
* I've set a note as todo with a reminder for the 1rst of decembre 19h that does not raise a popup right

**Comment by laurent22** [comment]
That should be fixed in the next release actually, it's true it hasn't been released yet.
