### ISSUE TITLE
iOS - UI Glitch - White Screen Blocks Text

### ISSUE THREAD

**Issue by jdpesq** [laurent22/joplin#4980]
![Joplin - White Screen Issue](https://user-images.githubusercontent.com/84331148/118502957-2ee77f00-b6f8-11eb-8938-fb3c0d4d94bc.jpg)

## Environment

Joplin version: 10.8.1, Database v35
Platform: iOS
OS specifics: 14.5.1 on an iPhone 11

## Steps to reproduce

1.  Open an existing note.
2.  Edit note.
3.  Save edits.
4. White screen with red button for new note/new to-do will fill the whole screen.  It does not allow further interaction with the app.
5.  Only way to resume normal operation and see notes is to force quit the app and restart.

See video example:  https://drive.google.com/file/d/16Tpc_iKZ3EG3ZASLp1pFMSWWq2kiXdvi/view?usp=sharing 

## Describe what you expected to happen

Expected behavior after saving edits is to return to the note with changes shown, and to be able to navigate to the list of notes in that folder.

## Logfile

Behavior does not show in the log file because it is a UI error.

**Comment by dz2106** [comment]
I have had this same issue as well

**Comment by jdpesq** [comment]
No, I don’t believe so.  I tend not to embed images in my notes, or if I do it is usually by linking to public URLs of images.  The only local images I have are from using the Joplin web clipper.

This behavior happens with all my notes, not just the one I used as an example.  Also, I have an iPad Air 2 that I use Joplin on, and have not experienced the same UI issues.  All notes that are on the iPhone are synced to the iPad (and to two PCs) via Dropbox with encryption enabled.  The other devices are all working correctly.

The other difference I recently noticed is that on the iPhone html links are not showing up as clickable, but just plain text.  The exact same note with the same formatting is showing html links as clickable on the iPad and PCs.

**Comment by jdpesq** [comment]
Follow up on my previous comment.  URLs with a name work, but addresses do not. For example:

[Name of Website](https://example.com)  works as expected with “Name of Website” as a clickable link, but https://example.com by itself will not show up as a clickable URL.

Not sure if this is related to my reported bug, or if this is user error on my part.  Note, however, that both of the above examples are clickable links on my iPad and PCs.

**Comment by roman-r-m** [comment]
> Follow up on my previous comment. URLs with a name work, but addresses do not. For example:
> 
> [Name of Website](https://example.com) works as expected with “Name of Website” as a clickable link, but https://example.com by itself will not show up as a clickable URL.
> 
> Not sure if this is related to my reported bug, or if this is user error on my part. Note, however, that both of the above examples are clickable links on my iPad and PCs.

Any chance you have Linkify switched off on your iPhone?

**Comment by dz2106** [comment]
I have an iPhone XS Max on 14.5.1.  I noticed the bug when trying to replicate [this](https://github.com/laurent22/joplin/issues/4503) issue. When I tried to attach the vertical image after I stopped editing it would break. I attached a video of what happens. https://imgur.com/SnU2XTa

**Comment by jdpesq** [comment]
Anyone else experiencing this bug? It’s really caused me to be unable to use Joplin on iOS, and I hope getting more data from others might help to solve the issue.

**Comment by anielakob** [comment]
> Anyone else experiencing this bug? It’s really caused me to be unable to use Joplin on iOS, and I hope getting more data from others might help to solve the issue. 

I am experiencing the exact same bug on iPhone SE iOS 14.5 

![image](https://user-images.githubusercontent.com/26513230/120216378-3bf78880-c237-11eb-80ca-d932db96b9b5.png)

**Comment by anielakob** [comment]
> Anyone else experiencing this bug? It’s really caused me to be unable to use Joplin on iOS, and I hope getting more data from others might help to solve the issue. 

I juat had a thought and tested it out. 

Turns out that going to _Accessibility>Motion>Reduce Motion_ and unchecking it made the app work exactly as it should for me. 

So definitely check if you have Reduce Motion turned on.

**Comment by jdpesq** [comment]
>Turns out that navigating to: Accessibility>Motion>Reduce Motion and unchecking it made the app work exactly as it should for me.

>So definitely check if you have Reduce Motion turned on.

>EDIT: I went back and tried only checking Reduce Motion and unchecking "Prefer Cross-Fade Transitions" and it still works. So, at least for me, that setting was to blame.

**That worked for me too - Thanks so much!**  

I can confirm that it seems like deselecting "Prefer Cross-Face Transitions" is the fix for this issue.  I was able to see that leaving Reduce Motion checked and unchecking Prefer Cross-Face Transitions causes Joplin to work as expected, and checking Prefer Cross-Face Transitions causes the UI glitch.  Unchecking Prefer Cross-Face Transitions fixes the issue, even without restarting Joplin.

**Comment by laurent22** [comment]
Thanks for looking into it. Are there settings a new iOS feature? As it's strange it's only starting to happen now.

**Comment by jdpesq** [comment]
> Thanks for looking into it. Are there settings a new iOS feature? As it's strange it's only starting to happen now.

Looks like this was added in iOS 13: [Set Cross Fade Animations in iOS 13 for Smoother Lateral Transitions | Gadgethacks](https://ios.gadgethacks.com/how-to/set-cross-fade-animations-ios-13-for-smoother-lateral-transitions-menus-apps-0200100/)

Not sure why it would only show up now...

**Comment by anielakob** [comment]
> > Thanks for looking into it. Are there settings a new iOS feature? As it's strange it's only starting to happen now.
> 
> 
> 
> Looks like this was added in iOS 13: [Set Cross Fade Animations in iOS 13 for Smoother Lateral Transitions | Gadgethacks](https://ios.gadgethacks.com/how-to/set-cross-fade-animations-ios-13-for-smoother-lateral-transitions-menus-apps-0200100/)
> 
> 
> 
> Not sure why it would only show up now...

The issue has also been posted [here](https://www.reddit.com/r/iOSBeta/comments/hwiqmy/ios_14_beta_3_reduce_motion_and_prefer_crossfade/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) but for iMessage apparently.

iOS 14 introduced a slew of UI updates, so it makes sense that transitions would be handled differently. 

I hope they fix it soon, I didn't turn it on for fun.

**Comment by laurent22** [comment]
Ok that's good to know. If even iMessage is broken, then they should hopefully fix the OS.

**Comment by amandamcg** [comment]
Adding this in case someone else is searching Github for a fix: 
- This broke for me when I upgraded to iOS 14.6. 
- It happened when editing a note and going back to the list, when saving a note from the app shortcut in Safari (I'd never used this feature before that), and when searching 
- The name of the note didn't seem to affect the behavior and was happening on old notes and new ones
- Unchecking `Prefer Cross-Fade Transitions` fixed it for me. (Thank you @anielakob!!)

**Comment by nathanojb** [comment]
Fwiw, I have a contrary experience.
iPad Air 4th gen, 14.6

I started with `Reduce Motion` off - the default. I tried all combinations of `Prefer Cross-Fade Transitions` and `Reduce Motion`. Rebooted, restarted the app, did all of the above in various combinations, but the issue persists.

**Comment by kezzbracey** [comment]
Same issue on iPad Pro 2021. iPad OS 14.6

`Reduce Motion` and `Prefer Cross-Fade Transitions` didn't have an effect.

**Comment by laurent22** [comment]
I found the React Native bug about this: https://github.com/facebook/react-native/issues/29974 There's patch apparently so I guess it should be fixed in a future version. I'll upgrade as soon as it is.

**Comment by jdpesq** [comment]
Thanks so much! Looking forward to the fix in the future.

**Comment by babyrusa** [comment]
@nathanojb @kezzbracey  a few users of mine have this issue and one of them doesn't have  Prefer Cross-Fade Transitions enabled but still faced this issue. I want to check to see if any of u figured out what could have caused this?

**Comment by WolfgangDpunkt** [comment]
`Reduce Motion` and `Prefer Cross-Fade Transitions` didn't have an effect. 
Same problem here on iPadOS 14.7.1
(But on iPhone SE Classic iOS 14.7.1 everything ist fine)
<img border=1 Style=“border:1“  width="820" alt="Bildschirmfoto 2021-09-04 um 19 43 42" src="https://user-images.githubusercontent.com/35533844/132104039-8617b8bc-4ba3-4fcb-9c26-cefde557b305.png">

**Comment by nathanojb** [comment]
I can’t believe it was that simple but the solution from @WolfgangDpunkt  works for me too. As in my previous comment I’m using iPad Air 4th gen, and I can confirm that this issue only happens with the “floating” phone sized keyboard but not with the “full sized” version.

**Comment by cmayoros** [comment]
Is this being looked at? Yes, switching to the full sized docked keyboard works, but is much more difficult to type at a decent pace with as it lacks swipe features. Joplin on iPad is basically unusable for me with this issue.

**Comment by WolfGangsta** [comment]
I also had this issue, and @anielakob's solution worked for me.

Also, looks like #6164 is a derivative of this issue.

iPhone 6s, iOS 15.3.1
Joplin 12.7.1

**Comment by xto3** [comment]
Thanks for highlighting this workaround.

Unfortunately, it didn't work for me:
iPad Pro 11
iPadOS 15.4.1
Joplin 12.7.1

**Comment by vkoechli** [comment]
I'm having this problem, too, on both iPhone SE2 and iPad 6, both with iOS 15.4.1.

I have experienced it not only when editing a note (new or modified), but also on entering configuration details. The problem seems to occur as soon as the onscreen keyboard is dismissed.

Turning off the 'Reduce motion' setting seems to resolve it, at least in my case, but this is not something everybody will want to do.

**Comment by jflth** [comment]
Same to me !😖
iPad  mini 4  iOS 15.6
iPhone SE 2nd  iOS 15.6
It' s shame: this bug ist older than one year. Joplin on iOS is not usable. I was on the way to migrate from apple Notes to Joplin, which causes me a lot of time and work.

**Comment by DShirk** [comment]
I have this same problem every time I edit. Sometimes when I click the line at top the screen opens back up and lets me access it. But generally have to quit Joplin and restart. 15.6.1 iPad Pro 5th Gen with docked keyboard. This has been a problem for more than a year now. Occasionally get it on my iPhone 13 Pro Max as well. Makes editing in Joplin unusable. Tried all the “fixes” above and full shutdown restarts but still not solving for me.

**Comment by cmayoros** [comment]
Honestly, it's sad, but I don't think the developers care about this one. I solved the problem for myself. I switched to another notes app. Don't have this issue anymore, I can write on my phone, iPad or laptop without issues anymore, everything syncs perfectly between them.

**Comment by janpersiel** [comment]
Same issue on iPhone 13 Pro with various iOS current versions. iPhone 12 Mini and iPhone R do not have it. Can be reproduced with fresh installs right away.

**Comment by laurent22** [comment]
Closing as there haven't been any recent report so hopefully the bug was fixed by React Native or iOS
