### ISSUE TITLE
When copying from viewer, theme colours are copied

### ISSUE THREAD

**Issue by axelsimon** [laurent22/joplin#5113]
## Environment
Joplin 1.8.5 (prod, linux)
Sync Version: 2
Profile Version: 35
Keychain Supported: No

Platform: Linux
OS specifics: Flatpak, on Fedora

## Steps to reproduce

1. Select a theme with a dark background in the Appearance options (Nord, in my case)
2. Copy text from the text viewer (right pane, in two pane mode)
3. Paste text in word processor, some/all of the text's colours are pasted:
  3.1. in LibreOffice writer, the foreground colour is copied but not the background, leading to a nearly unreadable light grey on white text
  3.2. in Google Docs, both the foreground and background colour are copied, leading to a weird light grey text on on dark blue on a white background

## Describe what you expected to happen
The text and its formatting, as well as pictures, should be copied, but my local styling of the text due to my choice of theme should not be exported: the theme is part of my personal rendering choice, it's not part of the text itself, unlike bold or italic markup, for instance, or images.

### Screenshots
Joplin panes:
![Screenshot from 2021-06-23 12-08-53](https://user-images.githubusercontent.com/1172256/123086881-d81e4500-d41b-11eb-9091-a10f2d030d6e.png)

LibreOffice Writer:
![Screenshot from 2021-06-23 12-10-10](https://user-images.githubusercontent.com/1172256/123087047-056af300-d41c-11eb-950a-f11c119a7a2d.png)

Google Docs:
![Screenshot from 2021-06-23 12-08-17](https://user-images.githubusercontent.com/1172256/123086884-d94f7200-d41b-11eb-8a12-021577e033a6.png)

**Comment by axelsimon** [comment]
I see no reason to assume this issue has been fixed.

**Comment by axelsimon** [comment]
Just tested and this is still a problem in `2.1.9 (prod, linux)`.

**Comment by NathanAuckett** [comment]
Just chiming in on this as its been a while.
This is still a problem.

Copying nicely formatted text from the markdown viewer to another app to share a tiny snippet with someone is basically not doable if you have anything but the white theme selected.
In the white theme things remain readable because the text is black and the background is white already.

My workaround for the problem was to use a custom style-sheet for just the markdown viewer but its not ideal.
If possible, copying from here should ignore the base text color and highlight/background.

**Comment by axelsimon** [comment]
Still an issue.

**Comment by axelsimon** [comment]
Still an issue.

@laurent22 could the bot be set up for a longer period? Every month seems a bit aggressive.

**Comment by axelsimon** [comment]
@laurent22 could this be re-opened?

**Comment by laurent22** [comment]
I think you need to paste without formatting Cmd+Shift+V. If you paste with formatting the background's included and there's no way for us to know when it should or shouldn't be excluded.

**Comment by axelsimon** [comment]
But isn't that the problem, that the theme background is _formatting_, and not just display?

There's a difference between me liking to show my text as red on a blue background or whatever, and the text itself being formatted as red on blue. It should still be normal, black on white text, even if i chose to display it according to a theme or another.
Ie: what should be presentation is becoming data, and that data is being passed on.

**Comment by laurent22** [comment]
The thing is that we don't know what's presentation and what's data, and that will vary depending on who you ask. It seems you want the app to convert the colours to the closest gray colour, or black and white. That's you, but I'm sure others will want the colours or background to be copied too. There's no easy solutions to this, and that's why we have paste without formatting.

**Comment by axelsimon** [comment]
I think i see your point, but for instance, when you change the theme on a website to a dark theme, even if the text is shown on light grey on black, when copy-pasted into another document, it shouldn't appear like that. Can we agree on that?

> The thing is that we don't know what's presentation and what's data, and that will vary depending on who you ask.

Don't we? I mean, on the left, in the typing area, we have the data, and on the right, in the viewer, we have the presentation of that data (rendering of markdown).

I'm not sure anyone who sets up a _theme_ expects the theme colours to be exported. A theme is not formatting. And in any case, markdown doesn't have a way to describe font and background colour for text, as far as i know, so i really think rendered markdown text should not be formatted and that formatting should not be exported.

**Comment by NathanAuckett** [comment]
> I think you need to paste without formatting Cmd+Shift+V. If you paste with formatting the background's included and there's no way for us to know when it should or shouldn't be excluded.

Pasting without formatting means you lose all formatting, even the formatting you actually want like headings, bold text, ect.

I struggle to envision a scenario where the background should be included as just about anywhere you could be pasting would have its own background color already. If the existing background color is not the exact same as your theme, the text is going to look horrible when pasted.

> The thing is that we don't know what's presentation and what's data, and that will vary depending on who you ask. It seems you want the app to convert the colours to the closest gray colour, or black and white. That's you, but I'm sure others will want the colours or background to be copied too. There's no easy solutions to this, and that's why we have paste without formatting.

I think the simplest way to know if someone wants the theme colors copied as well or not is to have a setting for it. A simple check box would do the trick here.
E.g. Copy theme/background colors with text: Yes/No

A more complex setup might allow the user to choose to keep or discard background and text colors separately. Point is, if you have no easy way of knowing what the user wants, give them the option to tell you.

If possible, rather than converting the color, I'd say the more ideal solution would be to remove the color from the copied data completely. So you copy black text including all formatting except the colors, depending on the user settings of course.

<br>
Any effort into implementing something like this would be greatly appreciated by myself and others who are affected by this issue.
We're relying on those who have the time and skill to make it happen though so at the end of the day all we can do is ask and give thanks for any effort/time put in.
Cheers.
