### ISSUE TITLE
GoTo is not working at first try

### ISSUE THREAD

**Issue by davidpoza** [laurent22/joplin#5184]
GoTo command palette is not working as expected.

## Environment

Joplin version: 2.2.1
Platform: linux
OS specifics: popOS 20.04

## Steps to reproduce

1. press CTRL+P to open command palette
2. search any note
3. press enter
4. it does anything, not jumping to selected note
5. repeat 1-4 steps again, and it works

## Describe what you expected to happen

Previously it was working as expected (on 2.0.9)

**Comment by laurent22** [comment]
Is there any error in the console? https://joplinapp.org/debugging

**Comment by davidpoza** [comment]
```
/tmp/.mount_JoplinZ6…GotoAnything.js:307 Uncaught (in promise) TypeError: Cannot read property 'makeItemIndexVisible' of null
    at Dialog.<anonymous> (/tmp/.mount_JoplinZ6…GotoAnything.js:307)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinZ6…s/GotoAnything.js:5)
```

**Comment by davidpoza** [comment]
Just to help out: I've tested 2.1.9 and this bug isn't present.

**Comment by laurent22** [comment]
I'm not entirely sure what the issue is here, it might depend on your notes or some other factor. I've implemented a fix that may improve the situation, but if it happens again please let me know, and provide again the console statements.

**Comment by davidpoza** [comment]
Sorry, I need to open issue again.
I'm trying 2.2.6 prerelease but bug still exists.

I've made a screen capture:
![Peek 2021-08-11 11-34](https://user-images.githubusercontent.com/5300774/129006489-ba1b295b-9b29-4914-8bfc-83a5c1fd68d2.gif)

**Comment by pravsripad** [comment]
I have the same issue (goto Cmd+P does not work first time). I do not see any error messages on the console. 

```
Joplin for Desktop
Copyright © 2016-2021 Laurent Cozic
Joplin 2.2.7 (prod, darwin)
Client ID: 20e2a2bc858f4dce89aeffe2c7889ab0
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes
Revision: 6d1a2e2
```

**Comment by gruen-f** [comment]
Same here. Issue is not addressed.

**Comment by laurent22** [comment]
I can't replicate it. Could someone try with all plugins disabled?

**Comment by pravsripad** [comment]
I tried with all plugins disabled and I still face this issue. Sometimes see the below error on the console,
```
DevTools failed to load SourceMap: Could not load content for file:///private/var/folders/gw/r0dkp90n2mvcnkfbz8jqrnj80000gq/T/AppTranslocation/1F998594-1166-4ADC-9CCC-B845E87A798D/d/Joplin.app/Contents/Resources/app.asar/gui/note-viewer/pluginAssets/mermaid/mermaid.min.js.map: 
```

```
Joplin 2.3.3 (prod, darwin)
Client ID: 20e2a2bc858f4dce89aeffe2c7889ab0
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes
Revision: f07636e
```

On a different profile with fewer number of notes, I cannot reproduce the issue even with the same plugins enabled.

**Comment by gruen-f** [comment]
I also have no plugins installed. Would a screencast help?

**Comment by 3ter** [comment]
I replicated the issue on an empty collection. I then duplicated and imported notebooks to generate a larger number of notes and then the goto would only work after the second try after a time:
![image](https://user-images.githubusercontent.com/11499929/129770684-401a5264-f103-4ea7-8f6a-aaafe3819407.png)

**Comment by banan314** [comment]
It's resolved for me in version 2.4.1, Linux

**Comment by pravsripad** [comment]
Works for me with 2.4.1 macOS as well. Thanks a lot for fixing this quickly.
