### ISSUE TITLE
After Joplin update Layout distroyed by using TOC

### ISSUE THREAD

**Issue by kai452** [laurent22/joplin#5288]
Hi,

using outline-plugin or TOC from the Joplin-Plugin-Tutorial:
Click on an TOC list element will move the layout upwards (all panels right of note-list-sidebar), so the head and editor-menü are dissapeared.
Repair only through Joplin restart.
 
## Environment

Joplin version: 2.2.4
Platform: Windows 7
OS specifics: Home

## Steps to reproduce

1. using outline-plugin or TOC from the Joplin-Plugin-Tutorial
2. Click list element will move the layout upwards, so head and menü rows are dissapeared
3. Repair through Joplin restart

## Describe what you expected to happen
Clicking list element should scroll note panel to that heading without scrolling other panels

## Logfile
![image](https://user-images.githubusercontent.com/53316526/128971264-25c2a1e8-63bd-4292-8056-97a0b364dd2a.png)
[-1628657327897.log](https://github.com/laurent22/joplin/files/6965945/-1628657327897.log)

**Comment by laurent22** [comment]
This was due to a recent change to the plugin API, which I've now reverted. The next 2.2 release should fix the issue.

**Comment by laurent22** [comment]
Please give a try to the latest release and let me know if it works: https://github.com/laurent22/joplin/releases

**Comment by nablabits** [comment]
Cool, on 2.2.7 plugins came back (they disappeared from the app for 2.2.6) but https://github.com/benji300/joplin-favorites/issues/11 is still failing to load could it be due to the update as well? 🤔

**Comment by kai452** [comment]
Hi Laurent,
well done, very fast !
Vielen, vielen Dank.

**Comment by CalebJohn** [comment]
> Cool, on 2.2.7 plugins came back (they disappeared from the app for 2.2.6) but [benji300/joplin-favorites#11](https://github.com/benji300/joplin-favorites/issues/11) is still failing to load could it be due to the update as well? 🤔

That plugin needs to be updated to work with the current version of Joplin. I know the author has been updating their other plugins, so it's just a matter of time.

**Comment by nablabits** [comment]
> > Cool, on 2.2.7 plugins came back (they disappeared from the app for 2.2.6) but [benji300/joplin-favorites#11](https://github.com/benji300/joplin-favorites/issues/11) is still failing to load could it be due to the update as well? thinking
> 
> That plugin needs to be updated to work with the current version of Joplin. I know the author has been updating their other plugins, so it's just a matter of time.

Ahh, yep, thanks for the reply!
