### ISSUE TITLE
Unable to import all Evernote notes. 

### ISSUE THREAD

**Issue by leveled** [laurent22/joplin#55]
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

<img width="520" alt="evernote-export" src="https://user-images.githubusercontent.com/6319960/33508030-a9b37866-d6bd-11e7-8490-3794ef2725bc.png">
<img width="398" alt="evernote-export-2" src="https://user-images.githubusercontent.com/6319960/33508136-2f6d8230-d6be-11e7-8fe0-2e26f08ac354.png">
<img width="1028" alt="joplin-import" src="https://user-images.githubusercontent.com/6319960/33508139-32697110-d6be-11e7-96f5-b0ff5c0f334a.png">

*If there is an error, please copy and paste the full error message*

---

I'm running into an issue while trying to import my Evernote notebook. For whatever reason Joplin seems to be capping out at importing 412 notes and then stopping.

**Comment by RupGautam** [comment]
Hi, you can run the below command to allow application to open the dev-tool.
And then you can re-run your imports
`echo "--open-dev-tools" > ~/.config/joplin-desktop/flags.txt`

And post the logs here.

**Comment by leveled** [comment]
Is there a way to export logs from the console? I can't seem to right click -> export in the app. In any case once the import process reached 412 notes the warnings in the screenshot below started appearing. 

![image](https://user-images.githubusercontent.com/6319960/33508972-67b1f004-d6c3-11e7-9517-74ea17f66bea.png)

**Comment by laurent22** [comment]
Thanks, I see your file has some tags that aren't currently supported by Joplin, I will add support for them as soon as possible. Yes you can actually export the console content by right-clicking it and selecting "Save as". Could you then please post the content of this log here?

**Comment by leveled** [comment]
Log 1: https://pastebin.com/besBVPh7
Log 2: https://pastebin.com/Sk8kPL0w

**Comment by RupGautam** [comment]
Yeap, tags unsupported or you don't have tag for some of the attached files.
Simple hack(might not work) but you might want to re-tag them and try again. 

This snippet will give you an idea. 
All attached resources needs `an "objID" tag`
https://github.com/laurent22/joplin/blob/4dce9e9e478f66f360cbc28f31a00a00a6d9024b/ReactNativeClient/lib/import-enex-md-gen.js#L367

**Comment by laurent22** [comment]
Yes the missing tags are easy to fix but the hash with no associated resource is a bit stranger. It's possible that the note simply references a resource that has been deleted, or maybe the XML is in a weird layout I don't know about.

Actually @leveled, is there any chance you could search for this ID "8588acc02b2142971de08b7f282c9933" in the ENEX file and copy and paste the surrounding code? In particular any en-media tag (if any) and any resource tag (if any)?

**Comment by laurent22** [comment]
Hi @leveled, I've created a new release which should fix the sup and blockquote issue although it's still strange that the import stop as it should have gone past the warnings. If you can give it another try  and let me know if it works that would be great. The app is at https://github.com/laurent22/joplin/releases/download/v0.10.33/Joplin-0.10.33.dmg

**Comment by leveled** [comment]
Hey @laurent22, I'm still having issues importing the full set of notes. The sup/blockquote issues are not showing up in the console but the hash issue still pops up. 

Log: https://pastebin.com/KQgi8A2u
ENEX Code:

`<p></p><div style="display:inline-block;outline:0px;"><a href="https://forum.bugcrowd.com/uploads/default/original/1X/3e339e14200e37d81dd78de69b97909a140f8a61.png" title="injectx
3.png" style="background:transparent;color:rgb(0, 98, 147);text-decoration:none;cursor:pointer;position:relative;display:inline-block;outline:0px;word-wrap:break-word;"><en-media
 type="image/png" hash="8588acc02b2142971de08b7f282c9933" width="690" height="464" style="border:0px;vertical-align:middle;outline:0px;max-width:690px;max-height:500px;"></en-med
ia><div style="color:rgb(255, 255, 255);font-weight:bold;outline:0px;position:absolute;bottom:0px;width:100%;background:rgb(34, 34, 34);opacity:0;transition:opacity 0.2s;">
<span style="outline:0px;float:left;margin:5px;max-width:100%;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;"><span style="white-space:nowrap;font-family:FontAwesome;
margin-right:5px;"><U+F03E></span>injectx3.png</span><span style="outline:0px;float:left;margin:6px;padding-right:20px;color:rgb(145, 145, 145);font-size:1em;">1043x702 41.4 KB</
span><span style="outline:0px;float:left;position:absolute;bottom:4px;right:7px;"><span style="font-family:FontAwesome;"><U+F065></span></span>
</div></a></div><p></p>`

**Comment by RupGautam** [comment]
Yes, those enex log shows that there are no `object id` for attached files. 
Did you try re-tagging them on Evernote? You can try exporting it after re-tag and run the import again?

**Comment by leveled** [comment]
I deleted the note in question and tried reimporting it. This time there were no warnings/error thrown in the console but it still stopped importing (at 411 notes).

**Comment by martinpengellyphillips** [comment]
For reference, I'm also having this issue on Windows 10 Joplin version 0.10.35. It stops at 20 notes out of 5231 for me. Enex file is 3.24 GB in size.

Console log attached - seems to be 'img' tag unsupported along with a bunch of the "Hash with no associated resource".

[joplin_evernote_import_error.log](https://github.com/laurent22/joplin/files/1524324/joplin_evernote_import_error.log)

**Comment by laurent22** [comment]
The img tag can be fixed and maybe the hash tag too (unless it's really referencing a non-existing resource) but It's really weird that the import simply gets stuck instead of throwing an error.

Would any of you by any chance has an enex file or even just a note that can be shared and that shows this issue? In my tests initially I've imported up to 2000 notes but didn't hit this problem.

**Comment by martinpengellyphillips** [comment]
I selected a subset (all hacker news articles) which can be downloaded from https://www.dropbox.com/s/hvofvwx7xd89cuj/joplin_test.enex?dl=0

It stops at 10 out of 318 having created 0. Different error though so might be a different issue.

```
C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\lib\import-enex-md-gen.js:302 Uncaught Error: Found a <tr> tag outside of a table
    at SAXStream.<anonymous> (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\lib\import-enex-md-gen.js:302:40)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:191:7)
    at SAXParser.me._parser.(anonymous function) [as onopentag] (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:258:17)
    at emit (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:629:5)
    at openTag (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:825:5)
    at SAXParser.write (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:1278:15)
    at SAXStream.write (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:239:18)
    at StringStream.ondata (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:612:20)
```

**Comment by laurent22** [comment]
Great, thanks for sharing the sample file. I see it might be related to parsing tables, so looks like I either need to fix the logic or make the parser more tolerant to invalid html.

**Comment by martinpengellyphillips** [comment]
>  make the parser more tolerant to invalid html.

This sounds like it might be needed as I can see another parse error in another batch:

```
Uncaught (in promise) Error: Non-whitespace before first tag.
Line: 0
Column: 2
Char: h
    at error (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:651)
    at strictFail (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:677)
    at beginWhiteSpace (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:951)
    at SAXParser.write (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:1010)
    at SAXStream.write (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\sax\lib\sax.js:239)
    at StringStream.ondata (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\readable-stream\lib\_…:612)
    at emitOne (events.js:96)
    at StringStream.emit (events.js:191)
    at addChunk (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\readable-stream\lib\_…:284)
    at readableAddChunk (C:\Users\martin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\readable-stream\lib\_…:271)
```

Thanks!

**Comment by laurent22** [comment]
Hi, a new version is available now with improved Enex support. In particular:

- Better handling of notes containing entire web pages (such as when imported via Web Clipper)
- Support for `<img>` tags
- Support for various other tags
- Improved importing web pages that contain tables within tables. In which case the outer tables (which are usually the website layout) are rendered as regular text block and only the inner tables are actually rendered as tables.
- Fixed many other minor warnings and errors

I think most errors should be gone now and the resulting Markdown, when rendered to HTML, should be much better. Please give it a try and let me know if you're still having any issue importing notes:

https://github.com/laurent22/joplin/releases/tag/v0.10.37

**Comment by martinpengellyphillips** [comment]
```
New notebook "evernote_2017_12_02" will be created and file "evernote_2017_12_02.enex" will be imported into it
Found: 5231. Created: 5180. Resources: 14512. Tagged: 1084.
The notes have been imported: Found: 5231. Created: 5180. Resources: 14512. Tagged: 1084.
```

Worked! Thank you :)

**Comment by leveled** [comment]
Hi @laurent22,

The fix worked for me as well. I noticed whilst importing my Evernote notes there were still a lot of tag and type errors although they did not affect the actual import process itself. Would it be useful information for you to get some of this debug information?

**Comment by laurent22** [comment]
Hi @leveled, good to know it's getting better. Yes please if you could post the warnings and other errors that would be useful.

**Comment by leveled** [comment]
The first section of the log is debug information from when I was deleting my older notebook.

Import Log: https://pastebin.com/8dcuX7BF

**Comment by laurent22** [comment]
Thanks @leveled, the next version will handle these tags that were missing (it won't make a big difference except for "kbd" which will be rendered as code).

For the tr/td in the wrong place, this is probably fine and due to invalid HTML. The text content is still imported even when this warning shows up.
