### ISSUE TITLE
Joplin appears to silently stop saving note history when it doesn't like some note contents

### ISSUE THREAD

**Issue by c-mart** [laurent22/joplin#5531]
I have Joplin configured to keep my note history for 9999 days on desktop, and 730 days on mobile -- the maximum that I appear to be able to set on both platforms. Basically, I want to keep all of my note history forever.

I never actually had to _use_ note history until a few minutes ago. I cut a block of text from one note (intending to paste it in another), but accidentally over-wrote the clipboard instead of pasting. Went back to the original note, text was gone, nothing in the undo (`Ctrl+Z`) buffer.

Note History to the rescue, right?? Looked up [how to use it](https://joplinapp.org/note_history/). Unfortunately, all of my notes say "This note has no history".

![image](https://user-images.githubusercontent.com/13605043/135929783-1168259c-784f-42af-8475-3265bb2f8985.png)

![image](https://user-images.githubusercontent.com/13605043/135929796-611e76cc-e96e-41b9-a544-eb2117ff9fec.png)

It doesn't seem to matter how old the note is, or how many times I've edited it. This particular note is ~3 months old and I've edited it probably a hundred times. Still, the app shows no history.

I tried upgrading from Joplin from 2.3.5 to 2.4.9, this didn't make a difference. Tried toggling "safe mode". Still no luck.

How might I get note history working? Thank you!

## Environment

Joplin version: originally seen on 2.3.5, persists on 2.4.9
Platform: Linux
OS specifics: Debian 10

## Steps to reproduce

1. With note history enabled, look at a note that you've edited many times.
2. See text "This note has no history".
3. Be sad.

## Describe what you expected to happen

I was hoping to see the previous versions of a note with the ability to restore.

## Logfile

I do notice this in the console log:

```
/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 15:02:42: RevisionService: RevisionService::collectRevisions: Could not create revision for note: 7c17452ba0a846e283ed0c876dc620a7: Error: Invalid patch string: @@ -20589,16 +20589,25 @@\n at poop%0A\n+- %5B %5D lip\n %0A- %5B %5D G\n
    at diff_match_patch.patch_fromText (/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/node_modules/diff-match-patch/index.js:2092:13)
    at Function.applyTextPatchLegacy (/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:43:21)
    at Function.applyTextPatch (/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:59:25)
    at Function.<anonymous> (/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:269:36)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_JoplinrwdjsI/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:5:58)
```

**Comment by c-mart** [comment]
[log-tail.txt](https://github.com/laurent22/joplin/files/7281599/log-tail.txt)

**Comment by c-mart** [comment]
I found the note and section of text that I think it's complaining about:

![image](https://user-images.githubusercontent.com/13605043/135932446-9ced098c-cf14-48c1-872d-b51eb12161fd.png)

`Invalid patch string: @@ -20589,16 +20589,25 @@\n at poop%0A\n+- %5B %5D lip\n %0A- %5B %5D G\n` seems to match.

_This_ note (last edited on December 23 of last year) **does** have history! So, perhaps I made some edit to this note that broke the saving of its own history, and maybe also the saving of history of _all other notes_ in the app. [This](https://discourse.joplinapp.org/t/unexpected-behavior-with-restoring-previous-notes-versions/15140/2) forum thread sounds very related. Do certain special characters in notes silently break the saving of note history?

**Comment by c-mart** [comment]
I tried moving the contents of the offending note to another application, so the note in Joplin is now empty. After restarting Joplin, I now get a similar error for a different note:

```
/tmp/.mount_Joplin0wWpAa/resources/app.asar/node_modules/@joplin/lib/Logger.js:188 15:33:25: RevisionService: RevisionService::collectRevisions: Could not create revision for note: 3b0b4aa7fbfa44c492f50ac06f008ccb: Error: Invalid patch string: @@ -20834,16 +20834,30 @@\n 0/12/28 14:20:00\n+%0Ai 2020/12/30 \n
```

![image](https://user-images.githubusercontent.com/13605043/135933814-bef102e2-b6e5-41a1-bdda-22ea31e92eee.png)

If I clear the text out of that note, I get a similar error for note with another ID.

So, the part of Joplin that saves note history doesn't like the contents of several of my notes. Unfortunately these are pretty long notes so I don't know exactly which parts of the note are triggering the issue.

**Comment by c-mart** [comment]
Not been fixed, still requires attention. I may get some time soon to diagnose further.

**Comment by ManuelFte** [comment]
Same issue here on Manjaro Linux 21.2.0 with the official AppImage. I just realized none of my notes had a history, but I also noticed I had been stuck on version 1.0.179.940 since forever (from what I read, apparently that particular version had a bug that had broken the auto-updates on Linux).

I deleted the AppImage file and the `~/.joplin` and `~/.config/Joplin` folders, and made a backup of `~/.config/joplin-desktop` (that contains the notes), then installed the latest version 2.6.10, and some of the notes' histories are back, but not many of them.

New notes don't seem to be saving any history from what I tested. Even some of the notes that recovered their histories are not saving any new history, so it's all very random and confusing. :confused:

**Comment by laurent22** [comment]
This should be fixed in recent versions.

**Comment by c-mart** [comment]
@laurent22 I just upgraded to 2.6.10 and unfortunately it's still happening. Still getting this in the console log... 

```
RevisionService: RevisionService::collectRevisions: Could not create revision for note: af63e4715c1f4b30bdacd0a4540316bc: Error: Invalid patch string
```

@ManuelFte, working any better for you?

**Comment by ManuelFte** [comment]
@c-mart On version 2.6.10 as well. The notes that had lost their histories didn't recover them, but I think both new and old notes are saving histories correctly. The notes with missing histories output this error in the console:

`Could not generate diff: SyntaxError: Unexpected end of JSON input`

**Comment by laurent22** [comment]
@ManuelFte, could you provide the complete messages please, with file paths and line numbers please? This is to find out where exactly it happens.

**Comment by ManuelFte** [comment]
> @ManuelFte, could you provide the complete messages please, with file paths and line numbers please? This is to find out where exactly it happens.

Sure, this is what it says:

```
Revision.ts:142 Could not generate diff: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.newPatchToDiffFormat (Revision.ts:123)
    at Function.patchStats (Revision.ts:137)
    at Function.revisionPatchStatsText (Revision.ts:174)
    at NoteRevisionViewerComponent.render (/tmp/.mount_JoplinPr2JMq/resources/app.asar/gui/NoteRevisionViewer.min.js:168)
    at finishClassComponent (/tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17039)
    at updateClassComponent (/tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16994)
    at beginWork$1 (/tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505)
    at beginWork$$1 (/tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23193)
    at performUnitOfWork (/tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208) 
patchStats @ Revision.ts:142
revisionPatchStatsText @ Revision.ts:174
render @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/gui/NoteRevisionViewer.min.js:168
finishClassComponent @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17039
updateClassComponent @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16994
beginWork$1 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18505
beginWork$$1 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23193
performUnitOfWork @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22208
workLoopSync @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22185
renderRoot @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21878
runRootCallback @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21554
(anonymous) @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11353
unstable_runWithPriority @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
flushSyncCallbackQueueImpl @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11349
flushSyncCallbackQueue @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11338
scheduleUpdateOnFiber @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21431
enqueueSetState @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13100
Component.setState @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react/cjs/react.development.js:471
viewer_domReady @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/gui/NoteRevisionViewer.min.js:62
processTicksAndRejections @ internal/process/task_queues.js:95
async function (async)
viewer_domReady @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/gui/NoteRevisionViewer.min.js:60
webview_domReady @ NoteTextViewer.tsx:45
webview_load @ NoteTextViewer.tsx:53
load (async)
initWebview @ NoteTextViewer.tsx:88
tryInit @ NoteTextViewer.tsx:125
componentDidMount @ NoteTextViewer.tsx:131
commitLifeCycles @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20049
commitLayoutEffects @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22813
callCallback @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:347
invokeGuardedCallbackDev @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:397
invokeGuardedCallback @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:454
commitRootImpl @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22585
unstable_runWithPriority @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
commitRoot @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22414
runRootCallback @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21554
(anonymous) @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11353
unstable_runWithPriority @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:643
runWithPriority$2 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11305
flushSyncCallbackQueueImpl @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11349
flushSyncCallbackQueue @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11338
discreteUpdates$1 @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21677
discreteUpdates @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:2359
dispatchDiscreteEvent @ /tmp/.mount_JoplinPr2JMq/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5979
```

**Comment by erichiller** [comment]
I am having this issue on Android v2.6.8

Here is the log
```
02-24T07:55:53,30,"""SearchEngine: Updated FTS table in 237ms. Inserted: 1. Deleted: 0""
02-24T07:55:53,30,"RevisionService: ""RevisionService::maintenance: Done in 288ms""
02-24T07:55:53,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
02-24T07:55:53,10,"RevisionService: ""RevisionService::collectRevisions:", "SyntaxError: Could not create revision for note: dfdcac2ad51c45ce813f451767977d77: JSON Parse error: Unterminated string
Could not create revision for note: dfdcac2ad51c45ce813f451767977d77: parse@[native code]
value@index.android.bundle:1474:2563
index.android.bundle:1474:7600
p@index.android.bundle:83:588
index.android.bundle:83:1893
s@index.android.bundle:1474:1238
u@index.android.bundle:77:157
index.android.bundle:77:866
index.android.bundle:85:1672
k@index.android.bundle:85:500
w@index.android.bundle:85:898
callReactNativeMicrotasks@index.android.bundle:85:3054
value@index.android.bundle:38:2868
index.android.bundle:38:960
value@index.android.bundle:38:2504
value@index.android.bundle:38:919
value@[native code]
value@[native code]""
02-24T07:55:53,30,"""SearchEngine: Updating FTS table...""
02-24T07:55:53,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
02-24T07:55:53,30,"RevisionService: ""RevisionService::maintenance: Starting...""
02-24T07:55:23,30,"Synchronizer: ""Total resources: 24""
02-24T07:55:23,30,"Synchronizer: ""Total notes: 105""
02-24T07:55:23,30,"Synchronizer: ""Total folders: 18""
02-24T07:55:23,30,"Synchronizer: ""Operations completed: ""
02-24T07:55:23,30,"Synchronizer: ""updateRemote: 1""
02-24T07:55:23,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1645710916851]""
```

I was unable to find any suspect string in the `dfdcac2ad51c45ce813f451767977d77` note, so I deleted the note and created a new one, however I still receive the same error (for the same note id too).

Let me know if you need any more information.

**Comment by laurent22** [comment]
When you open the note history screen, and it says "Could not generate diff", it should also print the patch object in the console. Please could you check that and provide this info here? I don't understand how it can be corrupted and that would help to see it.

**Comment by Perkolator** [comment]
> patch object in the console

I have no idea what that is. But, errors can be expanded in the console and there's more lines. The 2nd error is on most parts the same as the 1st, but there's 26 lines more in it in the middle.

[error1.txt](https://github.com/laurent22/joplin/files/8147294/error1.txt)

[error2.txt](https://github.com/laurent22/joplin/files/8147295/error2.txt)

**Comment by laurent22** [comment]
No I mean after these two errors. It's supposed to print the string that's causing problem, so this is what I'd like to see.

**Comment by Perkolator** [comment]
This is all that is printed in the console:

![errors](https://user-images.githubusercontent.com/53913724/155858926-87e706d5-f22b-4a5f-a765-d9bb6a66494f.png)

**Comment by laurent22** [comment]
Thanks for the log. What I was expecting is indeed not there so perhaps it means it fails on empty data but that would be weird. I will check.

**Comment by Perkolator** [comment]
In the commit you wrote this comment:

> // If any revision creation fails, we continue
// processing the other changes. It seems a rare bug
// in diff-match-patch can cause the creation of
// revisions to fail in some case. It should be rare
// and it's best to continue processing the other
// changes. The alternative would be to stop here
// and fix the bug, but in the meantime revisions
// will no longer be generated.
> 
> // The drawback is that once a change has been
// skipped it will never be processed again because
// the error will be in the past (before
// revisionService.lastProcessedChangeId)

So the bug is not completely fixed yet? Sometimes a revision will not be saved? And the only way to notice this is to watch the console all the time?

**Comment by laurent22** [comment]
I've fixed several issues so it will be more reliable, but it looks like there's still an upstream bug that can cause a bug in some rare cases. The impact is that some revisions might not be created - say instead of having 50 revisions for a note you'll end up with 49. The advantage of that new approach is that the revision service keeps working even when having this kind of failure.

I'm very keen to fix that upstream bug but I've spent a lot of time on it already (not just this time - I've investigated that many times), and I'm stuck. Happy to get help for this if someone knows a better way.

**Comment by laurent22** [comment]
For those with note history issues, please could you try the latest version and let me know how it works?

https://github.com/laurent22/joplin/releases/tag/v2.7.14

Any error message should also be more detailed now.

**Comment by Perkolator** [comment]
Only thing we can do is to run Joplin with the console open all the time to catch these rare errors? Should we report here in this issue?

Stupid question, how to install the pre-release on linux? I've always used the install script. Just overwrite the `~/.joplin/Joplin.AppImage`?

**Comment by laurent22** [comment]
> Stupid question, how to install the pre-release on linux? I've always used the install script. Just overwrite the ~/.joplin/Joplin.AppImage?

I think the install script as an update flag, but overwriting the AppImage should work too.

> Only thing we can do is to run Joplin with the console open all the time to catch these rare errors? Should we report here in this issue?

Yes feel free to report them here, especially now that the error message should be more detailed.

**Comment by Perkolator** [comment]
> I think the install script as an update flag

It seems that using the `--prerelease` argument is not going to work if using the `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash` download/install command. Would be easy to test prereleases if that would work. But, if overwriting the appimage works, I use that.

**Comment by Daeraxa** [comment]
Adding arguments to the script should work fine - https://joplinapp.org/faq/#how-can-i-pass-arguments-to-the-linux-installation-script

i.e. it should be `wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash -s -- --prerelease`

**Comment by Perkolator** [comment]
First report. After opening the prerelease, the sync reported `Created remote items: 36. Fetched items: 36/36.` even though I synced before closing Joplin before updating. Also the Sync Status now says: `Revision: 1186/1208` and `Total: 1300/1322`. Last time the revision count was `1152/1152`. Clicking the sync button manually ended up with this `Created remote items: 22.
Fetched items: 22/22.` and now revision and total counts match.

Checking one note that I have edited recently and which previously did show that the last revision was from 2021-07-02, now shows a newer revision dated 2022-02-03. Checking few other notes revisions show similar cases. So revisions were made locally during this time when this problem started to happen but they were not synced?

And here's the the error I now see (with more details, email & country code of google search redacted) after opening Joplin:

```
14:17:28: RevisionService: maintenance: SyntaxError: Revision f731b9c467114063af641e4d02aba0bc: Could not apply patch: Unexpected token 
 in JSON at position 344: {"new":{"id":"b1a2ec6d85f945ca8039685549ac5055","parent_id":"093f0fcaca434b399bf02a3f9821c46f","latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":REDACTED","source_url":"https://www.google.XX/search?tbs=li:1&q=transfer+from+lumia+to+android&gws_rd=cr&ei=oz8rWOn8EYKWsAHp1ISgDw#tbs=li:1&q=android+for+dummies
","is_todo":0,"todo_due":0,"todo_completed":0,"source":"evernote.desktop.win","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"markup_language":1},"deleted":[]}
    at JSON.parse (<anonymous>)
    at Function.applyObjectPatch (node_modules/@joplin/lib/models/Revision.js:110)
    at Function.<anonymous> (node_modules/@joplin/lib/models/Revision.js:271)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/@joplin/lib/models/Revision.js:5)
    at processTicksAndRejections (internal/process/task_queues.js:95)
```
Old note that I haven't completely cleaned out yet (lazy). I located the note in question and opening the note properties does not show any URL's.. so that error message is related to some older revision where the "source_url" was still in place?

Opening the version history view creates this error (email & country code of google search redacted):

```
Uncaught (in promise) SyntaxError: Revision f731b9c467114063af641e4d02aba0bc: Could not apply patch: Unexpected token 
 in JSON at position 344: {"new":{"id":"b1a2ec6d85f945ca8039685549ac5055","parent_id":"093f0fcaca434b399bf02a3f9821c46f","latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"REDACTED","source_url":"https://www.google.XX/search?tbs=li:1&q=transfer+from+lumia+to+android&gws_rd=cr&ei=oz8rWOn8EYKWsAHp1ISgDw#tbs=li:1&q=android+for+dummies
","is_todo":0,"todo_due":0,"todo_completed":0,"source":"evernote.desktop.win","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"markup_language":1},"deleted":[]}
    at JSON.parse (<anonymous>)
    at Function.applyObjectPatch (Revision.ts:104)
    at Function.<anonymous> (Revision.ts:277)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinlnzHM8/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:8
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinlnzHM8/resources/app.asar/node_modules/@joplin/lib/models/Revision.js:4)
    at Function.mergeDiffs (Revision.ts:240)
    at RevisionService.<anonymous> (RevisionService.ts:224)
    at Generator.next (<anonymous>)
```
The history view doesn't show any revision contents, only the above error message again when selecting a revision from the dropdown box (6 listed).

**Comment by Perkolator** [comment]
I don't know if this is related but I noticed that 5 of the revisions in the above problematic note have old dates from 2019. If the maximum note history is 730 days (2 years) then revisions from 2019 shouldn't exist anymore, right?

**Comment by laurent22** [comment]
> And here's the the error I now see (with more details, email & country code of google search redacted) after opening Joplin:

That's interesting, thanks for the info. Any chance you could send the complete message privately either as PM on the forum or by email? https://github.com/laurent22/joplin/blob/dev/Assets/AdresseSupport.png Because it's very strange that Electron would be able to encode something but not able to decode it.

**Comment by laurent22** [comment]
or perhaps even replacing the email & country code with strings of the same length (eg aaaa@aaaaa.com)

**Comment by Perkolator** [comment]
Replaced strings with same length:
```
14:17:28: RevisionService: maintenance: SyntaxError: Revision f731b9c467114063af641e4d02aba0bc: Could not apply patch: Unexpected token 
 in JSON at position 344: {"new":{"id":"b1a2ec6d85f945ca8039685549ac5055","parent_id":"093f0fcaca434b399bf02a3f9821c46f","latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":abcdefg@gmail.com","source_url":"https://www.google.ab/search?tbs=li:1&q=transfer+from+lumia+to+android&gws_rd=cr&ei=oz8rWOn8EYKWsAHp1ISgDw#tbs=li:1&q=android+for+dummies
","is_todo":0,"todo_due":0,"todo_completed":0,"source":"evernote.desktop.win","source_application":"net.cozic.joplin-desktop","application_data":"","order":0,"markup_language":1},"deleted":[]}
    at JSON.parse (<anonymous>)
    at Function.applyObjectPatch (node_modules/@joplin/lib/models/Revision.js:110)
    at Function.<anonymous> (node_modules/@joplin/lib/models/Revision.js:271)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/@joplin/lib/models/Revision.js:5)
    at processTicksAndRejections (internal/process/task_queues.js:95)
```

Do you have any idea why revisions from 2019 are showing in the dropdown box if the max days is 730? I found another note that shows revisions from 2019 even though that note does not create any errors.

**Comment by laurent22** [comment]
Just to be sure what you have is not `"author":abcdefg@gmail.com"` but `"author":"abcdefg@gmail.com"` (with the quote after ":"), is that correct? Because the first one indeed wouldn't work but I don't think it's possible for the app to generate this.

But the error is most like after the URL because that's where character 344 is. I don't quite get if it's a newline characters that got in or a null character. Is there any chance you could run a query to output the data as hexadecimal? The query would be like this, and that would copy the data to data.txt:

> sqlite3 -line ~/.config/joplin-desktop/database.sqlite 'select hex(metadata_diff) from revisions where id ="f731b9c467114063af641e4d02aba0bc"' > data.txt

If you want to remove the email, you can cut out the first 620 characters from the hex dump (that would remove the first 310 characters including the email).

**Comment by Perkolator** [comment]
> "author":"abcdefg@gmail.com"

It's like that, sorry, messed it up in the first post and then copied it to the newest message. :(

I checked the metadata_diff from the database (with DB Browser for SQLite) and the char at the end of the google URL seems to be a newline. Copied string to text editor and it shows a newline between `dummies` and `","is_todo":0`.

Here's the cut hex dump:

`674477237462733D6C693A3126713D616E64726F69642B666F722B64756D6D6965730D222C2269735F746F646F223A302C22746F646F5F647565223A302C22746F646F5F636F6D706C65746564223A302C22736F75726365223A22657665726E6F74652E6465736B746F702E77696E222C22736F757263655F6170706C69636174696F6E223A226E65742E636F7A69632E6A6F706C696E2D6465736B746F70222C226170706C69636174696F6E5F64617461223A22222C226F72646572223A302C226D61726B75705F6C616E6775616765223A317D2C2264656C65746564223A5B5D7D`

**Comment by laurent22** [comment]
Indeed that's a newline (`0D`) although I don't understand how it can end up there, because even if there was one at the end of the URL, it should be encoded properly. But anyway it's good to know that it can happen and that should be fixable.

**Comment by laurent22** [comment]
Just create a new issue to track this: https://github.com/laurent22/joplin/issues/6209

**Comment by Perkolator** [comment]
Found a new error when opening the history view for another note:

```
Uncaught (in promise) Error: Invalid markup language: undefined
    at MarkupToHtml.renderer (MarkupToHtml.ts:73)
    at MarkupToHtml.<anonymous> (MarkupToHtml.ts:121)
    at Generator.next (<anonymous>)
    at /tmp/.mount_JoplinlnzHM8/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MarkupToHtml.js:8
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_JoplinlnzHM8/resources/app.asar/node_modules/@joplin/lib/node_modules/@joplin/renderer/MarkupToHtml.js:4)
    at MarkupToHtml.render (MarkupToHtml.ts:113)
    at NoteRevisionViewerComponent.reloadNote (/tmp/.mount_JoplinlnzHM8/resources/app.asar/gui/NoteRevisionViewer.min.js:118)
    at processTicksAndRejections (internal/process/task_queues.js:95)
```
New issue?

Also, is the "older than 730 days revisions present" a problem, and should I open an issue for it?

**Comment by laurent22** [comment]
> Also, is the "older than 730 days revisions present" a problem, and should I open an issue for it?

Yes feel free to open an issue for this, providing as much info as possible (exact dates and errors in the log, if any).
