### ISSUE TITLE
Code block scrollbars have disappeared.

### ISSUE THREAD

**Issue by an0wak** [laurent22/joplin#5740]
Hi,

In previous versions when creating code blocks with text lengths that exceeded the size of the window, used to provide a scroll bar at the bottom of each code block. This now seems to have disappeared?

## Environment
Joplin version: 2.5.12
Platform: Windows 10
OS specifics: 10.0.18363

## Steps to reproduce
1. Open Joplin 
2. Either go to an existing or create a new code block that has significant length of text.
3. On the right pane of the split view the text no longer has a scrollbar when exceeding the page.

Image shows code block text missing scrollbars and text overflowing passed the boarder boundaries.
![image](https://user-images.githubusercontent.com/74270857/142066776-b9a05ad5-1947-4537-a766-0215ca094b80.png)

![image](https://user-images.githubusercontent.com/74270857/142068434-935a7880-108b-4cd4-9252-ef6b3a0d7ecc.png)

## Describe what you expected to happen
When using block texts they used to have scroll bars at the bottom when text exceeded the page

Expecting it to look something like this.
![image](https://user-images.githubusercontent.com/74270857/142067161-c863914f-fcac-4152-87c9-8841d1e3e60f.png)

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/7549949/log.txt)

**Comment by FreSauce** [comment]
Observed the same issue with code block overflowing on android version of Joplin
<hr />
<h1>Environment</h1>
OS: Android 9<br/>
App Version: Joplin v2.4.3 
<h2>Screenshot</h2>
<img src="https://user-images.githubusercontent.com/34598383/142206046-25b1d678-75ef-466a-bb2a-32ef40442303.png" alt="android" width="300"/>

**Comment by laurent22** [comment]
Was there ever a scrollbar for this? Anyway it's fixed now but I didn't see any code that would have displayed a scrollbar anywhere.

**Comment by an0wak** [comment]
Hi Laurent22,

Yes there used to be a scrollbar for the code blocks in previous versions... didn't pay much attention to which version made it disappear. Thanks, awesome product!!

**Comment by hffaust** [comment]
I just added a new issue for this exact same bug on the same version. I don't think it is fixed. Was there a resolution for this?

**Comment by CalebJohn** [comment]
@hffaust You can view the resolution above ![image](https://user-images.githubusercontent.com/2179547/145525563-d3dc2e74-4ce0-48e3-8a7c-65a8111f16a6.png)

The fix will be available in the next release, you can [download it in pre-release form now if you prefer](https://github.com/laurent22/joplin/releases/tag/v2.6.4).

**Comment by hffaust** [comment]
> @hffaust You can view the resolution above ![image](https://user-images.githubusercontent.com/2179547/145525563-d3dc2e74-4ce0-48e3-8a7c-65a8111f16a6.png)
> 
> The fix will be available in the next release, you can [download it in pre-release form now if you prefer](https://github.com/laurent22/joplin/releases/tag/v2.6.4).

My mistake. Thank you for clarifying that for me.
