### ISSUE TITLE
Android filesystem sync is broken after 2.6.3 update

### ISSUE THREAD

**Issue by shaymagsumov** [laurent22/joplin#5779]
* * *
**Update 20 Dec 2021:** There's currently no solution to this problem. In the meantime you may downgrade to v2.5 by downloading the APK from the official repository:

https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk
* * *

I use filesystem synchronization with path like
/storage/emulated/0/Sync/Data/Joplin

After 2.6.3 update i get this error:
![Screenshot_20211124-094935](https://user-images.githubusercontent.com/7124186/143189927-4985875c-d7fb-4c85-a3c7-97a8223c8595.png)

Could it be related to app permissions? I can choose only 'Allow access to media only' option in permission manager.
![Screenshot_20211124-095131](https://user-images.githubusercontent.com/7124186/143190138-2fa885e7-ce8f-4f1d-8b5e-4876aa710e4a.png)

**Comment by buckket** [comment]
I can confirm this happens with all my Android devices running Android 10 and Android 11.

Here’s the relevant log snippet:
```
11-24T11:13:56,20,"Synchronizer: ""Error: Error: Operation not permitted. Path: /storage/[redacted]/Joplin/locks/2_2_9450db2b66d24ccebc610d4adbc98838.json
Code: EUNSPECIFIED
value@index.android.bundle:1029:275
index.android.bundle:1029:4056
p@index.android.bundle:82:588
index.android.bundle:82:1893
p@index.android.bundle:82:588
o@index.android.bundle:82:1069
index.android.bundle:82:1241
u@index.android.bundle:76:157
index.android.bundle:76:866
index.android.bundle:84:1672
k@index.android.bundle:84:500
w@index.android.bundle:84:898
callReactNativeMicrotasks@index.android.bundle:84:3054
value@index.android.bundle:37:2868
index.android.bundle:37:960
value@index.android.bundle:37:2504
value@index.android.bundle:37:919
value@[native code]
value@[native code]""
```

**Comment by laurent22** [comment]
This is probably due the Android SDK update, but not sure how (or if) that can be fixed. If someone has any idea I'd accept a pull request.

**Comment by Robin-Sch** [comment]
Makes the app completely useless for me, I can't sync between my phone and pc anymore

https://github.com/laurent22/joplin/issues/5639
https://github.com/laurent22/joplin/issues/5691

**Comment by Timothy-Ecc19** [comment]
Add another one to the list. On Android 11 with 2.6.3 update I am no longer able to sync to my SD card so syncthing can access it. How would I go about downgrading to the previous version or can anyone think of another work around?

**Comment by blueorignal** [comment]
I am also experiencing the same issue when upgrading to version 2.6.3 on Android 11. Dropping back to version 2.4.3 (Google Version Code: 2097651) resolves the issue.

@laurent22  I just want to say thank you for this amazing software. It's easy to forget how much effort goes into making something like Joplin. If there is anything I can do help narrow down the issue (logs, testing, etc.) , please let me know.

**Comment by laurent22** [comment]
For info there's a bug in GitHub that makes it display the wrong version in the release page. Instead you need to go to the tags to see them: https://github.com/laurent22/joplin-android/tags

**Comment by shaymagsumov** [comment]
To downgrade you can also use Aurora Store client and choose manual download with specified version code

**Comment by shaymagsumov** [comment]
BTW i downgraded to 2.4.3 ans now i see different permission options:
![Screenshot_20211125-123736](https://user-images.githubusercontent.com/7124186/143417378-faacfba9-527e-4467-b4d6-5abc656c790b.png)

**Comment by laurent22** [comment]
Maybe they've renamed or removed the permission in this SDK update.

**Comment by github-ronk** [comment]
> This is probably due the Android SDK update, but not sure how (or if) that can be fixed. If someone has any idea I'd accept a pull request.

@laurent22 - [This Stack Overflow post](https://stackoverflow.com/a/68141908) seems to have the necessary information, in case you haven't seen it yet.

**Comment by da2x** [comment]
@laurent22 can you should the SDK update until this is fixed?

I’m also using Syncthing.

**Comment by da-sti** [comment]
same thing here 

android 11 (oxygenOS 11.1.1.1)
joplin android 2.6.3
syncthing 1.18.3

no obvious changes happened on the android side

**Comment by MikhailShi** [comment]
same issue since yesterday

android 11 (MIUI Global 12.5.2)
joplin android 2.6.3
syncthing 1.18.3

![IMG_20211126_185937](https://user-images.githubusercontent.com/25760031/143577845-c5a25521-f3dd-44c4-865c-196c7de91e33.jpg)

**Comment by laurent22** [comment]
> @laurent22 can you revert the SDK update until this is fixed?

Unfortunately no, because it's required by Google. We can't publish to the app store otherwise.

**Comment by rockhazard** [comment]
Happening to me too. Removing and re-creating the locks directory has no effect.

**Comment by Timothy-Ecc19** [comment]
Anyone figure out what folder the "allow access to media only" gives? Maybe we could sync to there and syncthing would still be able to see it.

**Comment by bensoibj** [comment]
Is only Android 11 and higher affected? Maybe it is related [Storage updates in Android 11](https://developer.android.com/about/versions/11/privacy/storage). Which API level does Joplin use on Android?

**Comment by bacteriostat** [comment]
I am on Android 11 and I also couldn't sync after updating to 2.6.2 version. But I got a different error which I reported here #5673? 

My storage location is inside Documents folder which is part of shared storage under Android 11 and maybe that's why the error is somewhat different?

**Comment by ase1590** [comment]
Seems to be an android 11 issue, as upgrading from 2.4.3 to 2.6.3 results in the same issue on a Moto G Power Android 11 device. Downgrading back to 2.4.3 fixes the issue.

**Comment by BeatLink** [comment]
The issue exists on my Android 12 Samsung a21s. I am fairly sure the issue lies in a recently implemented storage API

**Comment by jerseyblue** [comment]
I can confirm this issue is also on android 12 (using filesystem sync target with Syncthing on a pixel 5). Downgrading to 2.4.3 resolves the issue. Just need to fiddle to stop the play store from upgrading it till the issue is resolved.

@laurent22 I'm curious if you have identified root cause and have a plan to resolve. Or a proposed workaround (e.g., should I be thinking about migrating to a different sync strategy, though I love the Joplin/Syncthing combo!)

**Comment by Riolku** [comment]
I mentioned some possible causes in my issue #5810. It boils down to Media access is insufficient, Joplin needs full system access to be able to work properly. I think it's a matter of changing the permission requested, and I do think it has something to do with the new android storage APIs, but I don't have much experience on android development.

I think Joplin + Syncthing is very common (I use it too), and I feel like it would be ideal to make an effort to keep that. The easy solution to this is likely to figure out what we need to change to request the proper permission.

**Comment by github-ronk** [comment]
> I think Joplin + Syncthing is very common (I use it too), and I feel like it would be ideal to make an effort to keep that. The easy solution to this is likely to figure out what we need to change to request the proper permission.

Indeed.    Even more so since the Joplin cloud-based sync solutions are too unstable to be usable (for **me**, according to my **personal** experience with Dropbox and then OneDrive syncing.  YMMV)

**Comment by sedlund** [comment]
Device on android 11, and using Syncthing.  Downloaded 2.4.3 from apkpure.com and side loaded.  Sync working again.

**Comment by bensoibj** [comment]
A similar issue (#4122) occurred a year ago, it has been solved in PR #4134. This pull request set the flag `requestLegacyExternalStorage`, in this way opting out of the [Scoped storage enforcement](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage) of Android 11. However, with API level 30 (which Joplin Android uses since the 2.6.3 update, more precisely, already in [2.6.1](https://github.com/laurent22/joplin/commit/66e79ccb2385ee808185a601231933b8279d3b0f#diff-db9874930c7d8462c48137c8c70352f48e99d6d1e77f1e067fa4378862fdccd8)) this flag is ignored.

**Comment by frederikstroem** [comment]
> Device on android 11, and using Syncthing. Downloaded 2.4.3 from apkpure.com and side loaded. Sync working again.

Instead of downloading from a third-party APK site, it would probably be more advisable to use the [official repo](https://github.com/laurent22/joplin-android) specifically made for that purpose. 😊

Version 2.4.3 can be found here: https://github.com/laurent22/joplin-android/releases/tag/android-v2.4.3

**Comment by elacdude** [comment]
I am experiencing the same error

Local file storage with syncthing

Downgrading to version 2.4.3 fixed it.

**Comment by oliverjoa** [comment]
I have the same problem here, using v.2.6.3 together with syncthing

**Comment by headkaze** [comment]
I'm having a similar issue but in Android 12
```
12-05T15:12:42,30,"Synchronizer: ""Operations completed: ""
12-05T15:12:42,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1638735161375]""
12-05T15:12:42,10,"Synchronizer: ""Error: Could not upgrade from version 0 to version 1: Error: File '/storage/emulated/0/Download/Sync/Data/Joplin/.sync/version.txt' does not exist and could not be created, or it is a directory. Path: /storage/emulated/0/Download/Sync/Data/Joplin/.sync/version.txt
Code: ENOENT
value@index.android.bundle:1029:275
index.android.bundle:1029:4056
p@index.android.bundle:82:588
index.android.bundle:82:1893
p@index.android.bundle:82:588
o@index.android.bundle:82:1069
index.android.bundle:82:1241
u@index.android.bundle:76:157
index.android.bundle:76:866
index.android.bundle:84:1672
k@index.android.bundle:84:500
w@index.android.bundle:84:898
callReactNativeMicrotasks@index.android.bundle:84:3054
value@index.android.bundle:37:2868
index.android.bundle:37:960
value@index.android.bundle:37:2504
value@index.android.bundle:37:919
value@[native code]
value@[native code]""
12-05T15:12:41,30,"""MigrationHandler: Releasing exclusive lock""
12-05T15:12:41,30,"""MigrationHandler: Migrating from version 0 to version 1""
12-05T15:12:41,30,"""MigrationHandler: Acquired exclusive lock:", "{"id":null,"type":2,"clientType":2,"clientId":"*removed*","updatedTime":1638735161000}""
```
Looking at the permissions for Joplin all it has is "Allow access to media only" but it probably needs "Allow management of all files".
![Screenshot_20211205-152714](https://user-images.githubusercontent.com/1698401/144762998-779ff60c-3674-4a0b-8dbe-301f4f61289c.png)
![Screenshot_20211205-152655](https://user-images.githubusercontent.com/1698401/144762999-6cc9a35f-7345-4659-ae2b-27aeb0537b66.png)

**Comment by danielb2** [comment]
any workaround yet? Given the nature of this, it's rendering use of the android app useless for me since it is not synching my files at all now. Is anyone else having this severity or is it just showing the error? (iow, could I also be encountering a different issue)

**Comment by Riolku** [comment]
Some people have been having success downgrading the app to 2.4.3. Im having the same severity as you and others I think. We unfortunately dont have anyone taking this on :)

**Comment by danielb2** [comment]
I'll try the downgrade. thank you

**Comment by danielb2** [comment]
how do I downgrade? I don't see the apk for the 2.4.3 version : https://github.com/laurent22/joplin/releases/tag/v2.4.3

**Comment by jerseyblue** [comment]
@danielb2, Downgrading is a suitable workaround for now -- two things to be aware of:
1) You can download it here: https://github.com/laurent22/joplin-android/releases/tag/android-v2.4.3.
1b) In the google play app, you need to set Joplin to NOT auto update.
2) Be aware that you'll lose any changes on your Android device when you downgrade. It wasn't an issue for me because I caught the lack of sync-ing early on and knew exactly what was out of date. Not sure if others have solved this issue.

**Comment by danielb2** [comment]
@jerseyblue thank you for the detailed instructions and the heads up on exactly what data loss I could see. Very helpful

**Comment by danielb2** [comment]
Tried installing but it says "App not installed." Any reason I'd get that?

**Comment by cyphase** [comment]
@danielb2 I'm guessing because the profile/settings were upgraded to the format of the version you currently have, and therefore you can't install an older version that doesn't know how to understand that later format. This is why it was mentioned that you would lose changes on mobile; you have to uninstall the app first, deleting the profile, before reinstalling.

FYI, another workaround is to change to some other sync target. I moved to WebDAV to work around this issue. I didn't have to downgrade.

**Comment by headkaze** [comment]
> Tried installing but it says "App not installed." Any reason I'd get that?

When I try to downgrade to 2.4.3 I get "You can't install the app on your device."

**Comment by cyphase** [comment]
@headkaze See my comment above yours. https://github.com/laurent22/joplin/issues/5779#issuecomment-986386696

**Comment by headkaze** [comment]
> @headkaze See my comment above yours. [#5779 (comment)](https://github.com/laurent22/joplin/issues/5779#issuecomment-986386696)

I don't think it applies to me. My problem appears to be a permission issue. It cannot read the version.txt file (which exists and contains the value "2")

**Comment by roman-r-m** [comment]
If my understanding is correct, according to [this doc](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory) it's still possible to request access to a directory and get read/write access to it.
The problem is that it requires a different (URI-based) API and I'm not aware of any react-native wrappers over the required Android API for this.

**Comment by headkaze** [comment]
I managed to downgrade to 2.4.3 by clearing storage before uninstalling but it will not read my notes (my guess is their the wrong version) so I had to upgrade back to 2.6.3.

The doc @roman-r-m links to above mentions the Download directory being restricted in Android 11 (API level 30) so I moved my Resilio Sync folder to the root.

I no longer get an error reading version.txt but instead get:
`Error: Operation not permitted. Path: /storage/emulated/0/Sync/Data/Joplin/locks/2_2_619d48f8508f4330b9a8c6e644074f9c.json`

**Comment by roman-r-m** [comment]
@headkaze try `Documents`

**Comment by samuelkyl** [comment]
I'm getting similar problems as @headkaze with both Downloads and Documents directories. It looks like the Laptop-synced (2.5.12) files have `version.txt` as 2, and `info.json` as version 3, but the Android version is trying to do something weird to do an upgrade path starting from 0. If I delete those files I get into a bad situation where the Android app generates the files then gets stuck trying to migrate.

Also, I was trying out this thing https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory with https://reactnative.dev/docs/linking#sendintent-android like so:
```
Linking.sendIntent('android.intent.action.OPEN_DOCUMENT_TREE');
```
which is supposed to give me a file-picker where I choose which folder to grant access to, but then I hit this issue https://github.com/facebook/react-native/issues/28934 where it doesn't like me creating new activities with an Intent, which has just been fixed in the fb internal build of `react-native` but not the public one.

**Comment by roman-r-m** [comment]
@samuelkyl sending an Intent to open directory picker is only half the story (more like 20% actually). The real issue is that even if you granted permissions to a dir you can't use file-based API like Joplin does but have to work with Uri instead. 

I had a PR that was supposed to use directory picker: https://github.com/laurent22/joplin/pull/4903
But again, this alone isn't going to help.

**Comment by bensoibj** [comment]
For the protocol: considering its age, this is currently the most commented open Joplin issue (44 comments in 14 days).

**Comment by buckket** [comment]
> @laurent22 What version of the Android SDK is Joplin 2.4.3 compiled? Can we get 2.6.4 compiled under the same SDK to side-load as a work around until the permission issue is resolved?
> 
> EDIT: I ran apktool on joplin-v2.4.3.apk and got:
> 
> ```
> sdkInfo:
>   minSdkVersion: '21' (Android 5.0 Lollipop)
>   targetSdkVersion: '29' (Android 10 Q)
> ```

Unfortunately the Google Play store won’t accept updates targeting SDK 29 anymore.

**Comment by headkaze** [comment]
> Unfortunately Google Play store won’t accept updates targeting SDK 29 anymore. So that’s not an option.

I'm asking for a signed version built with SDK 29 to side-load as an interim solution. Just until the permission issue is resolved.

**Comment by Fabick75** [comment]
Hi, I'm following this thread for a rapid resolution, but don't seem that came very early. I've now five systems (two mobile and three desktop) in sync with syncthing and joplin on top. My question is how not to lose the modifications that I've created on one of the mobile device. Could convert in another system (like webDAV) and how? Otherwise It's necessary to wait for a resolution with SDK ?

**Comment by kernelpanic-cc** [comment]
Hello,
I have the same issue, Android 12, Joplin 2.6.3.
So far only confirmed workaround that worked for me was to remove google store version of Joplin and download previous one via Aurora Store.
If anyone would like to temporarily go the same way, previous version number you need to provide in Aurora Store (in ”manual download” option) is **2097651** - this will download Joplin v2.4.3.

**Comment by JP1789** [comment]
Same here.. well I got 2 errors looking a bit different on 2 Android phones.
Main PC runs Ubuntu.
Both sync is through file system via SyncThing. Both with Joplin 2.6.3 and Android 11
Phone 1 - Sync folder has same name on the phone and on the main PC.
Error: << Could not upgrade from version 0 to version 1: Error: File '/storage/emulated/0/Documents/Sync/Joplin/.sync/version.txt' does not exist and could not be created or it is a directory. Path: /storage/emulated/0/Documents/Sync/Joplin/.sync/version.txt >>
Of course the said file does exist and contains "2".
Joplin has all permissions possible through Android, as said in various previous posts.
Phone 2 - Originally same folder name etc, so same error. I changed the sync folder then. Created a new sync with new folder on the phone, but same old folder on the main PC: so different names, but SyncThing does work and sent all the files to the phone. But Joplin cannot sync:
Error: << Error: Operation not permitted. Path: /storage/emulated/0/Media/Sync/Joplin/locks/2_2_f838c189717(etc.. many digits...).json>>
Phone 2 shows exactly the same permissions for Joplin as phone 1.

I do not know how to install the previous version of Joplin. I am a simple user enjoying Joplin so far. But now I panic: if I cannot sync my notes on the 2 phones with the main PC, I am in trouble. I would not want to revert to Evernote... 
What is the next step then?

**Comment by seth100** [comment]
Same issue for me. Android 11 and File system sync, shared folder between Linux PC and Android phone. I get `Error: Operation not permitted. Path: /storage/emulated/0/Media/Sync/Joplin/locks/...` error in just installed version 2.6.3. Please fix is as soon as possible! Thanks

**Comment by bbwheeler** [comment]
I also have this issue. Android 11, filesystem sync (with Syncthing). Linux, Windows, TrueNAS machines sync fine. Tried reinstalling but get the same error.

**Comment by smartlitchi** [comment]
Is it fixed with the new version 2.6.8 ?

**Comment by gbetous-swir** [comment]
I run 2.6.8 and I have the same issue with same setup : Joplin + syncthings

**Comment by gbetous** [comment]
I run 2.6.8 and unfortunately I have same issue (also using combo syncthings + Joplin BTW).

**Comment by hdert** [comment]
> I run 2.6.8 and unfortunately I have same issue (also using combo syncthings + Joplin BTW).

Currently running version 2.6.8 from F-droid, filesystem sync, and syncthing, and I can second this.
![signal-2021-12-20-221458](https://user-images.githubusercontent.com/40216616/146742888-daced80b-606f-403e-b2f7-e5a4561b4c45.png)

**Comment by bacteriostat** [comment]
I would suggest to downgrade to 2.5.5 or older and disable updates for Joplin as this issue may take a while to get fixed. From the discussion, it seems react native does not have the needed mechanism to work with Android 11+ filesystem permissions. There have been no commits attributed to this issue, so it is pretty clear it has not been fixed. Just downgrade and wait until some actual changes have been made.

**Comment by gbetous** [comment]
A trustable URL to download the 2.5.5 apk ?

**Comment by hdert** [comment]
> A trustable URL to download the 2.5.5 apk ?

https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk
This is the repo that has the android release tags.

**Comment by seth100** [comment]
> > A trustable URL to download the 2.5.5 apk ?
> 
> https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk This is the repo that has the android release tags (as well).

not an option for me! I need the updates of the last versions. I hope it gets fixed soon !!!

**Comment by roman-r-m** [comment]
If anyone wants to have a go at fixing this, I can explain what changes are required on the Android side.
I just don't have time or interest in doing it myself at the moment.

**Comment by headkaze** [comment]
> If anyone wants to have a go at fixing this, I can explain what changes are required on the Android side.
> I just don't have time or interest in doing it myself at the moment.

I'm interested in the changes required. I'm guessing it's going to be more work than upgrading a few React Native packages though?

**Comment by roman-r-m** [comment]
> I'm interested in the changes required. I'm guessing it's going to be more work than upgrading a few React Native packages though?

Absolutely. More like creating a new RN package. Although it does not have to be a separate package, but can be a part of Joplin core.

Roughly the steps are:
1. Instead of entering a folder manually, Joplin needs to show a dialog prompting the user to select a directory and give access to it. I did most of it here https://github.com/laurent22/joplin/pull/4903 though it was not merged.
2. This should return a URI that Joplin must save.
3. Then when accessing files instead of using instances of `File` class, Joplin must construct [DocumentFile](https://developer.android.com/reference/androidx/documentfile/provider/DocumentFile) using the URI saved earlier. (To be clear this would be in a native module written in Java/Kotlin)

**Comment by headkaze** [comment]
It looks like we need an update to the react-native-fs library. What about [this fork](https://github.com/neosapience/react-native-file-access)?

**Comment by roman-r-m** [comment]
> It looks like we need an update to the react-native-fs library. What about [this fork](https://github.com/neosapience/react-native-file-access)?

Last time I checked `react-native-fs` didn't have the required functionality. The one you linked doesn't seem to have it either.
I'm afraid there's no way around it, it has to be written from scratch

**Comment by tcallsen** [comment]
Thank you to everyone that contributes to this awesome project.

Reverting to the 2.5.5 version and disabling the auto update in the Play Store fixed the issue for me.

https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk

**Comment by liza** [comment]
i am having this problem and it is absolutely a consequence of TMobile/Samsung pushing Android 11, whether you wanted it or not. this isn't just an issue with how apps supposedly deal with the file system going forward, it’s a USER PERMISSIONS problem: the "fix"  to apps acting like spyware has been to strip users from administering our own file folders. 

these changes have broken, for me, not just Joplin but Syncthing, Feedex. any backups these  apps created are not simple documents anymore. they’re now "system files". 

“ u:object_r:fuse:s0 ” is the SElinux context for the Joplin folder. 

so TMobile/Samsung’s android 11 won't let Joplin create a folder ―because it considers it an untrusted app― but wont let ME do create s writable folder for it either. i can create the folder but the file managers can only use the folder. 

caveat: i have not  /.bash’ed a folder to test this perms issue, but since am not rooted, am not sure if it will be any different

**Comment by roman-r-m** [comment]
Nah, it's not specific to TMobile or Samsung, any Android starting from version 11 is affected. If there's anyone to blame it's Google.

**Comment by ghcme** [comment]
I notice the same problem. File sync is the most important feature of Joplin for me in order to use it with Resilio Sync. Please fix it.

**Comment by ase1590** [comment]
For those having issues,
Please do not comment "me too", or "please fix".

This is broken for everyone on android 11.

There is no easy fix, as this project is in need of an android dev willing to write out the new proper file permissions implementation from scratch. 

For now if you cannot contribute code, downgrade the app (read above).

**Comment by danielb2** [comment]
> There is no easy fix, due to Google's new API requirements, as this project is in need of an android dev willing to write out the new proper file permissions implementation from scratch

why is the fix not as simple as rolling back the code to use whatever code is in the downgraded app since most everyone has to use that anyone to get it to work? Is there a feature that's super critical in the higher version which is preventing the downgrade on the app stores?

This IMO, is a breaking release, and should be rolled back. This is a serious product, and should be treated like one. Expecting everyone just to know how to downgrade and not asking to please fix isn't realistic for you to demand.

**Comment by betsythefc** [comment]
So, the code in the previous release was targetting an older version of android, and newer releases are targetting Android 11. The play store is no longer allowing apps to be updated that still target the older versions of android. Joplin didn't change how it gets filesystem access, android changed how it grants it, and how apps interact with the filesystem.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by danielb2** [comment]
> So, the code in the previous release was targetting an older version of android, and newer releases are targetting Android 11. The play store is no longer allowing apps to be updated that still target the older versions of android. Joplin didn't change how it gets filesystem access, android changed how it grants it, and how apps interact with the filesystem.

oh I forgot this was addressed in this thread before. Apologies. 
What can we do to avoid this kind of problem in the future? Have a beta branch?

**Comment by Daeraxa** [comment]
> Have a beta branch?

Pre-releases have always been available. 2.6.1 was pre-released 02/11 and I can only assume that if anyone even saw this issue it wasn't reported (https://joplinapp.org/changelog_android/#android-v2-6-1-https-github-com-laurent22-joplin-releases-tag-android-v2-6-1-pre-release-2021-11-02t20-49-53z)

**Comment by sedlund** [comment]
I suppose the current version with the older SDK could be built and hosted on F-Droid

**Comment by danielb2** [comment]
> Pre-releases have always been available. 2.6.1 was pre-released 02/11 and I can only assume that if anyone even saw this issue it wasn't reported

Not what I'm talking about. I see many apps in the app store having a proper beta release on the app store. Making it available for download each time is a different level of involvement.

**Comment by p5nbTgip0r** [comment]
I managed to work around this issue on Android 11 by setting `android:no_isolated_storage` to allow in the app ops:

`adb shell cmd appops set --uid net.cozic.joplin android:no_isolated_storage allow`

If you're rooted, you should be able to do this without adb by opening a terminal, running `su`, then using the above command without the adb part:

`cmd appops set --uid net.cozic.joplin android:no_isolated_storage allow`

I don't know if this will work on other devices or on A12, apologies if it doesn't.

**Comment by headkaze** [comment]
I'm on Android 12 and the following commands worked for me:
```
adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
adb shell am force-stop net.cozic.joplin
```
Since I use Resilio Sync I also issued the following commands:
```
adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
adb shell cmd appops set com.resilio.sync android:legacy_storage allow
adb shell am force-stop com.resilio.sync
```

**Comment by borisrunakov** [comment]
Also used 2.5.5 as a workaround: https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk

**Comment by headkaze** [comment]
@laurent22 I think we have a satisfactory work around for the permission issue now. Now it's a matter of waiting for react-native-fs to be updated.

**Comment by SuperFes** [comment]
Just FYI, I built my own debug APK with the additional permission MANAGE_EXTERNAL_STORAGE and I can now sync with the file-system in Android 11. (Not sure if this would cause playstore issues or not since the listed apps that are supposed to be able to use this permission includes document management stuff.)

**Comment by enboig** [comment]
I changed from syncthing to S3 to keep my notes synced

**Comment by borisrunakov** [comment]
> I changed from syncthing to S3 to keep my notes synced

So is it a syncthing issue ? Strange..

**Comment by jovandeginste** [comment]
It is not a synching issue

**Comment by danielb2** [comment]
> Since I use Resilio Sync I also issued the following commands:
> 
> ```
> adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
> adb shell cmd appops set com.resilio.sync android:legacy_storage allow
> adb shell am force-stop com.resilio.sync
> ```

I too am using resilio (love it). I'm curious, why are these resilio specific  lines necessary? Shouldn't just the joplin ones be sufficient?

**Comment by borisrunakov** [comment]
> It is not a synching issue

Sorry I thought s3 was similar to syncthing, I.e. local storage and not cloud based.

**Comment by headkaze** [comment]
> I too am using resilio (love it). I'm curious, why are these resilio specific  lines necessary? Shouldn't just the joplin ones be sufficient?

I guess it depends on how the permission system works but I would assume both apps need full r/w access to the same folder.

**Comment by seth100** [comment]
> I'm on Android 12 and the following commands worked for me:
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
adb shell am force-stop net.cozic.joplin

I tried on Android 11 and it gave me `command not found`. What can i do to make it work? Thankd

**Comment by danielb2** [comment]
> I tried on Android 11 and it gave me command not found. What can i do to make it work? Thankd

AFAIK, you have to issue this on your computer when your phone is connected in development mode

**Comment by headkaze** [comment]
> AFAIK, you have to issue this on your computer when your phone is connected in development mode

Yeah the easiest way to get adb is from the [platform-tools](https://developer.android.com/studio/releases/platform-tools)

**Comment by prestidigitonium** [comment]
> I'm on Android 12 and the following commands worked for me:
> 
> ```
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin
> ```
> 
> Since I use Resilio Sync I also issued the following commands:
> 
> ```
> adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
> adb shell cmd appops set com.resilio.sync android:legacy_storage allow
> adb shell am force-stop com.resilio.sync
> ```

is this fix permanent? anyway thank you I solved the problem in android 11 too

**Comment by akadaedalus** [comment]
The adb hacks worked for me too but I ultimately switched to using a self-hosted Joplin server so I can share some notebooks with my wife.  Works pretty slick and far less network traffic than syncthing.  Thanks for the great product.

**Comment by schuerg** [comment]
I also use syncthing to save notes and ran into this problem.

@headkaze  Your fix works splendid, thanks!

I ran these commands:

> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin

**Comment by draxaris1010** [comment]
> I'm on Android 12 and the following commands worked for me:
> 
> ```
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin
> ```
> 
> Since I use Resilio Sync I also issued the following commands:
> 
> ```
> adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
> adb shell cmd appops set com.resilio.sync android:legacy_storage allow
> adb shell am force-stop com.resilio.sync
> ```

Thanks this solution worked, I just had to run the first one on android 11.

**Comment by bjames88** [comment]
I downgraded my Android app to v2.5 which solved the issue.  Do we also need to freeze the version installed on Windows and Linux desktops or can those be keep updated to the latest versions?

**Comment by swordnine** [comment]
Android filesystem sync is broken after 2.7.2 update too.

**Comment by danielb2** [comment]
I'm not able to run the commands. Anyone else run into this?

```
[~/l/t/T/season.07]$ adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow

Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
        at android.app.ContextImpl.enforce(ContextImpl.java:2186)
        at android.app.ContextImpl.enforcePermission(ContextImpl.java:2195)
        at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2555)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2824)
        at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2819)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5554)
        at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:5323)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5495)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1198)
        at com.android.server.appop.OplusAppOpsService.onTransact(OplusAppOpsService.java:38)
        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)
```

**Comment by benbaker76** [comment]
> I'm not able to run the commands. Anyone else run into this?

You may need to turn on developer mode and USB debugging.

**Comment by danielb2** [comment]
> adb shell am force-stop net.cozic.joplin

I wouldn't be able to get to that error without those turned on. 

However. `Disabling permissions monitoring` was what I found online to do, but seems that option would just hide any potential problems, so I'm not sure. I tried it and after the error didn't s how.

**Comment by danielb2** [comment]
> You may need to turn on developer mode and USB debugging.

I wouldn't be able to get to that error without those turned on.

However. `Disabling permissions monitoring` was what I found online to do, but seems that option would just hide any potential problems, so I'm not sure. I tried it and after the error didn't s how.


update: The app works without errors despite having the error messages above. I disabled permissions monitoring before running the commands a final time and upgrading the app.

**Comment by marlluslustosa** [comment]
> I'm on Android 12 and the following commands worked for me:
> 
> ```
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin
> ```
> 
> Since I use Resilio Sync I also issued the following commands:
> 
> ```
> adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
> adb shell cmd appops set com.resilio.sync android:legacy_storage allow
> adb shell am force-stop com.resilio.sync
> ```

its work for me!

**Comment by jlane67** [comment]
Why not just downgrade the SDK version and tell people to switch from Play Store to F-Droid?  That's much more likely than getting people to run adb correctly.

**Comment by Mrnofish** [comment]
I would like to share a workaround that seems to be working for me on Android 11, and which can be applied entirely on device, as it doesn't rely on `adb`.

The only requirement is that the user can enable and work Developer Options.

Under Developer Options, locate `App Compatibility Changes`. Under `Default Enabled Changes`, turn off `DEFAULT_SCOPED_STORAGE`.

2.7.2 appears to be syncing correctly now using Syncthing as a transport. You might need to Force Stop and Restart the app for the permission change to register.

**Comment by Riolku** [comment]
I think this requires the app to be in some state I dont have. I downloaded, for lack of a better choice, from the play store, and when I hit App Compatibility Changes I get "no debuggable apps".

**Comment by Mrnofish** [comment]
Do you have `USB debugging` enabled in Dev Options?

**Comment by Riolku** [comment]
I do now: should I be installing the app using that?

**Comment by Mrnofish** [comment]
That shouldn't be necessary, just check that that apps are now listed under App Compatibility Changes.

**Comment by Riolku** [comment]
That doesnt seem to be the case, no apps are there.

**Comment by Mrnofish** [comment]
Have you tried restarting the device ?

**Comment by sedlund** [comment]
@Mrnofish 

https://developer.android.com/guide/app-compatibility/test-debug

```
Note: You must use a [debuggable build variant](https://developer.android.com/studio/debug#enable-debug) of your app to toggle changes on and off.
```

Which build are you using?

**Comment by Riolku** [comment]
> Have you tried restarting the device ?

Just did, no dice.

**Comment by Mrnofish** [comment]
> Which build are you using?

The official 2.7.2 apk, and all of my apps seem to be showing in the App Compatibility Changes list anyway.

Device is running the latest official LineageOS 18.1 image, perhaps that's the reason it's working for me and not Riolku?

**Comment by sedlund** [comment]
@Mrnofish 

> Device is running the latest official LineageOS 18.1 image, perhaps that's the reason it's working for me and not Riolku?

I think so, I'm running CRDroid Android 11 and none of my apps show up either.  Thanks for sharing though.

**Comment by brnl** [comment]
> I'm on Android 12 and the following commands worked for me:
> 
> ```
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin
> ```
I can also confirm this worked for me as a workaround to allow Joplin to access `/storage/emulated/0/Documents/joplin-notes`. Thanks @marlluslustosa !

**Comment by JuMilia** [comment]
`adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow`
`adb shell cmd appops set net.cozic.joplin android:legacy_storage allow`
`adb shell am force-stop net.cozic.joplin`

I also confirm working synchronization after applying the workaround on android 11.
Thanks everyone involved, good health and good will.

**Comment by draxaris1010** [comment]
It should be on the wiki for now.

**Comment by brnl** [comment]
> It should be on the wiki for now.

It should be fixed ;-)

**Comment by regisz** [comment]
> I'm on Android 12 and the following commands worked for me:
> 
> ```
> adb shell cmd appops set net.cozic.joplin android:no_isolated_storage allow
> adb shell cmd appops set net.cozic.joplin android:legacy_storage allow
> adb shell am force-stop net.cozic.joplin
> ```
> 
> Since I use Resilio Sync I also issued the following commands:
> 
> ```
> adb shell cmd appops set com.resilio.sync android:no_isolated_storage allow
> adb shell cmd appops set com.resilio.sync android:legacy_storage allow
> adb shell am force-stop com.resilio.sync
> ```

Hi, I got the next error in this case:
```
Exception occurred while executing 'set':
java.lang.SecurityException: uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.
	at android.app.ContextImpl.enforce(ContextImpl.java:2186)
	at android.app.ContextImpl.enforcePermission(ContextImpl.java:2195)
	at com.android.server.appop.AppOpsService.enforceManageAppOpsModes(AppOpsService.java:2554)
	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2823)
	at com.android.server.appop.AppOpsService.setMode(AppOpsService.java:2818)
	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5553)
	at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:5322)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:5494)
	at android.os.Binder.shellCommand(Binder.java:970)
	at android.os.Binder.onTransact(Binder.java:854)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:1198)
	at com.android.server.appop.OplusAppOpsService.onTransact(OplusAppOpsService.java:38)
	at android.os.Binder.execTransactInternal(Binder.java:1226)
	at android.os.Binder.execTransact(Binder.java:1163)
```
How can I solve this problem?

**Comment by charlescochran** [comment]
The adb hack works for me as well. Hopefully the app gets updated soon to request "all files access."

**Comment by regisz** [comment]
Hi,

I did the adb hack, but now I get the next error message when I would like to sync:
```
Error: Error: ENOENT: open failed: ENOENT (No such file or directory),
open '/storage/emulated/1/joplin-jegyzetek/.resource/<log hash number :-)>
```
Any idea?

I sync my notes with another app into MegaSync, and it works perfectly.

Oppo Reno 5 5G
ColorOS v12.1 (uptodate)

**Comment by draxaris1010** [comment]
@regisz 
> ColorOS v12.1 (uptodate)

What Android version is this?

**Comment by regisz** [comment]
@draxaris1010
> > ColorOS v12.1 (uptodate)

> What Android version is this?

12 :-)

**Comment by AsimovGod** [comment]
Can I not use the ADB normally now?
- Android 11 (MIUI 12.5)
- Filesystem sync + Syncthing

**Comment by bacteriostat** [comment]
> Can I not use the ADB normally now?
> 
>     * Android 11 (MIUI 12.5)
> 
>     * Filesystem sync + Syncthing

@AsimovGod Try this solution: https://github.com/laurent22/joplin/issues/5779#issuecomment-1013874764

**Comment by AsimovGod** [comment]
> > 我现在不能正常使用亚行吗？ 
> > ```
> > * Android 11 (MIUI 12.5)
> > 
> > * Filesystem sync + Syncthing
> > ```
> 
> @AsimovGod试试这个解决方案： [#5779（评论） ](https://github.com/laurent22/joplin/issues/5779#issuecomment-1013874764)

In fact, version 2.5.5 can be used normally, but it is obviously lacking.It is mainly worried that it will be completely unavailable to update a few more versions. These methods are just expedient.Seeing the current situation, there is no complete solution plan.

**Comment by johemilsson** [comment]
Using Android 11 + filesystem sync with syncthing. Still getting this error. Any plan for a solution?

**Comment by meinto** [comment]
Do I also need to freeze my desctop app version until this issue is fixed?

**Comment by pfaca** [comment]
> Do I also need to freeze my desctop app version until this issue is fixed?

No, you can update the desktop app. The problem is only with android.

**Comment by meowmachine** [comment]
I see this issue was recently closed. Does that mean we can all use the latest Android version now?

**Comment by lerra** [comment]
Hi mate, it is commited to the dev branch, if you wont compile it your self and load it your self on your phone you would need to wait until it is merged and released (so expect it to take some time) :)

**Comment by Mrnofish** [comment]
In this vein, and not meaning to pressure anybody, I would anticipate that a majority of the userbase would welcome a horizon for this change to materialize in a non-beta, even a rough, tentative one, as it is kind of a show-stopper.

Thanks Laurent and jd1378, as well all other contributors, for all your efforts: they're very much appreciated.

**Comment by KrisZane** [comment]
Just gonna put in my two cents here, 99% sure this is a permission problem. Updating to the new permissions that came along with the new storage system, should "fix" the problem for now: https://developer.android.com/training/data-storage/manage-all-files
It probably does make sense to migrate to the new storage platform sooner or later though, as we all know Gurgle will remove the old file management API eventually.

**Comment by NelsonMinar** [comment]
Very much looking forward to this bugfix being released. I've been wondering for 6 months why Joplin was broken, thinking it had something to do with encryption of Syncthing. I'm glad there's a fix committed!

**Comment by personalizedrefrigerator** [comment]
> Very much looking forward to this bugfix being released. I've been wondering for 6 months why Joplin was broken, thinking it had something to do with encryption of Syncthing. I'm glad there's a fix committed!

It's still broken! See https://github.com/laurent22/joplin/issues/6779

**Comment by Mrnofish** [comment]
> It's still broken!

We know. There have been no new Play Store releases after the early June one, after all.

> See https://github.com/laurent22/joplin/issues/6779

May be a good idea to close that one since you are already aware it's a duplicate, now. Save somebody a little work.

**Comment by personalizedrefrigerator** [comment]
> There have been no new Play Store releases after the early June one, after all.

#6779 is tested with building the Android app from source (so shouldn't relate to the lack of a new Play Store release). Perhaps there has been a regression since #6395...

**Comment by benbaker76** [comment]
The solution seems to be to use Scoped Storage but the react-native-fs has not been updated to support it yet. There is an alternative library called [react-native-file-access](https://github.com/alpha0010/react-native-file-access) which supports it. I'm not sure of the work involved to move to this library though.

**Comment by personalizedrefrigerator** [comment]
> The solution seems to be to use Scoped Storage but the react-native-fs has not been updated to support it yet. There is an alternative library called [react-native-file-access](https://github.com/alpha0010/react-native-file-access) which supports it. I'm not sure of the work involved to move to this library though.

Note that `react-native-fs` [may be unmaintained/is looking for a new maintainer](https://github.com/itinance/react-native-fs/issues/1115). As such, switching to [react-native-file-access](https://github.com/alpha0010/react-native-file-access) may otherwise make sense.

**Comment by danielb2** [comment]
I just had to install on a new phone due to an accident and this is STILL not fixed? Seriously? This is weak

**Comment by laurent22** [comment]
Locking as the last two comments (now deleted) were just rants.
