### ISSUE TITLE
Scroll jump when typing in note containing a mermaid diagram and using split view

### ISSUE THREAD

**Issue by shbach** [laurent22/joplin#6074]
When using split view with a note containing a mermaid diagram, there can be a scroll jump when typing:
![Peek 2022-01-29 11-11](https://user-images.githubusercontent.com/5298745/151674579-c61fee3b-ba6f-40ce-8f37-c514145c6312.gif)
![Peek 2022-01-29 11-38](https://user-images.githubusercontent.com/5298745/151675194-baec5657-127b-42ee-9053-04c81fd17b5d.gif)

## Environment

Joplin version: 2.6.10
Platform: Linux
OS specifics: Solus

## Steps to reproduce

Haven't identified the exact parameters that cause it to happen but it only happens in split view when a mermaid diagram is present and you type something. It's particularly annoying in a long note since where you are typing will eventually be completely out of view.

@ken1kob I think this may be related to my [previously reported issue](https://github.com/laurent22/joplin/issues/5918).

**Comment by shbach** [comment]
I've been testing this more and I actually think there might be two separate bugs here. 

1. Editor jumps when you type in split view with a shorter note containing a mermaid diagram:
![Peek 2022-01-29 12-05](https://user-images.githubusercontent.com/5298745/151675957-e3b3d64e-619a-4ce2-b9f0-3f4d3ba4e440.gif)

However, if the note is longer, when you type the editor doesn't jump anymore but the viewer does:
![Peek 2022-01-29 12-09](https://user-images.githubusercontent.com/5298745/151676159-2f6365c7-8088-4026-905e-697513a232ed.gif)

2. Then there is a more mysterious bug that happens on certain notes with a long mermaid diagram when only the editor is showing and is triggered when I either add or delete a space:

![Peek 2022-01-29 13-09](https://user-images.githubusercontent.com/5298745/151677684-6e28d4e8-272e-4000-ab13-78d885b14bff.gif)

**Comment by ken1kob** [comment]
> @ken1kob I think this may be related to my [previously reported issue](https://github.com/laurent22/joplin/issues/5918).

Yes. And it seems to be related to #5951.

I think it was already fixed in the recent pre-release version (2.7.8). Can you try it?

**Comment by shbach** [comment]
@ken1kob I just tried version 2.7.8 and the issues still exist.

**Comment by shbach** [comment]
[examples.zip](https://github.com/laurent22/joplin/files/8054635/examples.zip)

I've attached two examples notes. For the first one it will jump when typing in split view. For the second note it will jump significantly in split view when typing but even in only editor view if you type or remove a space it will still jump a tiny amount.

Happens both on Linux and Windows. Still an issue in v2.7.11

**Comment by laurent22** [comment]
@ken1kob, do you know the reason for this particular bug? Is that because Mermaid needs to be handled in a special way? Because I'm wondering about other renderers, including in plugins - do we need special code to handle each renderer? Or is there a more general solution that could work regardless of the content?

**Comment by ken1kob** [comment]
@laurent22, I'm still investigating, but I think the causes are not unique to Mermaid.
So, the solution will be general.

Maybe, I think the causes are:
- A problem of the precision of scroll position estimations among Editor, Line and View.
- A particular behavior of the bottom of scroll panes. At the point, the scroll position translation is singular.

Not easy problems. I think they are infrequent and thus their priority are not so high.

**Comment by laurent22** [comment]
In general regressions are high priority and based on user feedback it seems to happen relatively often (it came up on Hacker News too), but I agree it's not an easy problem.

I wonder if we could have a general solution that guards against any scrolling whenever typing in the editor? In fact, I think the only time we want the editor to programatically scroll is when the user manually scrolls the view, so perhaps we could detect that and only do editor scrolling in this case?

**Comment by shbach** [comment]
The scroll jump isn't unique to mermaid. I recently noticed this issue also occuring when using the [life calendar plugin](https://github.com/hieuthi/joplin-plugin-life-calendar)

**Comment by ken1kob** [comment]
> The scroll jump isn't unique to mermaid. I recently noticed this issue also occuring when using the [life calendar plugin](https://github.com/hieuthi/joplin-plugin-life-calendar)

Valuable information! Could you attach a note reproducing with life calendar?

**Comment by shbach** [comment]
Here's a note using life calendar which has the issue: [life calendar.zip](https://github.com/laurent22/joplin/files/8085607/life.calendar.zip)

Try typing in the note and it jumps quite a bit both in editor view and split view. In editor view it only jumps if you remove or delete a space though. Typing without a space doesn't cause a jump.

**Comment by ken1kob** [comment]
> life calendar.zip

@shbach, thank you. I can reproduced it.

> based on user feedback it seems to happen relatively often (it came up on Hacker News too), but I agree it's not an easy problem.

Understood, @laurent22. I'll raise its priority. Could you quote feedback on this symptom?

**Comment by ken1kob** [comment]
@laurent22, for the above symptoms, this problem was already fixed in my repo a month ago. If you would not quote additional symtom reports, shall I make a PR now?

**Comment by laurent22** [comment]
Sorry I missed that earlier question. No there wasn't any additional symptom, just this scroll jumping issue as far as I know.

On Discord, someone also mentioned a scrolling issue on a note that had many images, but it might be the same bug as this one.

**Comment by laurent22** [comment]
This is the link to this image jump issue: https://discord.com/channels/610762468960239627/610762468960239629/960267254103171142

**Comment by ken1kob** [comment]
> Sorry I missed that earlier question. No there wasn't any additional symptom, just this scroll jumping issue as far as I know.
> 
> On Discord, someone also mentioned a scrolling issue on a note that had many images, but it might be the same bug as this one.

I see. Thanks for your info. Then, I'll make a PR.
