### ISSUE TITLE
Markdown file with attachments not properly imported (again)

### ISSUE THREAD

**Issue by CR0CKER** [laurent22/joplin#6078]
I noticed that the MD files I had imported a while ago (which were exported from Bear Notes) did not properly import into Joplin if they had non-image attachments like PDFs. Initially, I thought the issue was caused by Bear not exporting the path to the attached files correctly (a bug which they now fixed), but it turns out that Joplin doesn't import the attachments correctly even though the path now appears to be correct. 

As seen in the attached sample file, the link in the MD source is

```
<a href='Water%20boilerheater%20manual/English%20Instructions%20for%20Thermostat.pdf'>English Instructions for Thermostat.pdf</a>
```
After importing into Joplin, the link looks like this and I am getting the error message "Unsupported link or message: :/833e438b618248b7bd2f969f1152de3d" when clicking it. 

```
<a href=':/943aa2a86c5246b2b708a1e60a71654d'>English Instructions for Thermostat.pdf</a>
```
I would expect the link in Joplin to be clickable and - in this case where the attached file is a  PDF -- expect the note to load and display the embedded PDF.

## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Client ID: 1e3bd8989b534aef9b17d47a49e57334
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37
Platform: MacOS
OS specifics: MacOS 12.1 (21C52)

## Steps to reproduce

1. Import the attached sample MD file into Joplin on Mac
2. Open the imported note, click on the link that is supposed to open the attached PDF
3. Get error message

## Describe what you expected to happen

I would expect the PDF to appear embedded in the note and the link to take me to a valid resource.

[Water boilerheater manual.md](https://github.com/laurent22/joplin/files/7966090/Water.boilerheater.manual.md)

**Comment by pathange-s** [comment]
@CR0CKER may I know if this issue exists only on Mac ?

- I tried replicating the issue this is what I found : The pdf was linked to the anchor text and on clicking it, opened the pdf in my default app.
Here is the screenshot for the same.

![image](https://user-images.githubusercontent.com/76244077/151789160-73d33522-5626-4a39-9b91-eaa3e35fc547.png)

On clicking `English Instructions for Thermostat.pdf`

![image](https://user-images.githubusercontent.com/76244077/151789209-07b8375a-f39d-4954-acb3-4d33cdfd97cb.png)

I also notice that the path in anchor has changed in your case after importing it. But in case of Ubuntu, it didn't. Seems like, this issue is specific to mac os.

**Comment by asrient** [comment]
Hi @CR0CKER, I checked this on my mac. The import worked well on my dev version: `Joplin 2.7.8 (dev, darwin)` but was able to reproduce on the version you mentioned: `Joplin 2.6.10 (prod, darwin)`, so I guess it has been fixed on the dev branch, you might wait for sometime for the current dev version to release.

**Comment by CR0CKER** [comment]
Thanks @asrient -- I'll try again after the next update. For now, the bug persist for me on both linux and mac.

**Comment by CR0CKER** [comment]
Something is definitely broken here. I updated to the development version on MacOS, and imported all my MD files (which have proper paths to the attached PDFs in the sample file shared here). After importing in Mac, the attachments were linked correctly. Joplin was fully synced. 

After that, I synced the changes on Android. Result: The attachments could not be found anymore.

After that, I synced Joplin on my linux machine. Result: The attachments could not be found anymore. 

The link to the PDF has remained unchanged.

**Comment by CR0CKER** [comment]
In fact, even now, the attached PDFs open fine on MacOS in the latest development version (though they don't appear embedded), while they do not open att all on Android and Linux (stable versions).

**Comment by CR0CKER** [comment]
The problem still persists on Android mobile. I can open the files on Linux in an external viewer (they don't appear embedded in the note as they used to) but on mobile, clicking the filename does nothing.

**Comment by CR0CKER** [comment]
@laurent22 Could you clarify if it is expected behavior that PDF attachments are now opened in an external app and not embedded anymore? Or is this a result of something being off with the paths of my imported notes? Thanks.
