### ISSUE TITLE
Note does not sync (Status: notDownloaded)

### ISSUE THREAD

**Issue by Guuustav** [laurent22/joplin#6125]
I have successfully installed and synced Joplin on my work Mac, my home Mac, and my Android phone.

Today I had my first problem. Yesterday I wrote a note at home but today it won't open at work. The sync seems to work but when I go into the note it just includes this message:

Please wait until all attachments have been downloaded and decrypted. You can also switch to Code to edit the note.
Status: notDownloaded

## Environment
I have the same at home and at work.
Joplin version: 2.6.10
Platform: macOS
OS specifics: macOS High Sierra 10.13.6

Any idea what can happen?

Thanks in advance. 

P.S. I was recently introduced to Joplin and have already uninstalled Evernote. I find it an gorgeous project!

**Comment by Guuustav** [comment]
Again. Yesterday I modified a note at home and today at work the same message appears.

**Comment by leematos** [comment]
Please include more information as to what sync mechanism you are using so more folks can chime in with relevant knowledge. 😄

**Comment by Guuustav** [comment]
I use Dropbox. If I make changes on the work Mac (iMac 2013 macOS High Sierra) they appear on the Xiaomi phone with Android 12 but not on the home Mac Pro (macOS High Sierra). Those unsynchronized notes are where the error message I mentioned above appears. If I make changes on the home Mac they appear on the phone but do not sync on the work Mac and the error message appears.

**Comment by Guuustav** [comment]
I don't know how it was solved but it already syncs correctly all the notes on all my devices. This thread can now be closed.

Thank you very much.

**Comment by ForumLiker** [comment]
This problem still exists.
Joplin 3.2.13
It occurs if you turn it on "Attachment download behavior" in "Manual" mode

![Image](https://github.com/user-attachments/assets/c4565153-0082-478a-8887-9006bcc53845)
