### ISSUE TITLE
Copy / paste losing formatting on CTRL-V

### ISSUE THREAD

**Issue by Nilliom** [laurent22/joplin#6257]
## Environment

Joplin version: 2.7.14
Platform: Windows 10
OS specifics: 20H2

## Steps to reproduce

1. Write some text with carriage return in the note window
2. Select the text and press CTRL-C
3. Go a little lower in the note and do CTRL-V
4. BUT if we do right click and Select Paste in contextual menu it work OK and keep the formatting

## Describe what you expected to happen

Lines of text should stay formatted with carriage return between each line

Example of text typed:
Test1

Test2

Test3

Sample after CTRL-V:

Test1Test2Test3

Sample after context menu Paste:
Test1

Test2

Test3

## Logfile

Console on pasting CTRL-V:
07:44:07: Scheduling sync operation... 30000
C:\Users\xxx\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:25 Got ipc-message: noteRenderComplete null
C:\Users\xxx\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:25 Got ipc-message: noteRenderComplete null

Console on pasting through context menu:
C:\Users\xxxx\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:25 Got ipc-message: noteRenderComplete null
C:\Users\xxx\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\utils\useMessageHandler.js:25 Got ipc-message: noteRenderComplete null

No logs in log.txt

**Comment by Nilliom** [comment]
It is still occuring. I get it each time i don't think about it and just paste rather than through the context menu

**Comment by roman-r-m** [comment]
I can't reproduce it. Which editor is it, WYSIWYG or markdown?

**Comment by Nilliom** [comment]
The WYSIWYG editor I press the toggle button and get only one large window rather than the split window. And that's in that editor (The M arrow down is not lighted up)

Here is my version of Joplin  

Joplin 2.7.14 (prod, win32)

Client ID: b19b7bece2c74434927f20d45ea17e6c
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 75cc9d7

**Comment by rpld** [comment]
Happening here too.

Regarding repro: issue is related to where we paste. Try pasting to a different note, and in places that have different formatting (bullets/headings/regular text).

Also, this looks like a regression, issue only started happening in recent versions.

BTW: thanks OP for the workaround of using Paste from the menu, would never have thought to try it.

Joplin 2.7.15 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: 8352e23

**Comment by Nilliom** [comment]
No it is not fixed, and encounter this bug daily. Somebody was able to reproduce but it didn't go further

**Comment by Nilliom** [comment]
No it is not fixed, and encounter this bug daily.

**Comment by Nilliom** [comment]
Still occuring each day

**Comment by Nilliom** [comment]
Still not solved

**Comment by rpld** [comment]
No new releases since the last auto-nag, so how could it have been fixed?

**Comment by Nilliom** [comment]
No still not fixed. Wonder if it will ever be.

**Comment by wh201906** [comment]
Hi. I figured out why the behaviors of `Ctrl+V` and right click->Paste are different.
Assuming that you have copied this text:
```
Test1

Test2

Test3
```
The former will call `onPaste()` in `packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx`. This function will insert something like this:
```
<html>
<body>
<!--StartFragment--><p>Test1</p>
<p>Test2</p>
<p>Test3</p><!--EndFragment-->
</body>
</html>
```
The latter will call `onAction()` of `Paste` button in `packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts`. This function will insert something like this:
```
<p>Test1</p>
<p>Test2</p>
<p>Test3</p>
```

**Comment by wh201906** [comment]
> Also, this looks like a regression, issue only started happening in recent versions.

@rpld Hi. Can you provide the version which doesn't have the problem you provided? 

> Regarding repro: issue is related to where we paste. Try pasting to a different note, and in places that have different formatting (bullets/headings/regular text).

Plus, does the recent version(v2.9.11 and later) fixes the problem you described? I only tested the content with `<p>` tag there

**Comment by rpld** [comment]
Hi and thank you so much for fixing it!
> does the recent version(v2.9.11 and later) fixes the problem you described?

Tested with 2.9.12 and it seems to work great now :) I'll keep working with it and notify if there is a problem. Attaching my simple test note - copy pasting the text from "the stuff to copy" to "Insert to Here" now works as expected, in stable version it lost the bullets and headers.
[test note.txt](https://github.com/laurent22/joplin/files/9939445/test.note.txt)

> @rpld Hi. Can you provide the version which doesn't have the problem you provided?

I don't know the old version where it was ok previously. If you think finding it will help, let me know and I'll download and test old versions.

**Comment by wh201906** [comment]
@rpld Thank you for your confirming!

> I don't know the old version where it was ok previously. If you think finding it will help, let me know and I'll download and test old versions.

If the recent versions work fine then there is no need to test them.

**Comment by Nilliom** [comment]
I tried with version beta 2.9.11 and my issue is resolved. Thanks a lot!

**Comment by wh201906** [comment]
You're welcome.

**Comment by dreaded369** [comment]
Still exists on OSX. Fresh install - no plugins. Only customisations were enabling dark mode and connecting dropbox.

Joplin 2.9.17 (prod, darwin)

Client ID: 62b26f3ca00f4663aeff8a35194c5833
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes
Revision: a84a8e7

Edit: actually in rich text mode I can't paste text with line breaks using CTRL-v or Edit->Paste. Line breaks are preserved in Markdown.

**Comment by wh201906** [comment]
@dreadedhamish Could you please create a new issue for it? I guess it's better because this issue was closed.

**Comment by dreaded369** [comment]
> Still exists on OSX. Fresh install - no plugins. Only customisations were enabling dark mode and connecting dropbox.
> 
> Joplin 2.9.17 (prod, darwin)
> 
> Client ID: 62b26f3ca00f4663aeff8a35194c5833 Sync Version: 3 Profile Version: 41 Keychain Supported: Yes Revision: [a84a8e7](https://github.com/laurent22/joplin/commit/a84a8e7710980f2d3c4f0bfabf8fb87876f2536a)
> 
> Edit: actually in rich text mode I can't paste text with line breaks using CTRL-v or Edit->Paste. Line breaks are preserved in Markdown.

will do
