### ISSUE TITLE
WebDav sync error

### ISSUE THREAD

**Issue by alabotski** [laurent22/joplin#6450]
Joplin version:  Android Mac (2.7.15) Windows (2.7.15)
Platform: Android Mac Windows
OS specifics: 

Trying to sync with my Kinetic router where WebDav is configured

Checking the connection shows that everything is configured successfully
<img width="406" alt="image" src="https://user-images.githubusercontent.com/439337/164966020-2cab1765-295c-4691-a3e9-a47f7aa326bd.png">

But when I try to sync I get this error
```
Completed: 24/04/2022 10:44 (42s)
Last error: Error: PUT locks/2_1_7800db619e2945c79d85dc92f7ea5acd.json: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>412 Precondition Failed</title> </head> <body> <h1>412 Precondition Failed</h1> </body> </html>
```
Two empty folders are simply created on the server

- temp
- locks

**Comment by roman-r-m** [comment]
I think this can happen if more than one device is trying to do the initial sync at the same time.

**Comment by alabotski** [comment]
No I sync only from one device.

![image](https://user-images.githubusercontent.com/439337/164993837-8cfed729-fb3d-4208-8d50-8d9ae4737b1e.png)

**Comment by alabotski** [comment]
I think problem with Keenetic  WebDac
[link](https://help.keenetic.com/hc/en-us/articles/360012308540-%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA-USB-%D0%B4%D0%B8%D1%81%D0%BA%D1%83-%D0%BF%D0%BE-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D1%83-WebDAV)

Some time ago I had a similar issue with SFTP
I wrote to the author of FTPPrush, he corrected it in his release (3.5.1)
https://www.wftpserver.com/releasenotes.htm

Maybe it's the same here?

**Comment by roman-r-m** [comment]
It's possible. Any logs on the server?

**Comment by alabotski** [comment]
@roman-r-m 
Request goes here
https://XXX.keenetic.pro/webdav/

Nothing reaches my router, so there are no logs from my side

**Comment by inste** [comment]
Keenetic uses lighttpd with mod_webdav as a server. Can you reproduce this problem on generic lighttpd?

**Comment by karlitos** [comment]
I have the exact same issue too on Mac with Joplin 2.7.15. I use __lighttpd__ with __mod_webdav__ as a server. I use HTTPS with certificate from LetsEncrypt.

There was an warning message in the console in the developer tools
```javascript
Logger.ts:219 00:04:30: FileApi: Could not retrieve remote date - defaulting to device date: Error: PUT temp/timeCheck290624.txt: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>

    at newError (/Applications/Joplin…ib/WebDavApi.js:414)
    at WebDavApi.exec (/Applications/Joplin…ib/WebDavApi.js:444)
    at processTicksAndRejections (internal/process/task_queues.js:95)
    at async FileApiDriverWebDav.put (/Applications/Joplin…river-webdav.js:201)
```

followed by an error:

```javascript
Logger.ts:219 00:04:51: Synchronizer: Error: PUT locks/2_1_058bd161cea54f63a2063c26bb43d608.json: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>

    at newError (/Applications/Joplin…ib/WebDavApi.js:414)
    at WebDavApi.exec (/Applications/Joplin…ib/WebDavApi.js:444)
    at processTicksAndRejections (internal/process/task_queues.js:95)
    at async FileApiDriverWebDav.put (/Applications/Joplin…river-webdav.js:201)```
```
<details><summary>The whole log looks like this:</summary>

```
00:04:30: FileApi: Could not retrieve remote date - defaulting to device date: Error: PUT temp/timeCheck290624.txt: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>

    at newError (/Applications/Joplin…ib/WebDavApi.js:414)
    at WebDavApi.exec (/Applications/Joplin…ib/WebDavApi.js:444)
    at processTicksAndRejections (internal/process/task_queues.js:95)
    at async FileApiDriverWebDav.put (/Applications/Joplin…river-webdav.js:201)
Logger.ts:219 00:04:51: Synchronizer: Error: PUT locks/2_1_058bd161cea54f63a2063c26bb43d608.json: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>

    at newError (/Applications/Joplin…ib/WebDavApi.js:414)
    at WebDavApi.exec (/Applications/Joplin…ib/WebDavApi.js:444)
    at processTicksAndRejections (internal/process/task_queues.js:95)
    at async FileApiDriverWebDav.put (/Applications/Joplin…river-webdav.js:201)
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:09: MKCOL https://pim.karlitos.net/webdav/temp/ {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-62605","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:09: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>405 Method Not Allowed</title>
 </head>
 <body>
  <h1>405 Method Not Allowed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:09: PROPFIND https://pim.karlitos.net/webdav/locks/ {"headers":{"Depth":1,"Authorization":"********","Content-Type":"text/xml","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-22158","User-Agent":"Joplin/1.0","Content-Length":"190"},"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\t\t\t<d:propfind xmlns:d=\"DAV:\">\n\t\t\t\t<d:prop xmlns:oc=\"http://owncloud.org/ns\">\n\t\t\t\t\t<d:getlastmodified/><d:resourcetype/>\n\t\t\t\t</d:prop>\n\t\t\t</d:propfind>","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:09: <?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns0="urn:uuid:c2f41010-65b3-11d1-a29f-00aa00c14882/">
<D:response>
<D:href>/webdav/locks/</D:href>
<D:propstat>
<D:prop>
<D:getlastmodified ns0:dt="dateTime.rfc1123">Sun, 01 May 2022 20:50:18 GMT</D:getlastmodified><D:resourcetype><D:collection/></D:resourcetype></D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:09: PUT https://pim.karlitos.net/webdav/temp/timeCheck290624.txt {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-27374","User-Agent":"Joplin/1.0","Content-Length":"9"},"body":"timeCheck","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:09: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:13: PUT https://pim.karlitos.net/webdav/temp/timeCheck290624.txt {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-45807","User-Agent":"Joplin/1.0","Content-Length":"9"},"body":"timeCheck","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:13: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:20: PUT https://pim.karlitos.net/webdav/temp/timeCheck290624.txt {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-57440","User-Agent":"Joplin/1.0","Content-Length":"9"},"body":"timeCheck","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:20: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:30: PUT https://pim.karlitos.net/webdav/temp/timeCheck290624.txt {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-51922","User-Agent":"Joplin/1.0","Content-Length":"9"},"body":"timeCheck","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:30: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:30: PUT https://pim.karlitos.net/webdav/locks/2_1_058bd16….json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-87661","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":2,\"clientType\":1,\"clientId\":\"058bd161cea54f63a2063c26bb43d608\"}","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:30: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:34: PUT https://pim.karlitos.net/webdav/locks/2_1_058bd16….json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-52286","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":2,\"clientType\":1,\"clientId\":\"058bd161cea54f63a2063c26bb43d608\"}","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:34: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:41: PUT https://pim.karlitos.net/webdav/locks/2_1_058bd16….json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-46904","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":2,\"clientType\":1,\"clientId\":\"058bd161cea54f63a2063c26bb43d608\"}","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:41: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:51: PUT https://pim.karlitos.net/webdav/locks/2_1_058bd16….json {"headers":{"Authorization":"********","Content-Type":"text/plain","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-41947","User-Agent":"Joplin/1.0","Content-Length":"71"},"body":"{\"type\":2,\"clientType\":1,\"clientId\":\"058bd161cea54f63a2063c26bb43d608\"}","ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:51: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Req 00:04:51: DELETE https://pim.karlitos.net/webdav/locks/2_1_058bd16….json {"headers":{"Authorization":"********","Cache-Control":"no-store","If-None-Match":"JoplinIgnore-78088","User-Agent":"Joplin/1.0"},"ignoreTlsErrors":false,"timeout":120000,"maxRetry":0}
Logger.ts:219 00:04:51: Synchronizer: Res 00:04:51: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>
Logger.ts:219 00:04:51: Synchronizer: Sync: finished: Synchronisation finished [1651615449074]
Logger.ts:219 00:04:51: Synchronizer: Operations completed: 
Logger.ts:219 00:04:51: Synchronizer: Total folders: 0
Logger.ts:219 00:04:51: Synchronizer: Total notes: 0
Logger.ts:219 00:04:51: Synchronizer: Total resources: 0
Logger.ts:219 00:04:51: Synchronizer: There was some errors:
Logger.ts:219 00:04:51: Synchronizer: Error: PUT locks/2_1_058bd161cea54f63a2063c26bb43d608.json: Unknown error 2 (412): <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>412 Precondition Failed</title>
 </head>
 <body>
  <h1>412 Precondition Failed</h1>
 </body>
</html>

    at newError (/Applications/Joplin…ib/WebDavApi.js:414)
    at WebDavApi.exec (/Applications/Joplin…ib/WebDavApi.js:444)
    at processTicksAndRejections (internal/process/task_queues.js:95)
    at async FileApiDriverWebDav.put (/Applications/Joplin…river-webdav.js:201)
Logger.ts:219 00:04:52: DecryptionWorker: cannot start because no master key is currently loaded.
Logger.ts:219 00:05:43: Trying to reload note that has been deleted: null
Logger.ts:219 00:08:00: RevisionService: maintenance: Starting...
Logger.ts:219 00:08:00: RevisionService: maintenance: Service is enabled
Logger.ts:219 00:08:00: RevisionService: collectRevisions: Created revisions for 0 notes
Logger.ts:219 00:08:00: RevisionService: maintenance: Done in 111ms
```
</details>

My Android App on the other hand does not even recognize the WebDAV at all and gives me  __Network request fail__:

```
5-03T23:48:14,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
```

<details><summary>Full Android debug log</summary>
<p>
```
Date,Level,Message
05-03T23:53:58,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:53:58,30,"RevisionService: ""RevisionService::maintenance: Done in 223ms""
05-03T23:53:58,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:53:58,30,"""ResourceService::indexNoteResources: Start""
05-03T23:53:58,30,"Synchronizer: ""Indexing resources...""
05-03T23:53:58,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651614838343]""
05-03T23:53:58,30,"""Starting scheduled sync""
05-03T23:53:58,30,"""Preparing scheduled sync""
05-03T23:53:58,30,"""Running background sync on timer...""
05-03T23:53:58,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:53:58,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:51:40,30,"RevisionService: ""RevisionService::maintenance: Done in 231ms""
05-03T23:51:40,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:51:40,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:51:40,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:51:01,30,"RevisionService: ""RevisionService::maintenance: Done in 149ms""
05-03T23:51:01,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:51:01,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:51:01,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:50:48,30,"RevisionService: ""RevisionService::maintenance: Done in 18236ms""
05-03T23:50:48,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:50:29,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:50:29,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:48:22,30,"RevisionService: ""RevisionService::maintenance: Done in 139ms""
05-03T23:48:22,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:48:22,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:48:22,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:48:15,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:48:14,30,"Synchronizer: ""Total notes: 5""
05-03T23:48:14,30,"Synchronizer: ""Total resources: 3""
05-03T23:48:14,30,"Synchronizer: ""Total folders: 1""
05-03T23:48:14,30,"Synchronizer: ""Operations completed: ""
05-03T23:48:14,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1651614472505]""
05-03T23:48:14,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
05-03T23:47:52,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:47:52,30,"RevisionService: ""RevisionService::maintenance: Done in 284019ms""
05-03T23:47:52,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:47:52,30,"RevisionService: ""RevisionService::maintenance: Done in 96ms""
05-03T23:47:52,30,"""ResourceService::indexNoteResources: Start""
05-03T23:47:52,30,"Synchronizer: ""Indexing resources...""
05-03T23:47:52,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651614472505]""
05-03T23:47:52,30,"""Starting scheduled sync""
05-03T23:47:52,30,"""Preparing scheduled sync""
05-03T23:47:52,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:47:52,30,"""Running background sync on timer...""
05-03T23:47:52,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:43:08,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:43:08,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:42:20,30,"RevisionService: ""RevisionService::maintenance: Done in 43802ms""
05-03T23:42:20,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:42:20,30,"RevisionService: ""RevisionService::maintenance: Done in 38ms""
05-03T23:42:20,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:42:20,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:41:36,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:41:36,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:40:37,30,"RevisionService: ""RevisionService::maintenance: Done in 1470ms""
05-03T23:40:37,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:40:36,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:40:36,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:39:52,30,"RevisionService: ""RevisionService::maintenance: Done in 177ms""
05-03T23:39:52,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:39:52,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:39:52,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:39:41,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:39:40,30,"Synchronizer: ""Total folders: 1""
05-03T23:39:40,30,"Synchronizer: ""Total notes: 5""
05-03T23:39:40,30,"Synchronizer: ""Total resources: 3""
05-03T23:39:40,30,"Synchronizer: ""Operations completed: ""
05-03T23:39:40,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1651613958722]""
05-03T23:39:40,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
05-03T23:39:18,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:39:18,30,"RevisionService: ""RevisionService::maintenance: Done in 261916ms""
05-03T23:39:18,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:39:18,30,"RevisionService: ""RevisionService::maintenance: Done in 162ms""
05-03T23:39:18,30,"""ResourceService::indexNoteResources: Start""
05-03T23:39:18,30,"Synchronizer: ""Indexing resources...""
05-03T23:39:18,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651613958722]""
05-03T23:39:18,30,"""Starting scheduled sync""
05-03T23:39:18,30,"""Preparing scheduled sync""
05-03T23:39:18,30,"""Running background sync on timer...""
05-03T23:39:18,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:39:18,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:34:56,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:34:56,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:34:13,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:34:12,30,"RevisionService: ""RevisionService::maintenance: Done in 281ms""
05-03T23:34:12,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:34:12,30,"Synchronizer: ""Total resources: 3""
05-03T23:34:12,30,"Synchronizer: ""Total notes: 5""
05-03T23:34:12,30,"Synchronizer: ""Total folders: 1""
05-03T23:34:12,30,"Synchronizer: ""Operations completed: ""
05-03T23:34:12,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:34:12,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:34:12,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1651613630719]""
05-03T23:34:12,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
05-03T23:33:50,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:33:50,30,"""ResourceService::indexNoteResources: Start""
05-03T23:33:50,30,"Synchronizer: ""Indexing resources...""
05-03T23:33:50,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651613630719]""
05-03T23:33:50,30,"""Starting scheduled sync""
05-03T23:33:50,30,"""Preparing scheduled sync""
05-03T23:33:50,30,"""Running background sync on timer...""
05-03T23:33:24,30,"RevisionService: ""RevisionService::maintenance: Done in 138ms""
05-03T23:33:24,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:33:24,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:33:24,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:31:48,30,"RevisionService: ""RevisionService::maintenance: Done in 254ms""
05-03T23:31:48,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:31:48,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:31:48,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:29:37,30,"RevisionService: ""RevisionService::maintenance: Done in 237ms""
05-03T23:29:37,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:29:36,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:29:36,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:29:03,30,"RevisionService: ""RevisionService::maintenance: Done in 373ms""
05-03T23:29:03,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:29:03,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:29:03,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:28:46,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:28:45,30,"Synchronizer: ""Total notes: 5""
05-03T23:28:45,30,"Synchronizer: ""Total resources: 3""
05-03T23:28:45,30,"Synchronizer: ""Total folders: 1""
05-03T23:28:45,30,"Synchronizer: ""Operations completed: ""
05-03T23:28:45,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1651613303391]""
05-03T23:28:45,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
05-03T23:28:23,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:28:23,30,"""ResourceService::indexNoteResources: Start""
05-03T23:28:23,30,"Synchronizer: ""Indexing resources...""
05-03T23:28:23,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651613303391]""
05-03T23:28:23,30,"""Starting scheduled sync""
05-03T23:28:23,30,"""Preparing scheduled sync""
05-03T23:28:17,30,"RevisionService: ""RevisionService::maintenance: Done in 129ms""
05-03T23:28:17,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:28:17,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:28:17,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:27:53,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:27:52,30,"Synchronizer: ""Total notes: 5""
05-03T23:27:52,30,"Synchronizer: ""Total resources: 3""
05-03T23:27:52,30,"Synchronizer: ""Total folders: 1""
05-03T23:27:52,30,"Synchronizer: ""Operations completed: ""
05-03T23:27:52,30,"Synchronizer: ""Sync: finished: Synchronisation finished [1651613250572]""
05-03T23:27:52,10,"Synchronizer: ""TypeError: Network request failed
index.android.bundle:108:8201
index.android.bundle:85:1257
k@index.android.bundle:85:500
callTimers@index.android.bundle:85:2653
value@index.android.bundle:38:3557
index.android.bundle:38:674
value@index.android.bundle:38:2504
value@index.android.bundle:38:646
value@[native code]""
05-03T23:27:30,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:27:30,30,"Synchronizer: ""Indexing resources...""
05-03T23:27:30,30,"""ResourceService::indexNoteResources: Start""
05-03T23:27:30,30,"Synchronizer: ""Sync: starting: Starting synchronisation to target 6... supportsAccurateTimestamp = false; supportsMultiPut = false [1651613250572]""
05-03T23:27:30,30,"""Starting scheduled sync""
05-03T23:27:30,30,"""Preparing scheduled sync""
05-03T23:27:26,30,"""ResourceService::deleteOrphanResources:", "[]""
05-03T23:27:26,30,"""ResourceService::indexNoteResources: Completed""
05-03T23:27:26,30,"RevisionService: ""RevisionService::maintenance: Done in 739ms""
05-03T23:27:25,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:27:25,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:27:25,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:27:25,30,"""ResourceService::indexNoteResources: Start""
05-03T23:25:52,30,"""SearchEngine: Updated FTS table in 387ms. Inserted: 5. Deleted: 0""
05-03T23:25:51,30,"""SearchEngine: Updating FTS table...""
05-03T23:25:48,30,"""Sync cancelled - no sync target is selected.""
05-03T23:25:48,30,"""Preparing scheduled sync""
05-03T23:25:47,30,"RevisionService: ""RevisionService::maintenance: Done in 434ms""
05-03T23:25:47,30,"RevisionService: ""RevisionService::collectRevisions: Created revisions for 0 notes""
05-03T23:25:47,30,"RevisionService: ""RevisionService::maintenance: Service is enabled""
05-03T23:25:47,30,"RevisionService: ""RevisionService::maintenance: Starting...""
05-03T23:25:43,30,"""Application initialized""
05-03T23:25:43,30,"RevisionService: ""RevisionService::runInBackground: Starting background service with revision collection interval 30000""
05-03T23:25:42,30,"""DecryptionWorker: cannot start because no master key is currently loaded.""
05-03T23:25:42,30,"""SearchEngine: Updating FTS table...""
05-03T23:25:42,30,"""Running migration: 35""
05-03T23:25:41,30,"""SearchEngine: Updating FTS table...""
05-03T23:25:41,30,"""Running migration: 33""
05-03T23:25:41,30,"""Running migration: 27""
05-03T23:25:41,30,"""ResourceFetcher: Auto-added resources: 0""
05-03T23:25:41,30,"""Running migration: 20""
05-03T23:25:41,30,"""ResourceFetcher: Auto-add resources: Mode: always""
05-03T23:25:41,30,"""Loading folders...""
05-03T23:25:41,30,"e2ee/utils: ""Trying to load 0 master keys...""
05-03T23:25:41,30,"e2ee/utils: ""Loaded master keys: 0""
05-03T23:25:41,30,"""Sync target: 0""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: mermaid/mermaid_render.js => /data/user/0/net.cozic.joplin/files/pluginAssets/mermaid/mermaid_render.js""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: mermaid/mermaid.min.js => /data/user/0/net.cozic.joplin/files/pluginAssets/mermaid/mermaid.min.js""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/katex.css => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/katex.css""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Typewriter-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Typewriter-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size4-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size4-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size3-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size3-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size2-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size2-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Size1-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Size1-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Script-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Script-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Italic.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_SansSerif-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_SansSerif-Bold.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Math-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Math-Italic.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Math-BoldItalic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Math-BoldItalic.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Italic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Italic.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-BoldItalic.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-BoldItalic.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Main-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Main-Bold.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Fraktur-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Fraktur-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Fraktur-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Fraktur-Bold.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Caligraphic-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Caligraphic-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_Caligraphic-Bold.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_Caligraphic-Bold.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: katex/fonts/KaTeX_AMS-Regular.woff2 => /data/user/0/net.cozic.joplin/files/pluginAssets/katex/fonts/KaTeX_AMS-Regular.woff2""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: highlight.js/atom-one-light.css => /data/user/0/net.cozic.joplin/files/pluginAssets/highlight.js/atom-one-light.css""
05-03T23:25:41,30,"""PluginAssetsLoader: Copying: highlight.js/atom-one-dark-reasonable.css => /data/user/0/net.cozic.joplin/files/pluginAssets/highlight.js/atom-one-dark-reasonable.css""
05-03T23:25:41,30,"""PluginAssetsLoader: Importing assets to /data/user/0/net.cozic.joplin/files/pluginAssets""
05-03T23:25:41,30,"""db.ftsEnabled = ", "1""
05-03T23:25:41,30,"""FTS check succeeded""
05-03T23:25:41,30,"models/Setting: ""Skipping all default migrations...""
05-03T23:25:41,30,"e2ee/utils: ""Master password is not set - trying to get it from the active master key...""
05-03T23:25:41,30,"""KeychainService: could not set test password - keychain support will be disabled""
05-03T23:25:41,30,"""KeychainService: checking if keychain supported""
05-03T23:25:41,30,"e2ee/utils: ""Loaded master keys: 0""
05-03T23:25:41,30,"e2ee/utils: ""Trying to load 0 master keys...""
05-03T23:25:41,30,"""Loading settings...""
05-03T23:25:41,30,"""Database is ready.""
05-03T23:25:39,30,"""Initializing tables...""
05-03T23:25:39,30,"""New version: 41. Previously recorded version: 0""
05-03T23:25:39,30,"""Converting database to version 41""
05-03T23:25:39,30,"""Converting database to version 40""
05-03T23:25:39,30,"""Converting database to version 39""
05-03T23:25:39,30,"""Converting database to version 38""
05-03T23:25:39,30,"""Converting database to version 37""
05-03T23:25:38,30,"""Converting database to version 36""
05-03T23:25:38,30,"""Converting database to version 35""
05-03T23:25:38,30,"""Migration failed with fallback and will not be repeated - saving version number""
05-03T23:25:38,30,"""Converting database to version 34""
05-03T23:25:38,30,"""Converting database to version 33""
05-03T23:25:38,30,"""Converting database to version 32""
05-03T23:25:38,30,"""Converting database to version 31""
05-03T23:25:38,30,"""Converting database to version 30""
05-03T23:25:38,30,"""Converting database to version 29""
05-03T23:25:38,30,"""Converting database to version 28""
05-03T23:25:38,30,"""Converting database to version 27""
05-03T23:25:38,30,"""Converting database to version 26""
05-03T23:25:38,30,"""Converting database to version 25""
05-03T23:25:38,30,"""Converting database to version 24""
05-03T23:25:38,30,"""Converting database to version 23""
05-03T23:25:37,30,"""Converting database to version 22""
05-03T23:25:37,30,"""Converting database to version 21""
05-03T23:25:37,30,"""Converting database to version 20""
05-03T23:25:37,30,"""Converting database to version 19""
05-03T23:25:37,30,"""Converting database to version 18""
05-03T23:25:37,30,"""Converting database to version 17""
05-03T23:25:37,30,"""Converting database to version 16""
05-03T23:25:37,30,"""Converting database to version 15""
05-03T23:25:37,30,"""Converting database to version 14""
05-03T23:25:37,30,"""Converting database to version 13""
05-03T23:25:37,30,"""Converting database to version 12""
05-03T23:25:37,30,"""Converting database to version 11""
05-03T23:25:37,30,"""Converting database to version 10""
05-03T23:25:37,30,"""Converting database to version 9""
05-03T23:25:37,30,"""Converting database to version 8""
05-03T23:25:37,30,"""Converting database to version 7""
05-03T23:25:37,30,"""Converting database to version 6""
05-03T23:25:37,30,"""Converting database to version 5""
05-03T23:25:37,30,"""Converting database to version 4""
05-03T23:25:37,30,"""Converting database to version 3""
05-03T23:25:36,30,"""Converting database to version 2""
05-03T23:25:36,30,"""Converting database to version 1""
05-03T23:25:36,30,"""Upgrading database from version 0""
05-03T23:25:36,30,"""Current database version", "null""
05-03T23:25:36,30,"""Checking for database schema update...""
05-03T23:25:36,30,"""Database was open successfully""
05-03T23:25:36,30,"""Starting application net.cozic.joplin-mobile v2.7.2 (prod)""
05-03T23:25:36,30,"""====================================""
================================================================================
type,id,updated_time,sync_time,is_conflict
```
</p>
</details>

**Comment by gstrauss** [comment]
Has anyone tested with lighttpd 1.4.64?
https://git.lighttpd.net/lighttpd/lighttpd1.4/commit/8a535e7e064b0c33c3b60a92df88b349d79b94c2

**Comment by karlitos** [comment]
Hello Glenn, I am going to as soon as I will figure out how to install lighttpd 1.4.64 on Armbian 22.02

**Comment by karlitos** [comment]
I installed lighttpd 1.4.64 from the debian unstable repository and can confirm, that the __412 Precondition Failed__ errors are gone.

I also tried to comment out the [line adding the "If-None-Match" header to the PROPFIND request](https://github.com/laurent22/joplin/blob/1f384c7ae44169df702c9ce498ff4b2e1d7d98eb/ReactNativeClient/lib/WebDavApi.js#L311) and this also _solved_ the 412 errors.

Maybe you could add a switch to the (advanced) settings which will allow to disable this header-workaround, since there are quite a lot other reports of this behavior around

**Comment by gstrauss** [comment]
tl;dr: upgrade the ancient version of lighttpd shipped with your poorly maintained distro.  (That applies to many, many distros.)

This issue and #1228 and #3457 were fixed in lighttpd 1.4.64
(and would have been fixed sooner if reported to lighttpd developers sooner).

Latest lighttpd release as I write this is lighttpd 1.4.65.

**Comment by RZarifov** [comment]
I still have this issue. Half a year have passed and lighttpd still haven't been upgraded?

**Comment by gstrauss** [comment]
What version of lighttpd are you running?  The latest lighttpd release is currently lighttpd 1.4.68.  If your distro has not upgraded, look in backports for your distro or complain to your distro to upgrade.

**Comment by RZarifov** [comment]
@gstrauss it's a router. Keenetic giga. Already messaged the support, they promised to let devs know about the issue.

**Comment by alabotski** [comment]
Keenetic router hasn't own  lighttpd

https://help.keenetic.com/hc/en-us/articles/360012308540-Connecting-to-a-USB-drive-via-WebDAV

**Comment by RZarifov** [comment]
well yes, but still it uses in it's firmware looks like? Or I'm getting all of this wrong? Then how can I setup WebDAV on my router then using or not using latest version of lighttpd, so I could have a WebDAV server on my router?

**Comment by alabotski** [comment]
I had many problems with SFTP
So I wrote authors of FTPRush , Mixplorer etc and they fixed on their side

in current situation I don't now...

**Comment by RZarifov** [comment]
Well I mailed tech support so... Fingers crossed.
