### ISSUE TITLE
New android device sync error with dropbox

### ISSUE THREAD

**Issue by zen-quo** [laurent22/joplin#6595]
## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android 12 on a Samsung device

## Steps to reproduce

1. Install the mobile app.
2. Configuration > Sync target = Dropbox
3. Authorize Dropbox.
4. Enter encryption key.

It did upload default notebook on the mobile but doesn't get my notes. Similarly, if I create a test notebook on mobile, I see it on my pc. Tried uninstalling twice and doing above steps again. Getting the same error.

## Describe what you expected to happen

Hello. I'm trying to sync this mobile device for the first time. My main device is a laptop with Windows 10. 

## Logfile

```
Last error: Error: uploadBlob: POST https://content.dropboxapi.com/2/files/upload: 
Error: RNFetchBIob request error: 
Unexpected char 0x131 at 10 in header name: dropbox-apı-argnull
```

**Comment by zen-quo** [comment]
Issue is solved thanks to a [comment on the forum](https://discourse.joplinapp.org/t/anyone-here-using-joplin-with-yandex-webdav-or-any-webdav-on-android/23948/7?u=zen-quo)! Just changed the language of the phone to English (and Joplin's too for good measure) and it works now!

**Comment by bulmust** [comment]
What do you mean _changed the language of the phone_?

> Issue is solved thanks to a [comment on the forum](https://discourse.joplinapp.org/t/anyone-here-using-joplin-with-yandex-webdav-or-any-webdav-on-android/23948/7?u=zen-quo)! Just changed the language of the phone to English (and Joplin's too for good measure) and it works now!

What do you mean _changed the language of the phone_? I change the language of app but still get similar err.

**Comment by zen-quo** [comment]
> What do you mean _changed the language of the phone_?

Go into Settings on your phone, search for Language. Set your primary language to English.

**Comment by zapatistay** [comment]
That only seems to temporarily fix it. The problem occurs again. It must have to do with language code in the phone. Mine is TR (Turkish) and this problem does not let me sync between devices. It only occurs on android as far as I can see.
