### ISSUE TITLE
Edits disappearing and duplicate files showing up in the Conflicts notebook

### ISSUE THREAD

**Issue by cmill72** [laurent22/joplin#70]
### Operating system

- [ ] Windows
- [ ] macOS
- [ x] Linux
- [ ] Android
- [ ] iOS

### Application

- [ x] Desktop
- [ ] Mobile
- [ ] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
This is what is happening exactly, I attempt to edit a note in a notebook and the edit will disappear and show up in the "Conflicts" notebook.  I was trying to add links using Markdown to some of the text.  I am successful at editing it on the Android app but that is much slower than doing it on the desktop.  I frequently have to redo the edit and several notes of the same name appear in the "Conflicts" notebook. I don't know if this will help or not but these notes were copied over from Google Keep. If you could tell me how to find the error message, I can add it to this post.

**Comment by laurent22** [comment]
Hello, that should be fixed in the [latest version](https://github.com/laurent22/joplin/releases/download/v0.10.36/Joplin-0.10.36-x86_64.AppImage). Please give it a try and let me know if it's any better.

**Comment by flipjs** [comment]
Is the terminal version (via npm) updated already?

**Comment by laurent22** [comment]
I don't think and it was and it had this problem too. I've just published the latest version.

**Comment by flipjs** [comment]
Just upgraded my terminal (npm) version to 0.10.78. Will let you know If I still get the 'conflicts' issue. Thanks.

**Comment by flipjs** [comment]
So far, no 'conflicts' using the terminal version (0.10.78).

**Comment by laurent22** [comment]
Great, good to know it's working now.

**Comment by alexdevero** [comment]
The Conflicts issue seems to be back. I was editing one note and while "Conflicts" folder appeared in the sidebar with copy of the note I was working with.

### Operating system

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by poopie-head** [comment]
### Operating system



- Windows


### Application



- Desktop



***
## Sync status (synced items / total items)

Note: 41/7
Folder: 11/4
Resource: 24/24
Tag: 7/7
NoteTag: 7/7
MasterKey: 0/0
Revision: 54/54
Total: 144/103
 
Conflicted: 1
To delete: 0
Folders
Welcome! (Desktop): 4 notes
Markdown: 1 notes
2019 BuJo: 1 notes
Conventions/Format: 1 notes
***

This is a particular "instance" of Joplin where I use a different profile I launch via a .bat file in a different directory. 
On editing a note it is immediately pushed into Conflicts. Synchronisation is disabled as i only use this set on notes on one device.
I don't know why this is happening, And the only way i can resolve it is my manually dragging the note into the right notebook. At some point I think I'm going to drag a note into the wrong notebook.



[syncReport-1560074361927.zip](https://github.com/laurent22/joplin/files/3269405/syncReport-1560074361927.zip)
