### ISSUE TITLE
Exporting Mermaid graph as PNG results in small low quality file

### ISSUE THREAD

**Issue by TC68** [laurent22/joplin#7783]
In some of my notes, I create mermaid graphs. It is very useful to be able to save these as PNG files for inclusion in reports or other documents.

Previously, I could right click on the graph and select "Save as PNG" and the graph would save as a good quality PNG file. After a recent update (not sure which one), the PNG files saved in this manner are small and of poor quality. I have attached one for reference.

A return to the earlier method/result would be great.

## Environment

Joplin version: Joplin 2.9.17 (prod, linux)

Client ID: 2e77cc265f47425ea61b4d7b7c1bbadc
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Platform:  Linux
OS specifics: Pop!_OS 22.04 LTS

## Steps to reproduce

1.  Create a mermaid graph
2.  Right click on the graph and choose "Save As"
3.  Save the file, then view it.

an example graph:

```mermaid
graph LR
%%{init: {'theme':'neutral'}}%%

%% legend ------------------------------------------
subgraph KEY[<b>LEGEND]
	ARROWS[<b>Arrows</b><br>Dashed: Potential Pathway<br>Solid: Probable Pathway<br>Thick: Dominant Pathway<p><b>Receptor Colours</b><br>Green: No Risk<br> Yellow: Potential Risk <br> Red: Probable Risk]
	%%COLOURS[]
end

%% sources---------------------------------------------
subgraph SRC[<b>SOURCES]
	SITE[/<b>Historical Site Activity</b><br>Metals, PAH, Asbestos\]
	FILL[/<b>Imported Fill</b><br>Metals, PAH, Asbestos\]
	HAZ[/<b>Building Materials</b><br>Lead, Asbestos\]
end

%% media-----------------------------------------------
subgraph MED[<b>MEDIA]
		GW[Groundwater]
		SV[Soil Vapour]
		SL[Soil];
end 

%% receptors------------------------------------------------
subgraph REC[<b>RECEPTORS]
	WKRS([Current and future intrusive<br>workers/maintenance workers])
	USERS([Current and future<br>site workers])
	OFFSITE([Residents of adjacent properties])
	ECO([Downgradient receptors])
end

%% contam methods
 SITE & FILL & HAZ == direct==> SL

%% exposure pathways 
	SL -. Risk removed through<br> remedial works .-> WKRS & USERS
	
	
%%----------------------------------------------------
%% colours
classDef darkblue fill:#84c0ff,stroke:#06f,stroke-width:0px
classDef riskbox fill:#f5abab,stroke:#000084,stroke-width:1px
classDef warnbox fill:#fff0ab,stroke:#000084,stroke-width:1px
classDef greenbox fill:#abf5ab,stroke:#000084,stroke-width:1px
classDef neutralbox fill:#cbcbcb,stroke:#000084,stroke-width:1px

class SRC,MED,REC darkblue
class USTS,SITE,FILL,HAZ neutralbox
class SL riskbox
class SL,WKRS warnbox
class GW,SV,WKRS,USERS,ECO,OFFSITE greenbox
```

## Describe what you expected to happen

A good quality PNG file is produced

## Logfile

This entry appears when right clicking the mermaid graph. No errors appear 
```
16:10:48: RevisionService: maintenance: Done in 105ms
useMessageHandler.ts:16 Got ipc-message: contextMenu {type: 'image', textToCopy: '<svg viewBox="-0.0000152587890625 0.00001525878906…iv></foreignObject></g></g></g></g></g></g></svg>', mime: 'image/svg+xml', filename: 'mermaid-1676522483741.svg'}
```

![mermaid-1676522483741](https://user-images.githubusercontent.com/8788393/219273468-931984da-63ed-4836-b715-6a60b25f8803.png)

**Comment by TC68** [comment]
Although the file I attached shows clearly in this bug report, it does not resolve clearly in the image viewer on my system, or in LibreOffice Writer when inserted into a document. Previously, this worked flawlessly.

**Comment by JackGruber** [comment]
This issue should be fixed in the next release. https://github.com/laurent22/joplin/issues/7521

**Comment by TC68** [comment]
Awesome, thanks

**Comment by TC68** [comment]
Recent up date did not (yet) include this fix. The problem is still present in Joplin 2.9.17 (prod, linux)

**Comment by JackGruber** [comment]
The fix is implemented in the 2.10.11 pre-release, the 2.9.17 is from November 2022

**Comment by TC68** [comment]
Excellent - thanks

**Comment by iRomanyshyn** [comment]
Guys, thank you for the work! Pre-release 2.10.12 exports the proper size PNG. I like it very much because I am using it to draw HUGE diagrams of computer networks. For me, it's ten times better than any other diagram editor. And Joplin is the easiest way to get a PNG image out of the Mermaid diagram code. I'm going to donate this.
