### ISSUE TITLE
Search in all the notes lose focus and switching to the note body

### ISSUE THREAD

**Issue by almadorx** [laurent22/joplin#7882]
When I'm trying to use the "`Search in all the notes`" function I could provide only a few letters, after that focus is switched to the note body, so I have to click on "`Search in all the notes`" once again and provide more letters. It could lose focus many times from this search field to the note field.

Also, the problem is the same when I'm trying to input data to "`Note title`" - it is always switching automatically to the `note body` while inputting text.  

And yes, in Tools -> Options -> Note my setting is "`Focus title`". Also, tried "`Focus body`", but no luck

## Environment

Joplin version: 2.9.17
Platform: Windows
OS specifics: Windows 10 home SL 21H2

## Steps to reproduce

1. Place the cursor in the Search field
2. Start providing letters 
3. After a few letter input focus is automatically switching to the Note body and other letters are going to the Note, not the Search field 

## Describe what you expected to happen

Focus should stay on the Search field

## Logfile
[debug.log](https://github.com/laurent22/joplin/files/10907210/debug.log)

**Comment by melsonic** [comment]
Just tried as you suggested, but in my case it's working fine. I am using it on linux btw. May be it's only related to windows.

**Comment by melsonic** [comment]
I just tried as you suggested, but in my case, it's working fine for me. I am using it on Linux btw. May be this issue persists only on windows.

**Comment by laurent22** [comment]
Isn't it fixed in 2.10?

**Comment by bobasaurus** [comment]
I was having this problem until I updated to the latest pre-release version 2.10.10.  Seems to be fixed now, thanks devs.

**Comment by hleskien** [comment]
@laurent22: I believe this bug is still there. I'm using current stable (2.12.19) on Linux. The focus <s>goes away as soon syncing starts</s> sometimes goes away on loading search results and doesn't come back until I click into the search field.
