### ISSUE TITLE
Slow and CPU-intensive startup with v2.10.15

### ISSUE THREAD

**Issue by iJorgen** [laurent22/joplin#8087]
## Environment

Joplin version: 2.10.15 with Joplin Cloud sync
Platform: Linux
OS specifics: Ubuntu 23.04

## Steps to reproduce

1. Installed the latest AppImage 2.10.15 over 2.10.13.
2. When starting Joplin it now takes over 60 seconds with high CPU compared to around 5 seconds before with 2.10.13 on the same machine/OS.

![Screenshot from 2023-04-27 07-22-35](https://user-images.githubusercontent.com/52280788/234767936-ac2f2720-d443-4b2c-a81f-2bd35f559a56.png)

## Describe what you expected to happen
A normal startup-time around 5 seconds, so something has happened with the latest build.

## Logfile

Joplin 2.10.15 (prod, linux)

Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: b84fc1c

**Comment by roman-r-m** [comment]
I think this version includes the change to use max compression, it could explain the issue.

**Comment by iJorgen** [comment]
Yeah, I noticed that too in the change-log and maybe a clue to the issue?! I use an Intel core i7 with 4 cores/8 threads and my storage is only 13 MB (just text) in the cloud, so should be no match to handle.

**Comment by laurent22** [comment]
I reverted to normal compression in this prerelease:

https://github.com/laurent22/joplin/releases/tag/v2.10.16

Would you mind giving it a try and letting me know how it affects your startup time?

**Comment by iJorgen** [comment]
Wow, that was quick... Tried the new version 2.10.16 and all is back to normal again with 4-5 seconds startup-time. Thanks!!! :-))

**Comment by laurent22** [comment]
Great, thanks for confirming. We'll leave it as "normal" then even if it means slightly larger executables for macOS and Linux.

**Comment by laurent22** [comment]
Fixed in 2e2feaba3dcd5a772367a33117ced65029adb9a0

**Comment by iJorgen** [comment]
This issue is back in the new pre-release (v2.11.3) with 60+ seconds to start the app.

![Screenshot from 2023-05-16 11-15-55](https://github.com/laurent22/joplin/assets/52280788/90a4b56d-596d-4665-8631-1d34ed0152b3)

**Comment by laurent22** [comment]
Right, sorry, the fix was applied to 2.10 but not 2.11. That will be fixed in the next pre-release

**Comment by iJorgen** [comment]
No worries!! Only noticeable during startup. Keep up the good work... :smiley:
