### ISSUE TITLE
Linkify error in Rich Text Editor, with links containing an underscore

### ISSUE THREAD

**Issue by cman-mario** [laurent22/joplin#9122]
## Environment

Joplin version: 2.12.19
Platform: Windows 11
OS specifics: 

## Steps to reproduce

1. If you copy a link from the web containing an underscore character "_" and paste it in the Rich Text Editor, it gets changed in a link (Linkify option flagged) but in the created link there's an error: a backslash is added and the underscore gets changed in a backslash and an underscore
2. For example, "https://en.wikipedia.org/wiki/Main_Page" gets changed in "https://en.wikipedia.org/wiki/Main\_Page"
3. If you paste the link in the Markdown Editor, all works fine

**Comment by laurent22** [comment]
This is fixed in pre-release 2.13

**Comment by cman-mario** [comment]
I downloaded Joplin 2.13.3, but the error is still showing. 
If I copy the link "https://en.wikipedia.org/wiki/Main_Page", it still gets changed in "[https://en.wikipedia.org/wiki/Main\_Page](https://en.wikipedia.org/wiki/Main%5C_Page)"

**Comment by laurent22** [comment]
Ok, this is strange as that should have been fixed in this issue: https://github.com/laurent22/joplin/issues/8743

@personalizedrefrigerator, any idea about this? I can indeed replicate the bug in last dev version.

**Comment by personalizedrefrigerator** [comment]
> Ok, this is strange as that should have been fixed in this issue: #8743
> 
> @personalizedrefrigerator, any idea about this? I can indeed replicate the bug in last dev version.

It looks like it's only fixed in some cases. Pasting the link, then converting it to a link (with <kbd>ctrl</kbd>+<kbd>k</kbd>) preserves underscores. If it isn't converted to a link, underscores are not preserved.

Similarly, pasting the link into the markdown editor, then switching to the rich text editor and editing, preserves the link.

A better fix might be to only escape underscores that are at the beginning of words (e.g. `_test_` -> `\_test_`) as this (from limited testing) seems to be sufficient.
**Edit**: That fix is not sufficient (e.g. `main❯_page_` does cause `page` to be italicized). Perhaps we could only escape it if the previous character is punctuation or a space (it seems to be sufficient for `從英文_翻譯而來。_`)?
